use oxedyne_fe2o3_core::prelude::*;

use std::{
    fmt::{
        self,
        Display,
    },
    str::FromStr,
};


/// [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml)
#[allow(non_camel_case_types)]
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum Charset {
    Us_Ascii,
    Iso8859_1_1987,
    Iso8859_2_1987,
    Iso8859_3_1988,
    Iso8859_4_1988,
    Iso8859_5_1988,
    Iso8859_6_1987,
    Iso8859_7_1987,
    Iso8859_8_1988,
    Iso8859_9_1989,
    Iso8859_10,
    Iso6937_2_Add,
    Jis_x0201,
    Jis_encoding,
    Shift_jis,
    Extended_unix_code_packed_format_for_japanese,
    Extended_unix_code_fixed_width_for_japanese,
    Bs_4730,
    Sen_850200_c,
    It,
    Es,
    Din_66003,
    Ns_4551_1,
    Nf_z_62_010,
    Iso_10646_Utf_1,
    Iso_646_Basic_1983,
    Invariant,
    Iso_646_Irv_1983,
    Nats_Sefi,
    Nats_Sefi_Add,
    Nats_Dano,
    Nats_Dano_Add,
    Sen_850200_b,
    Ks_c_5601_1987,
    Iso_2022_Kr,
    Euc_Kr,
    Iso_2022_Jp,
    Iso_2022_Jp_2,
    Jis_c6220_1969_Jp,
    Jis_c6220_1969_Ro,
    Pt,
    Greek7_Old,
    Latin_Greek,
    Nf_z_62_010_1973,
    Latin_Greek_1,
    Iso_5427,
    Jis_c6226_1978,
    Bs_viewdata,
    Inis,
    Inis_8,
    Inis_Cyrillic,
    Iso_5427_1981,
    Iso_5428_1980,
    Gb_1988_80,
    Gb_2312_80,
    Ns_4551_2,
    Videotex_Suppl,
    Pt2,
    Es2,
    Msz_7795_3,
    Jis_c6226_1983,
    Greek7,
    Asmo_449,
    Iso_Ir_90,
    Jis_c6229_1984_A,
    Jis_c6229_1984_B,
    Jis_c6229_1984_B_Add,
    Jis_c6229_1984_Hand,
    Jis_c6229_1984_Hand_Add,
    Jis_c6229_1984_Kana,
    Iso_2033_1983,
    Ansi_x3_110_1983,
    T_61_7bit,
    T_61_8bit,
    Ecma_Cyrillic,
    Csa_z243_4_1985_1,
    Csa_z243_4_1985_2,
    Csa_z243_4_1985_Gr,
    Iso_8859_6_E,
    Iso_8859_6_I,
    T_101_G2,
    Iso_8859_8_E,
    Iso_8859_8_I,
    Csn_369103,
    Jus_i_B1_002,
    Iec_p27_1,
    Jus_i_B1_003_Serb,
    Jus_i_B1_003_Mac,
    Greek_Ccitt,
    Nc_nc00_10_81,
    Iso_6937_2_25,
    Gost_19768_74,
    Iso_8859_Supp,
    Iso_10367_Box,
    Latin_Lap,
    Jis_x0212_1990,
    Ds_2089,
    Us_Dk,
    Dk_Us,
    Ksc5636,
    Unicode_1_1_Utf_7,
    Iso_2022_Cn,
    Iso_2022_Cn_Ext,
    Utf_8,
    Iso_8859_13,
    Iso_8859_14,
    Iso_8859_15,
    Iso_8859_16,
    Gbk,
    Gb18030,
    Osd_ebcdic_df04_15,
    Osd_ebcdic_df03_irv,
    Osd_ebcdic_df04_1,
    Iso_11548_1,
    Kz_1048,
    Iso_10646_Ucs_2,
    Iso_10646_Ucs_4,
    Iso_10646_Ucs_Basic,
    Iso_10646_Unicode_Latin1,
    Iso_10646_J_1,
    Iso_Unicode_Ibm_1261,
    Iso_Unicode_Ibm_1268,
    Iso_Unicode_Ibm_1276,
    Iso_Unicode_Ibm_1264,
    Iso_Unicode_Ibm_1265,
    Unicode_1_1,
    Scsu,
    Utf_7,
    Utf_16be,
    Utf_16le,
    Utf_16,
    Cesu_8,
    Utf_32,
    Utf_32be,
    Utf_32le,
    Bocu_1,
    Utf_7_Imap,
    Iso_8859_1_Windows_3_0_Latin_1,
    Iso_8859_1_Windows_3_1_Latin_1,
    Iso_8859_2_Windows_Latin_2,
    Iso_8859_9_Windows_Latin_5,
    Hp_Roman8,
    Adobe_Standard_Encoding,
    Ventura_Us,
    Ventura_International,
    Dec_Mcs,
    Ibm850,
    Pc8_Danish_Norwegian,
    Ibm862,
    Pc8_Turkish,
    Ibm_Symbols,
    Ibm_Thai,
    Hp_Legal,
    Hp_Pi_Font,
    Hp_Math8,
    Adobe_Symbol_Encoding,
    Hp_Desktop,
    Ventura_Math,
    Microsoft_Publishing,
    Windows_31j,
    Gb2312,
    Big5,
    Macintosh,
    Ibm037,
    Ibm038,
    Ibm273,
    Ibm274,
    Ibm275,
    Ibm277,
    Ibm278,
    Ibm280,
    Ibm281,
    Ibm284,
    Ibm285,
    Ibm290,
    Ibm297,
    Ibm420,
    Ibm423,
    Ibm424,
    Ibm437,
    Ibm500,
    Ibm851,
    Ibm852,
    Ibm855,
    Ibm857,
    Ibm860,
    Ibm861,
    Ibm863,
    Ibm864,
    Ibm865,
    Ibm868,
    Ibm869,
    Ibm870,
    Ibm871,
    Ibm880,
    Ibm891,
    Ibm903,
    Ibm904,
    Ibm905,
    Ibm918,
    Ibm1026,
    Ebcdic_At_De,
    Ebcdic_At_De_A,
    Ebcdic_Ca_Fr,
    Ebcdic_Dk_No,
    Ebcdic_Dk_No_A,
    Ebcdic_Fi_Se,
    Ebcdic_Fi_Se_A,
    Ebcdic_Fr,
    Ebcdic_It,
    Ebcdic_Pt,
    Ebcdic_Es,
    Ebcdic_Es_A,
    Ebcdic_Es_S,
    Ebcdic_Uk,
    Ebcdic_Us,
    Unknown_8bit,
    Mnemonic,
    Mnem,
    Viscii,
    Viqr,
    Koi8_R,
    Hz_Gb_2312,
    Ibm866,
    Ibm775,
    Koi8_U,
    Ibm00858,
    Ibm00924,
    Ibm01140,
    Ibm01141,
    Ibm01142,
    Ibm01143,
    Ibm01144,
    Ibm01145,
    Ibm01146,
    Ibm01147,
    Ibm01148,
    Ibm01149,
    Big5_Hkscs,
    Ibm1047,
    Ptcp154,
    Amiga_1251,
    Koi7_Switched,
    Brf,
    Tscii,
    Cp51932,
    Windows_874,
    Windows_1250,
    Windows_1251,
    Windows_1252,
    Windows_1253,
    Windows_1254,
    Windows_1255,
    Windows_1256,
    Windows_1257,
    Windows_1258,
    Tis_620,
    Cp50220,
}

impl Display for Charset {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", match self {
            Self::Us_Ascii						                    => "us-ascii",                                     
            Self::Iso8859_1_1987						            => "iso_8859-1:1987",                              
            Self::Iso8859_2_1987						            => "iso_8859-2:1987",                              
            Self::Iso8859_3_1988						            => "iso_8859-3:1988",                              
            Self::Iso8859_4_1988						            => "iso_8859-4:1988",                              
            Self::Iso8859_5_1988						            => "iso_8859-5:1988",                              
            Self::Iso8859_6_1987						            => "iso_8859-6:1987",                              
            Self::Iso8859_7_1987						            => "iso_8859-7:1987",                              
            Self::Iso8859_8_1988						            => "iso_8859-8:1988",                              
            Self::Iso8859_9_1989						            => "iso_8859-9:1989",                              
            Self::Iso8859_10						                => "iso-8859-10",                                  
            Self::Iso6937_2_Add						                => "iso_6937-2-add",                               
            Self::Jis_x0201						                    => "jis_x0201",                                    
            Self::Jis_encoding						                => "jis_encoding",                                 
            Self::Shift_jis						                    => "shift_jis",                                    
            Self::Extended_unix_code_packed_format_for_japanese		=> "extended_unix_code_packed_format_for_japanese",
            Self::Extended_unix_code_fixed_width_for_japanese		=> "extended_unix_code_fixed_width_for_japanese",  
            Self::Bs_4730						                    => "bs_4730",                                      
            Self::Sen_850200_c						                => "sen_850200_c",                                 
            Self::It						                        => "it",                                           
            Self::Es						                        => "es",                                           
            Self::Din_66003						                    => "din_66003",                                    
            Self::Ns_4551_1						                    => "ns_4551-1",                                    
            Self::Nf_z_62_010						                => "nf_z_62-010",                                  
            Self::Iso_10646_Utf_1						            => "iso-10646-utf-1",                              
            Self::Iso_646_Basic_1983						        => "iso_646.basic:1983",                           
            Self::Invariant						                    => "invariant",                                    
            Self::Iso_646_Irv_1983						            => "iso_646.irv:1983",                             
            Self::Nats_Sefi						                    => "nats-sefi",                                    
            Self::Nats_Sefi_Add						                => "nats-sefi-add",                                
            Self::Nats_Dano						                    => "nats-dano",                                    
            Self::Nats_Dano_Add						                => "nats-dano-add",                                
            Self::Sen_850200_b						                => "sen_850200_b",                                 
            Self::Ks_c_5601_1987						            => "ks_c_5601-1987",                               
            Self::Iso_2022_Kr						                => "iso-2022-kr",                                  
            Self::Euc_Kr						                    => "euc-kr",                                       
            Self::Iso_2022_Jp						                => "iso-2022-jp",                                  
            Self::Iso_2022_Jp_2						                => "iso-2022-jp-2",                                
            Self::Jis_c6220_1969_Jp						            => "jis_c6220-1969-jp",                            
            Self::Jis_c6220_1969_Ro						            => "jis_c6220-1969-ro",                            
            Self::Pt						                        => "pt",                                           
            Self::Greek7_Old						                => "greek7-old",                                   
            Self::Latin_Greek						                => "latin-greek",                                  
            Self::Nf_z_62_010_1973						            => "nf_z_62-010_(1973)",                           
            Self::Latin_Greek_1						                => "latin-greek-1",                                
            Self::Iso_5427						                    => "iso_5427",                                     
            Self::Jis_c6226_1978						            => "jis_c6226-1978",                               
            Self::Bs_viewdata						                => "bs_viewdata",                                  
            Self::Inis						                        => "inis",                                         
            Self::Inis_8						                    => "inis-8",                                       
            Self::Inis_Cyrillic						                => "inis-cyrillic",                                
            Self::Iso_5427_1981						                => "iso_5427:1981",                                
            Self::Iso_5428_1980						                => "iso_5428:1980",                                
            Self::Gb_1988_80						                => "gb_1988-80",                                   
            Self::Gb_2312_80						                => "gb_2312-80",               
            Self::Ns_4551_2						                    => "ns_4551-2",                                    
            Self::Videotex_Suppl					                => "videotex-suppl",                               
            Self::Pt2						                        => "pt2",                                          
            Self::Es2						                        => "es2",                                          
            Self::Msz_7795_3						                => "msz_7795.3",                                   
            Self::Jis_c6226_1983					                => "jis_c6226-1983",                               
            Self::Greek7						                    => "greek7",                                       
            Self::Asmo_449						                    => "asmo_449",                                     
            Self::Iso_Ir_90						                    => "iso-ir-90",                                    
            Self::Jis_c6229_1984_A					                => "jis_c6229-1984-a",                             
            Self::Jis_c6229_1984_B					                => "jis_c6229-1984-b",                             
            Self::Jis_c6229_1984_B_Add				                => "jis_c6229-1984-b-add",                         
            Self::Jis_c6229_1984_Hand				                => "jis_c6229-1984-hand",                          
            Self::Jis_c6229_1984_Hand_Add			                => "jis_c6229-1984-hand-add",                      
            Self::Jis_c6229_1984_Kana				                => "jis_c6229-1984-kana",                          
            Self::Iso_2033_1983						                => "iso_2033-1983",                                
            Self::Ansi_x3_110_1983					                => "ansi_x3.110-1983",                             
            Self::T_61_7bit						                    => "t.61-7bit",                                    
            Self::T_61_8bit						                    => "t.61-8bit",                                    
            Self::Ecma_Cyrillic						                => "ecma-cyrillic",                                
            Self::Csa_z243_4_1985_1					                => "csa_z243.4-1985-1",                            
            Self::Csa_z243_4_1985_2					                => "csa_z243.4-1985-2",                            
            Self::Csa_z243_4_1985_Gr				                => "csa_z243.4-1985-gr",                           
            Self::Iso_8859_6_E						                => "iso_8859-6-e",                                 
            Self::Iso_8859_6_I						                => "iso_8859-6-i",                                 
            Self::T_101_G2						                    => "t.101-g2",                                     
            Self::Iso_8859_8_E						                => "iso_8859-8-e",                                 
            Self::Iso_8859_8_I						                => "iso_8859-8-i",                                 
            Self::Csn_369103						                => "csn_369103",                                   
            Self::Jus_i_B1_002						                => "jus_i.b1.002",                                 
            Self::Iec_p27_1						                    => "iec_p27-1",                                    
            Self::Jus_i_B1_003_Serb					                => "jus_i.b1.003-serb",                            
            Self::Jus_i_B1_003_Mac					                => "jus_i.b1.003-mac",                             
            Self::Greek_Ccitt						                => "greek-ccitt",                                  
            Self::Nc_nc00_10_81						                => "nc_nc00-10:81",                                
            Self::Iso_6937_2_25						                => "iso_6937-2-25",                                
            Self::Gost_19768_74						                => "gost_19768-74",                                
            Self::Iso_8859_Supp						                => "iso_8859-supp",                                
            Self::Iso_10367_Box						                => "iso_10367-box",                                
            Self::Latin_Lap						                    => "latin-lap",                                    
            Self::Jis_x0212_1990					                => "jis_x0212-1990",                               
            Self::Ds_2089						                    => "ds_2089",                                      
            Self::Us_Dk						                        => "us-dk",                                        
            Self::Dk_Us						                        => "dk-us",                                        
            Self::Ksc5636						                    => "ksc5636",                                      
            Self::Unicode_1_1_Utf_7					                => "unicode-1-1-utf-7",                            
            Self::Iso_2022_Cn						                => "iso-2022-cn",                                  
            Self::Iso_2022_Cn_Ext					                => "iso-2022-cn-ext",                              
            Self::Utf_8						                        => "utf-8",                                        
            Self::Iso_8859_13						                => "iso-8859-13",                                  
            Self::Iso_8859_14						                => "iso-8859-14",                                  
            Self::Iso_8859_15						                => "iso-8859-15",                                  
            Self::Iso_8859_16						                => "iso-8859-16",                                  
            Self::Gbk						                        => "gbk",                                          
            Self::Gb18030						                    => "gb18030",                                      
            Self::Osd_ebcdic_df04_15				                => "osd_ebcdic_df04_15",                           
            Self::Osd_ebcdic_df03_irv				                => "osd_ebcdic_df03_irv",                          
            Self::Osd_ebcdic_df04_1					                => "osd_ebcdic_df04_1",                            
            Self::Iso_11548_1						                => "iso-11548-1",                                  
            Self::Kz_1048						                    => "kz-1048",                                      
            Self::Iso_10646_Ucs_2					                => "iso-10646-ucs-2",                              
            Self::Iso_10646_Ucs_4					                => "iso-10646-ucs-4",                              
            Self::Iso_10646_Ucs_Basic				                => "iso-10646-ucs-basic",                          
            Self::Iso_10646_Unicode_Latin1			                => "iso-10646-unicode-latin1",                     
            Self::Iso_10646_J_1						                => "iso-10646-j-1",                                
            Self::Iso_Unicode_Ibm_1261				                => "iso-unicode-ibm-1261",                         
            Self::Iso_Unicode_Ibm_1268				                => "iso-unicode-ibm-1268",                         
            Self::Iso_Unicode_Ibm_1276				                => "iso-unicode-ibm-1276",                         
            Self::Iso_Unicode_Ibm_1264				                => "iso-unicode-ibm-1264",                         
            Self::Iso_Unicode_Ibm_1265				                => "iso-unicode-ibm-1265",                         
            Self::Unicode_1_1						                => "unicode-1-1",                                  
            Self::Scsu						                        => "scsu",                                         
            Self::Utf_7						                        => "utf-7",                                        
            Self::Utf_16be						                    => "utf-16be",                                     
            Self::Utf_16le						                    => "utf-16le",                                     
            Self::Utf_16						                    => "utf-16",                                       
            Self::Cesu_8						                    => "cesu-8",                                       
            Self::Utf_32						                    => "utf-32",                                       
            Self::Utf_32be						                    => "utf-32be",                                     
            Self::Utf_32le						                    => "utf-32le",                                     
            Self::Bocu_1						                    => "bocu-1",                                       
            Self::Utf_7_Imap						                => "utf-7-imap",                                   
            Self::Iso_8859_1_Windows_3_0_Latin_1	                => "iso-8859-1-windows-3.0-latin-1",               
            Self::Iso_8859_1_Windows_3_1_Latin_1	                => "iso-8859-1-windows-3.1-latin-1",               
            Self::Iso_8859_2_Windows_Latin_2		                => "iso-8859-2-windows-latin-2",                   
            Self::Iso_8859_9_Windows_Latin_5		                => "iso-8859-9-windows-latin-5",                   
            Self::Hp_Roman8						                    => "hp-roman8",                                    
            Self::Adobe_Standard_Encoding			                => "adobe-standard-encoding",                      
            Self::Ventura_Us						                => "ventura-us",                                   
            Self::Ventura_International				                => "ventura-international",                        
            Self::Dec_Mcs						                    => "dec-mcs",                                      
            Self::Ibm850						                    => "ibm850",                                       
            Self::Pc8_Danish_Norwegian				                => "pc8-danish-norwegian",                         
            Self::Ibm862						                    => "ibm862",                                       
            Self::Pc8_Turkish						                => "pc8-turkish",                                  
            Self::Ibm_Symbols						                => "ibm-symbols",                                  
            Self::Ibm_Thai						                    => "ibm-thai",                                     
            Self::Hp_Legal						                    => "hp-legal",                                     
            Self::Hp_Pi_Font						                => "hp-pi-font",                                   
            Self::Hp_Math8						                    => "hp-math8",                                     
            Self::Adobe_Symbol_Encoding				                => "adobe-symbol-encoding",                        
            Self::Hp_Desktop						                => "hp-desktop",                                   
            Self::Ventura_Math						                => "ventura-math",                                 
            Self::Microsoft_Publishing				                => "microsoft-publishing",                         
            Self::Windows_31j						                => "windows-31j",                                  
            Self::Gb2312						                    => "gb2312",                                       
            Self::Big5						                        => "big5",                                         
            Self::Macintosh						                    => "macintosh",                                    
            Self::Ibm037						                    => "ibm037",                                       
            Self::Ibm038						                    => "ibm038",                                       
            Self::Ibm273						                    => "ibm273",                                       
            Self::Ibm274						                    => "ibm274",                                       
            Self::Ibm275						                    => "ibm275",                                       
            Self::Ibm277						                    => "ibm277",                                       
            Self::Ibm278						                    => "ibm278",                                       
            Self::Ibm280						                    => "ibm280",                                       
            Self::Ibm281						                    => "ibm281",                                       
            Self::Ibm284						                    => "ibm284",                                       
            Self::Ibm285						                    => "ibm285",                                       
            Self::Ibm290						                    => "ibm290",                                       
            Self::Ibm297						                    => "ibm297",                                       
            Self::Ibm420						                    => "ibm420",                                       
            Self::Ibm423						                    => "ibm423",                                       
            Self::Ibm424						                    => "ibm424",                                       
            Self::Ibm437						                    => "ibm437",                                       
            Self::Ibm500						                    => "ibm500",                                       
            Self::Ibm851						                    => "ibm851",                                       
            Self::Ibm852						                    => "ibm852",                                       
            Self::Ibm855						                    => "ibm855",                                       
            Self::Ibm857						                    => "ibm857",                                       
            Self::Ibm860						                    => "ibm860",                                       
            Self::Ibm861						                    => "ibm861",                                       
            Self::Ibm863						                    => "ibm863",                                       
            Self::Ibm864						                    => "ibm864",                                       
            Self::Ibm865						                    => "ibm865",                                       
            Self::Ibm868						                    => "ibm868",                                       
            Self::Ibm869						                    => "ibm869",                                       
            Self::Ibm870						                    => "ibm870",                                       
            Self::Ibm871						                    => "ibm871",                                       
            Self::Ibm880						                    => "ibm880",                                       
            Self::Ibm891						                    => "ibm891",                                       
            Self::Ibm903						                    => "ibm903",                                       
            Self::Ibm904						                    => "ibm904",                                       
            Self::Ibm905						                    => "ibm905",                                       
            Self::Ibm918						                    => "ibm918",                                       
            Self::Ibm1026						                    => "ibm1026",                                      
            Self::Ebcdic_At_De					                    => "ebcdic-at-de",                                 
            Self::Ebcdic_At_De_A				                    => "ebcdic-at-de-a",                               
            Self::Ebcdic_Ca_Fr					                    => "ebcdic-ca-fr",                                 
            Self::Ebcdic_Dk_No					                    => "ebcdic-dk-no",                                 
            Self::Ebcdic_Dk_No_A				                    => "ebcdic-dk-no-a",                               
            Self::Ebcdic_Fi_Se					                    => "ebcdic-fi-se",                                 
            Self::Ebcdic_Fi_Se_A				                    => "ebcdic-fi-se-a",                               
            Self::Ebcdic_Fr						                    => "ebcdic-fr",                                    
            Self::Ebcdic_It						                    => "ebcdic-it",                                    
            Self::Ebcdic_Pt						                    => "ebcdic-pt",                                    
            Self::Ebcdic_Es						                    => "ebcdic-es",                                    
            Self::Ebcdic_Es_A					                    => "ebcdic-es-a",                                  
            Self::Ebcdic_Es_S					                    => "ebcdic-es-s",                                  
            Self::Ebcdic_Uk						                    => "ebcdic-uk",                                    
            Self::Ebcdic_Us						                    => "ebcdic-us",                                    
            Self::Unknown_8bit					                    => "unknown-8bit",                                 
            Self::Mnemonic						                    => "mnemonic",                                     
            Self::Mnem						                        => "mnem",                                         
            Self::Viscii						                    => "viscii",                                       
            Self::Viqr						                        => "viqr",                                         
            Self::Koi8_R						                    => "koi8-r",                                       
            Self::Hz_Gb_2312					                    => "hz-gb-2312",                                   
            Self::Ibm866						                    => "ibm866",                                       
            Self::Ibm775						                    => "ibm775",                                       
            Self::Koi8_U						                    => "koi8-u",                                       
            Self::Ibm00858						                    => "ibm00858",                                     
            Self::Ibm00924						                    => "ibm00924",                                     
            Self::Ibm01140						                    => "ibm01140",                                     
            Self::Ibm01141						                    => "ibm01141",                                     
            Self::Ibm01142						                    => "ibm01142",                                     
            Self::Ibm01143						                    => "ibm01143",                                     
            Self::Ibm01144						                    => "ibm01144",                                     
            Self::Ibm01145						                    => "ibm01145",                                     
            Self::Ibm01146						                    => "ibm01146",                                     
            Self::Ibm01147						                    => "ibm01147",                                     
            Self::Ibm01148						                    => "ibm01148",                                     
            Self::Ibm01149						                    => "ibm01149",                                     
            Self::Big5_Hkscs					                    => "big5-hkscs",                                   
            Self::Ibm1047						                    => "ibm1047",                                      
            Self::Ptcp154						                    => "ptcp154",                                      
            Self::Amiga_1251					                    => "amiga-1251",                                   
            Self::Koi7_Switched					                    => "koi7-switched",                                
            Self::Brf						                        => "brf",                                          
            Self::Tscii						                        => "tscii",                                        
            Self::Cp51932						                    => "cp51932",                                      
            Self::Windows_874					                    => "windows-874",                                  
            Self::Windows_1250					                    => "windows-1250",                                 
            Self::Windows_1251					                    => "windows-1251",                                 
            Self::Windows_1252					                    => "windows-1252",                                 
            Self::Windows_1253					                    => "windows-1253",                                 
            Self::Windows_1254					                    => "windows-1254",                                 
            Self::Windows_1255					                    => "windows-1255",                                 
            Self::Windows_1256					                    => "windows-1256",                                 
            Self::Windows_1257					                    => "windows-1257",                                 
            Self::Windows_1258					                    => "windows-1258",                                 
            Self::Tis_620						                    => "tis-620",                       
            Self::Cp50220						                    => "cp50220",     
        })
    }
}

impl FromStr for Charset {
    type Err = Error<ErrTag>;

    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        Ok(match s {
            "us-ascii"                                      => Self::Us_Ascii,
            "iso_8859-1:1987"                               => Self::Iso8859_1_1987,
            "iso_8859-2:1987"                               => Self::Iso8859_2_1987,
            "iso_8859-3:1988"                               => Self::Iso8859_3_1988,
            "iso_8859-4:1988"                               => Self::Iso8859_4_1988,
            "iso_8859-5:1988"                               => Self::Iso8859_5_1988,
            "iso_8859-6:1987"                               => Self::Iso8859_6_1987,
            "iso_8859-7:1987"                               => Self::Iso8859_7_1987,
            "iso_8859-8:1988"                               => Self::Iso8859_8_1988,
            "iso_8859-9:1989"                               => Self::Iso8859_9_1989,
            "iso-8859-10"                                   => Self::Iso8859_10,
            "iso_6937-2-add"                                => Self::Iso6937_2_Add,
            "jis_x0201"                                     => Self::Jis_x0201,
            "jis_encoding"                                  => Self::Jis_encoding,
            "shift_jis"                                     => Self::Shift_jis,
            "extended_unix_code_packed_format_for_japanese"	=> Self::Extended_unix_code_packed_format_for_japanese,
            "extended_unix_code_fixed_width_for_japanese"   => Self::Extended_unix_code_fixed_width_for_japanese,
            "bs_4730"                                       => Self::Bs_4730,
            "sen_850200_c"                                  => Self::Sen_850200_c,
            "it"                                            => Self::It,
            "es"                                            => Self::Es,
            "din_66003"                                     => Self::Din_66003,
            "ns_4551-1"                                     => Self::Ns_4551_1,
            "nf_z_62-010"                                   => Self::Nf_z_62_010,
            "iso-10646-utf-1"                               => Self::Iso_10646_Utf_1,
            "iso_646.basic:1983"                            => Self::Iso_646_Basic_1983,
            "invariant"                                     => Self::Invariant,
            "iso_646.irv:1983"                              => Self::Iso_646_Irv_1983,
            "nats-sefi"                                     => Self::Nats_Sefi,
            "nats-sefi-add"                                 => Self::Nats_Sefi_Add,
            "nats-dano"                                     => Self::Nats_Dano,
            "nats-dano-add"                                 => Self::Nats_Dano_Add,
            "sen_850200_b"                                  => Self::Sen_850200_b,
            "ks_c_5601-1987"                                => Self::Ks_c_5601_1987,
            "iso-2022-kr"                                   => Self::Iso_2022_Kr,
            "euc-kr"                                        => Self::Euc_Kr,
            "iso-2022-jp"                                   => Self::Iso_2022_Jp,
            "iso-2022-jp-2"                                 => Self::Iso_2022_Jp_2,
            "jis_c6220-1969-jp"                             => Self::Jis_c6220_1969_Jp,
            "jis_c6220-1969-ro"                             => Self::Jis_c6220_1969_Ro,
            "pt"                                            => Self::Pt,
            "greek7-old"                                    => Self::Greek7_Old,
            "latin-greek"                                   => Self::Latin_Greek,
            "nf_z_62-010_(1973)"                            => Self::Nf_z_62_010_1973,
            "latin-greek-1"                                 => Self::Latin_Greek_1,
            "iso_5427"                                      => Self::Iso_5427,
            "jis_c6226-1978"                                => Self::Jis_c6226_1978,
            "bs_viewdata"                                   => Self::Bs_viewdata,
            "inis"                                          => Self::Inis,
            "inis-8"                                        => Self::Inis_8,
            "inis-cyrillic"                                 => Self::Inis_Cyrillic,
            "iso_5427:1981"                                 => Self::Iso_5427_1981,
            "iso_5428:1980"                                 => Self::Iso_5428_1980,
            "gb_1988-80"                                    => Self::Gb_1988_80,
            "gb_2312-80"                                    => Self::Gb_2312_80,
            "ns_4551-2"                                     => Self::Ns_4551_2,
            "videotex-suppl"                                => Self::Videotex_Suppl,
            "pt2"                                           => Self::Pt2,
            "es2"                                           => Self::Es2,
            "msz_7795.3"                                    => Self::Msz_7795_3,
            "jis_c6226-1983"                                => Self::Jis_c6226_1983,
            "greek7"                                        => Self::Greek7,
            "asmo_449"                                      => Self::Asmo_449,
            "iso-ir-90"                                     => Self::Iso_Ir_90,
            "jis_c6229-1984-a"                              => Self::Jis_c6229_1984_A,
            "jis_c6229-1984-b"                              => Self::Jis_c6229_1984_B,
            "jis_c6229-1984-b-add"                          => Self::Jis_c6229_1984_B_Add,
            "jis_c6229-1984-hand"                           => Self::Jis_c6229_1984_Hand,
            "jis_c6229-1984-hand-add"                       => Self::Jis_c6229_1984_Hand_Add,
            "jis_c6229-1984-kana"                           => Self::Jis_c6229_1984_Kana,
            "iso_2033-1983"                                 => Self::Iso_2033_1983,
            "ansi_x3.110-1983"                              => Self::Ansi_x3_110_1983,
            "t.61-7bit"                                     => Self::T_61_7bit,
            "t.61-8bit"                                     => Self::T_61_8bit,
            "ecma-cyrillic"                                 => Self::Ecma_Cyrillic,
            "csa_z243.4-1985-1"                             => Self::Csa_z243_4_1985_1,
            "csa_z243.4-1985-2"                             => Self::Csa_z243_4_1985_2,
            "csa_z243.4-1985-gr"                            => Self::Csa_z243_4_1985_Gr,
            "iso_8859-6-e"                                  => Self::Iso_8859_6_E,
            "iso_8859-6-i"                                  => Self::Iso_8859_6_I,
            "t.101-g2"                                      => Self::T_101_G2,
            "iso_8859-8-e"                                  => Self::Iso_8859_8_E,
            "iso_8859-8-i"                                  => Self::Iso_8859_8_I,
            "csn_369103"                                    => Self::Csn_369103,
            "jus_i.b1.002"                                  => Self::Jus_i_B1_002,
            "iec_p27-1"                                     => Self::Iec_p27_1,
            "jus_i.b1.003-serb"                             => Self::Jus_i_B1_003_Serb,
            "jus_i.b1.003-mac"                              => Self::Jus_i_B1_003_Mac,
            "greek-ccitt"                                   => Self::Greek_Ccitt,
            "nc_nc00-10:81"                                 => Self::Nc_nc00_10_81,
            "iso_6937-2-25"                                 => Self::Iso_6937_2_25,
            "gost_19768-74"                                 => Self::Gost_19768_74,
            "iso_8859-supp"                                 => Self::Iso_8859_Supp,
            "iso_10367-box"                                 => Self::Iso_10367_Box,
            "latin-lap"                                     => Self::Latin_Lap,
            "jis_x0212-1990"                                => Self::Jis_x0212_1990,
            "ds_2089"                                       => Self::Ds_2089,
            "us-dk"                                         => Self::Us_Dk,
            "dk-us"                                         => Self::Dk_Us,
            "ksc5636"                                       => Self::Ksc5636,
            "unicode-1-1-utf-7"                             => Self::Unicode_1_1_Utf_7,
            "iso-2022-cn"                                   => Self::Iso_2022_Cn,
            "iso-2022-cn-ext"                               => Self::Iso_2022_Cn_Ext,
            "utf-8"                                         => Self::Utf_8,
            "iso-8859-13"                                   => Self::Iso_8859_13,
            "iso-8859-14"                                   => Self::Iso_8859_14,
            "iso-8859-15"                                   => Self::Iso_8859_15,
            "iso-8859-16"                                   => Self::Iso_8859_16,
            "gbk"                                           => Self::Gbk,
            "gb18030"                                       => Self::Gb18030,
            "osd_ebcdic_df04_15"                            => Self::Osd_ebcdic_df04_15,
            "osd_ebcdic_df03_irv"                           => Self::Osd_ebcdic_df03_irv,
            "osd_ebcdic_df04_1"                             => Self::Osd_ebcdic_df04_1,
            "iso-11548-1"                                   => Self::Iso_11548_1,
            "kz-1048"                                       => Self::Kz_1048,
            "iso-10646-ucs-2"                               => Self::Iso_10646_Ucs_2,
            "iso-10646-ucs-4"                               => Self::Iso_10646_Ucs_4,
            "iso-10646-ucs-basic"                           => Self::Iso_10646_Ucs_Basic,
            "iso-10646-unicode-latin1"                      => Self::Iso_10646_Unicode_Latin1,
            "iso-10646-j-1"                                 => Self::Iso_10646_J_1,
            "iso-unicode-ibm-1261"                          => Self::Iso_Unicode_Ibm_1261,
            "iso-unicode-ibm-1268"                          => Self::Iso_Unicode_Ibm_1268,
            "iso-unicode-ibm-1276"                          => Self::Iso_Unicode_Ibm_1276,
            "iso-unicode-ibm-1264"                          => Self::Iso_Unicode_Ibm_1264,
            "iso-unicode-ibm-1265"                          => Self::Iso_Unicode_Ibm_1265,
            "unicode-1-1"                                   => Self::Unicode_1_1,
            "scsu"                                          => Self::Scsu,
            "utf-7"                                         => Self::Utf_7,
            "utf-16be"                                      => Self::Utf_16be,
            "utf-16le"                                      => Self::Utf_16le,
            "utf-16"                                        => Self::Utf_16,
            "cesu-8"                                        => Self::Cesu_8,
            "utf-32"                                        => Self::Utf_32,
            "utf-32be"                                      => Self::Utf_32be,
            "utf-32le"                                      => Self::Utf_32le,
            "bocu-1"                                        => Self::Bocu_1,
            "utf-7-imap"                                    => Self::Utf_7_Imap,
            "iso-8859-1-windows-3.0-latin-1"                => Self::Iso_8859_1_Windows_3_0_Latin_1,
            "iso-8859-1-windows-3.1-latin-1"                => Self::Iso_8859_1_Windows_3_1_Latin_1,
            "iso-8859-2-windows-latin-2"                    => Self::Iso_8859_2_Windows_Latin_2,
            "iso-8859-9-windows-latin-5"                    => Self::Iso_8859_9_Windows_Latin_5,
            "hp-roman8"                                     => Self::Hp_Roman8,
            "adobe-standard-encoding"                       => Self::Adobe_Standard_Encoding,
            "ventura-us"                                    => Self::Ventura_Us,
            "ventura-international"                         => Self::Ventura_International,
            "dec-mcs"                                       => Self::Dec_Mcs,
            "ibm850"                                        => Self::Ibm850,
            "pc8-danish-norwegian"                          => Self::Pc8_Danish_Norwegian,
            "ibm862"                                        => Self::Ibm862,
            "pc8-turkish"                                   => Self::Pc8_Turkish,
            "ibm-symbols"                                   => Self::Ibm_Symbols,
            "ibm-thai"                                      => Self::Ibm_Thai,
            "hp-legal"                                      => Self::Hp_Legal,
            "hp-pi-font"                                    => Self::Hp_Pi_Font,
            "hp-math8"                                      => Self::Hp_Math8,
            "adobe-symbol-encoding"                         => Self::Adobe_Symbol_Encoding,
            "hp-desktop"                                    => Self::Hp_Desktop,
            "ventura-math"                                  => Self::Ventura_Math,
            "microsoft-publishing"                          => Self::Microsoft_Publishing,
            "windows-31j"                                   => Self::Windows_31j,
            "gb2312"                                        => Self::Gb2312,
            "big5"                                          => Self::Big5,
            "macintosh"                                     => Self::Macintosh,
            "ibm037"                                        => Self::Ibm037,
            "ibm038"                                        => Self::Ibm038,
            "ibm273"                                        => Self::Ibm273,
            "ibm274"                                        => Self::Ibm274,
            "ibm275"                                        => Self::Ibm275,
            "ibm277"                                        => Self::Ibm277,
            "ibm278"                                        => Self::Ibm278,
            "ibm280"                                        => Self::Ibm280,
            "ibm281"                                        => Self::Ibm281,
            "ibm284"                                        => Self::Ibm284,
            "ibm285"                                        => Self::Ibm285,
            "ibm290"                                        => Self::Ibm290,
            "ibm297"                                        => Self::Ibm297,
            "ibm420"                                        => Self::Ibm420,
            "ibm423"                                        => Self::Ibm423,
            "ibm424"                                        => Self::Ibm424,
            "ibm437"                                        => Self::Ibm437,
            "ibm500"                                        => Self::Ibm500,
            "ibm851"                                        => Self::Ibm851,
            "ibm852"                                        => Self::Ibm852,
            "ibm855"                                        => Self::Ibm855,
            "ibm857"                                        => Self::Ibm857,
            "ibm860"                                        => Self::Ibm860,
            "ibm861"                                        => Self::Ibm861,
            "ibm863"                                        => Self::Ibm863,
            "ibm864"                                        => Self::Ibm864,
            "ibm865"                                        => Self::Ibm865,
            "ibm868"                                        => Self::Ibm868,
            "ibm869"                                        => Self::Ibm869,
            "ibm870"                                        => Self::Ibm870,
            "ibm871"                                        => Self::Ibm871,
            "ibm880"                                        => Self::Ibm880,
            "ibm891"                                        => Self::Ibm891,
            "ibm903"                                        => Self::Ibm903,
            "ibm904"                                        => Self::Ibm904,
            "ibm905"                                        => Self::Ibm905,
            "ibm918"                                        => Self::Ibm918,
            "ibm1026"                                       => Self::Ibm1026,
            "ebcdic-at-de"                                  => Self::Ebcdic_At_De,
            "ebcdic-at-de-a"                                => Self::Ebcdic_At_De_A,
            "ebcdic-ca-fr"                                  => Self::Ebcdic_Ca_Fr,
            "ebcdic-dk-no"                                  => Self::Ebcdic_Dk_No,
            "ebcdic-dk-no-a"                                => Self::Ebcdic_Dk_No_A,
            "ebcdic-fi-se"                                  => Self::Ebcdic_Fi_Se,
            "ebcdic-fi-se-a"                                => Self::Ebcdic_Fi_Se_A,
            "ebcdic-fr"                                     => Self::Ebcdic_Fr,
            "ebcdic-it"                                     => Self::Ebcdic_It,
            "ebcdic-pt"                                     => Self::Ebcdic_Pt,
            "ebcdic-es"                                     => Self::Ebcdic_Es,
            "ebcdic-es-a"                                   => Self::Ebcdic_Es_A,
            "ebcdic-es-s"                                   => Self::Ebcdic_Es_S,
            "ebcdic-uk"                                     => Self::Ebcdic_Uk,
            "ebcdic-us"                                     => Self::Ebcdic_Us,
            "unknown-8bit"                                  => Self::Unknown_8bit,
            "mnemonic"                                      => Self::Mnemonic,
            "mnem"                                          => Self::Mnem,
            "viscii"                                        => Self::Viscii,
            "viqr"                                          => Self::Viqr,
            "koi8-r"                                        => Self::Koi8_R,
            "hz-gb-2312"                                    => Self::Hz_Gb_2312,
            "ibm866"                                        => Self::Ibm866,
            "ibm775"                                        => Self::Ibm775,
            "koi8-u"                                        => Self::Koi8_U,
            "ibm00858"                                      => Self::Ibm00858,
            "ibm00924"                                      => Self::Ibm00924,
            "ibm01140"                                      => Self::Ibm01140,
            "ibm01141"                                      => Self::Ibm01141,
            "ibm01142"                                      => Self::Ibm01142,
            "ibm01143"                                      => Self::Ibm01143,
            "ibm01144"                                      => Self::Ibm01144,
            "ibm01145"                                      => Self::Ibm01145,
            "ibm01146"                                      => Self::Ibm01146,
            "ibm01147"                                      => Self::Ibm01147,
            "ibm01148"                                      => Self::Ibm01148,
            "ibm01149"                                      => Self::Ibm01149,
            "big5-hkscs"                                    => Self::Big5_Hkscs,
            "ibm1047"                                       => Self::Ibm1047,
            "ptcp154"                                       => Self::Ptcp154,
            "amiga-1251"                                    => Self::Amiga_1251,
            "koi7-switched"                                 => Self::Koi7_Switched,
            "brf"                                           => Self::Brf,
            "tscii"                                         => Self::Tscii,
            "cp51932"                                       => Self::Cp51932,
            "windows-874"                                   => Self::Windows_874,
            "windows-1250"                                  => Self::Windows_1250,
            "windows-1251"                                  => Self::Windows_1251,
            "windows-1252"                                  => Self::Windows_1252,
            "windows-1253"                                  => Self::Windows_1253,
            "windows-1254"                                  => Self::Windows_1254,
            "windows-1255"                                  => Self::Windows_1255,
            "windows-1256"                                  => Self::Windows_1256,
            "windows-1257"                                  => Self::Windows_1257,
            "windows-1258"                                  => Self::Windows_1258,
            "tis-620"                                       => Self::Tis_620,
            "cp50220"                                       => Self::Cp50220,
            _ => return Err(err!(
                "Unrecognised charset '{}'.", s;
            IO, Network, Unknown, Input)),
        })
    }
}
