/* daimond_debugshare.js -- GENERATED by make_adapter.mjs. Daimond's www/js/debugshare.js as it
 * would stand after adopting fe2o3_net/lens/js/writer.js: its own app layer, cut from its own
 * file by line range, over the extracted writer core in `__lensCore`.
 *
 * It is a classic script, evaluated by Daimond's own test harness exactly as the original is, so
 * the core arrives as a global the preload supplies; in the page it would be an import.
 */
(function () {
	'use strict';
	var L = __lensCore;

	'use strict';

	// ── Keys, endpoint, and the transport caps (mirrored from the handler) ──
	//
	// These four match `gateway/src/handlers/debug_trace.rs` with a margin, so a
	// post is never refused for size and a row is never clipped mid-payload:
	//   MAX_BODY   256 KiB  -> we keep a post under 200 KiB
	//   MAX_ROWS   1000     -> we put at most 400 rows in a post
	//   MAX_DATA   400      -> we keep a base64 slice at 360 bytes
	//   MIN_INTERVAL_MS 2s  -> we drain one post every 3s, ONE clock for every lane
	var ENABLED_KEY = 'daimond-debugshare';		// the flag itself; '1' is on
	var STAMP_KEY   = 'daimond-debugshare-at';	// ms of the last LOCAL decision, for freshest-wins
	var LEDGER_KEY  = 'daimond-ledger';			// the cost ledger, read directly
	var SIGNALS_KEY = 'daimond-signals';		// the per-Diamond / per-model signal index
	var CROSS_KEY   = 'daimond-debug-cross';	// our own diamond×model spend cross (while on)
	var ENDPOINT    = '/api/debug-trace';
	var CLIENT_API  = 2;						// matches CLIENT_API in gateway.js / diag.js

	var MAX_DATA_BYTES = 360;
	var MAX_ROWS_POST  = 400;
	var MAX_BODY_BYTES = 200 * 1024;
	// THE ONE DRAIN INTERVAL, shared by every lane. The gateway floor is 2 s
	// (gateway/src/handlers/debug_trace.rs MIN_INTERVAL_MS); 3 s leaves margin for
	// clock skew between the device and the handler. A device that meets an OLDER
	// gateway -- one still refusing a second post inside ten seconds -- is not
	// special-cased: its 429s double the gap through `gapMs`, so it degrades to
	// the pace that gateway will take instead of spamming it.
	var DRAIN_MS       = 3000;			// the minimum gap between ANY two posts, all lanes

	var TELEMETRY_MS = 30000;					// stream telemetry cadence while on
	var RESNAP_MS    = 300000;					// periodic full re-snapshot (5 min)

	var EVENT_KEY    = 'daimond-debugshare-outbox';	// the durable outbox
	var SEQ_KEY      = 'daimond-debugshare-seq';	// the per-device sequence `n`
	var BUILD_KEY    = 'daimond-build-seen';		// breadcrumb.js's confirmed build id
	var POST_AT_KEY  = 'daimond-debugshare-lastpost';	// the post clock, so a reload keeps it
	var BEAT_TICK_MS = 30000;					// the beat timer's period ...
	var BEAT_TURN_MS = 30000;					// ... a beat this often while a turn runs ...
	var BEAT_IDLE_MS = 300000;					// ... and this often when nothing is running
	// THE SCREEN, ADDED 2026-09-13. Every other event says what the ENGINE did; a
	// phone driven by its own owner has no console to read and no way to be driven
	// from Linux, so the beat/telemetry/console lanes above are silent about the one
	// thing "full visibility" actually needs there: what the person is LOOKING AT.
	// Checked on the SAME clock as the beat (see `beatTick`), so it costs no extra
	// timer, but it posts its own `ev screen` row only when the picture actually
	// CHANGED since the last one -- a device sitting on one screen for an hour must
	// not repeat itself every thirty seconds -- with a floor that ships one anyway
	// every `SCREEN_FLOOR_MS`, so a reader is never more than five minutes stale.
	var SCREEN_FLOOR_MS   = 300000;			// ship one even unchanged, at least this often
	var MAX_VIEW_CHARS    = 24;					// the view/thread kind
	var MAX_SEAT_CHARS    = 60;					// the seat-line text, as rendered
	var MAX_TILE_ROLE_CHARS = 16;				// the last tile's role ("user", "assistant", ...)
	var MAX_TILE_TEXT_CHARS = 80;				// the last tile's text, head only
	var MAX_DLG_CHARS     = 48;					// an open dialog/banner's kind + head
	var MAX_MSG_CHARS = 200;					// an `error` or `console` message, clipped
	var MAX_SRC_CHARS = 60;						// and where it came from
	// A context drop of more than this fraction between two rounds of one turn is
	// read as a fold, because the fold itself happens in Rust and emits nothing a
	// JS caller can see (see `inferFold`). Such an event is marked `inferred:1`.
	var FOLD_DROP = 0.30;
	// A REAL fold (the engine's `compacted` event) within this window suppresses
	// the inferred one, so a fold that IS reported is not also guessed at.
	var FOLD_REAL_MS = 20000;

	// A transcript embeds whole source-file reads and command outputs verbatim, so
	// a snapshot was ~7 MB / 25k chunks and drained for ~12 min, starving telemetry
	// behind it. The one lever is SIZE -- the handler's interval / 400-row / 360-byte
	// caps mean we cannot post faster -- so a giant string is hard-capped to this
	// many bytes with a "[+N bytes]" tail that keeps its size visible. The cap is
	// generous enough to leave an ordinary readable message whole and only bites a
	// giant tool payload. daimond.js has no `TOOL_ELISION_CAP` to reuse, so it
	// lives here. Only the free-form arrays (transcripts, trail, diag) are elided;
	// the structured state stays complete.
	var ELISION_CAP = 2048;

	// Windowing the transcripts, which is a SEPARATE lever from the per-payload
	// elision above. Elision caps each STRING; it does nothing about turn COUNT, and
	// an account with hundreds of turns still shipped every one -- a live trace saw a
	// ~5.7 MB / ~15,900-chunk snapshot drain for ~7 minutes, and the small per-round
	// telemetry the developer actually reads starved behind it. So the snapshot keeps
	// only the MOST RECENT turns: each chat's last `MAX_MSGS_PER_CHAT`, and across all
	// chats a total `TRANSCRIPT_BUDGET_BYTES` spent freshest-first. A row carries 360
	// base64 bytes (= 270 raw), so a ~700 KiB transcript budget plus the small
	// structured state lands the whole snapshot near the ~2,800-row / one-minute
	// target. ONLY the transcript prose is windowed; every structured section (config,
	// roster, presence, election, signals, ledger, tokenStats) and ALL telemetry stay
	// complete and unwindowed -- the live numbers are never cut.
	var MAX_MSGS_PER_CHAT       = 40;			// keep each chat's last N turns
	var TRANSCRIPT_BUDGET_BYTES = 700 * 1024;	// total cap across all chats' kept turns

	// The snapshot no longer ships the whole raw cost ledger. Telemetry carries the
	// per-model / per-Diamond AGGREGATES of it every tick (see aggregateLedger and
	// signalBreakdown), so the raw ~400-entry array was pure duplicated bulk that
	// pushed the snapshot past the one-minute drain target and starved the live
	// numbers behind it. Only the most recent turns are kept, as a tail the operator
	// can spot-check against the aggregates; the count dropped is recorded so the
	// tail is read as a window, not a short ledger.
	var SNAPSHOT_LEDGER_TAIL = 20;				// raw ledger entries kept in a snapshot

	// ── App state. What the writer owns (the outbox, the post clock, the console lane) is gone. ──
	var enabled  = read(ENABLED_KEY) === '1';
	var provider = null;			// registered by daimond.js: () -> (obj | Promise<obj>)
	var statsFn  = null;			// registered by daimond.js: () -> live-stats obj (sync, cheap)
	var screenFn = null;			// registered by daimond.js: () -> {view,seat,role,text,dlg,comp,locked}
	var crossIx  = {};				// diamondId -> model -> {turns, usd}, filled while on
	var telQueue  = [];				// priority lane: telemetry posts, each an array of rows
	var snapQueue = [];				// snapshot lane: drained only when telQueue is empty
	var telTimer = null, snapTimer = null, beatTimer = null;
	var lastBeatAt  = 0;
	var lastScreenAt = 0, lastScreenKey = null;
	var lastCtx     = {};
	var lastRealFold = {};
	var indicator = null;
	var lastLedgerLen = 0, lastTrailLen = 0, lastDiagLen = 0;

	function read(k)  { try { return localStorage.getItem(k); } catch (e) { return null; } }
	function write(k, v) { try { localStorage.setItem(k, v); } catch (e) {} }
	/// The same write, THROWING. `write` swallows, which is right for a flag nobody
	/// misses -- and wrong for the outbox, whose whole point is durability: its quota
	/// fallback was written against a function that cannot fail, so the fallback was
	/// dead code and a full device simply stopped persisting the queue, silently.
	function writeOrThrow(k, v) { localStorage.setItem(k, v); }

	/// A plain positive-millisecond number, or 0. Bignum-safe -- a stamp that
	/// round-tripped through the gateway can arrive as a bignum object with a
	/// `toNumber`, like the presence stamps peer.js reads.
	function ms(v) {
		var n = (v && typeof v.toNumber === 'function') ? v.toNumber() : Number(v);
		return (isFinite(n) && n > 0) ? n : 0;
	}

	/// Best-effort nudge to the sync engine, so a local flip is pushed to the
	/// fleet promptly rather than only on the next debounce. Guarded on the global,
	/// so a build without sync (or a test) pays only a property test.
	function nudgeSync() {
		try { if (window.DaimondSync && window.DaimondSync.nudge) window.DaimondSync.nudge(); }
		catch (e) {}
	}

	// Restore the diamond×model cross from a previous session, so a device that was
	// already sharing keeps its tally across a reload.
	try { crossIx = JSON.parse(read(CROSS_KEY) || '{}') || {}; } catch (e) { crossIx = {}; }
	function saveCross() { try { write(CROSS_KEY, JSON.stringify(crossIx)); } catch (e) {} }

	/// Record one metered turn's spend against its (Diamond, model) pair -- the one
	/// cross the ledger (which carries no Diamond) and the signal index (which holds
	/// Diamond and model separately) cannot answer: which Diamond spent what on
	/// which model. Called from daimond.js's `recordSpend`, and a no-op unless
	/// sharing is on, so an off device pays only a guarded call and a flag test.
	function noteCross(diamondId, model, usd) {
		if (!enabled) return;
		var id = diamondId || '(none)';
		var m  = model || '(unknown)';
		var d  = crossIx[id] || (crossIx[id] = {});
		var r  = d[m] || (d[m] = { turns: 0, usd: 0 });
		r.turns += 1;
		r.usd   += usd || 0;
		saveCross();
	}

	// ── Names, content shapes and the redactor: the core's, with Daimond's two parameters. ──
	var SCRUB = L.createScrubber({
		// The gateway's own session cookie. It is HttpOnly, so this app cannot read it, but a server
		// log line pasted into a chat is not bound by that.
		pairs:  [{ k: 'cookie', g: 2, re: /(daimond_gw_sess=)([^;,\s"'\[\]]{4,})/g }],
		// `body` is the archive's own snapshot FILENAME, which the entropy catch used to take.
		idKeys: { holder: 1, self: 1, nominated: 1, body: 1 },
	});
	var REDACT = L.createRedactor();
	var REDACT_CONFIG = L.createRedactor({ loose: true });
	function scrubText(s, isId) { return SCRUB.text(s, isId); }
	function scrubDeep(o) { return SCRUB.deep(o); }
	function redact(o) { return REDACT.value(o); }
	function redactConfig(o) { return REDACT_CONFIG.value(o); }
	function fingerprint(v) { return L.fingerprint(v); }
	function byteLen(s) { return L.byteLen(s); }
	function str(o) { return JSON.stringify(o); }

	/// A deep copy of `obj` with every string past `ELISION_CAP` bytes hard-capped
	/// to its first `ELISION_CAP` characters plus a `…[+N bytes]` tail naming how
	/// many bytes were dropped -- so the size stays visible and a giant file-read or
	/// command output no longer bloats the bundle, while an ordinary readable
	/// message (under the cap) passes through whole. Structure-preserving, so the
	/// operator still sees the shape of a transcript; cycle-safe and depth-bounded,
	/// like `redact()`, since the state it walks is arbitrary.
	function elide(obj, seen, depth) {
		seen = seen || [];
		depth = depth || 0;
		if (typeof obj === 'string') {
			var bytes = byteLen(obj);
			if (bytes <= ELISION_CAP) return obj;
			// A string ABOUT TO BE CUT is scrubbed first, for the same reason `clip`
			// does it: the 2 KiB boundary falls wherever it falls, and a key
			// straddling it would reach the egress seam as a prefix too short for
			// any rule to know. Only here, and not on every string: one that passes
			// through whole is scrubbed at the seam anyway, and a transcript is
			// thousands of strings the walk would otherwise search twice.
			obj = scrubText(obj);
			bytes = byteLen(obj);
			if (bytes <= ELISION_CAP) return obj;
			// Tool payloads are overwhelmingly ASCII, so a character slice at the cap
			// is at or under the byte cap; the tail reports the exact bytes dropped.
			var head = obj.slice(0, ELISION_CAP);
			return head + '…[+' + (bytes - byteLen(head)) + ' bytes]';
		}
		if (obj == null || typeof obj !== 'object') return obj;
		if (depth > 40 || seen.indexOf(obj) !== -1) return '[elided:cycle-or-deep]';
		seen = seen.concat([obj]);
		if (Array.isArray(obj)) {
			return obj.map(function (v) { return elide(v, seen, depth + 1); });
		}
		var out = {};
		Object.keys(obj).forEach(function (k) { out[k] = elide(obj[k], seen, depth + 1); });
		return out;
	}

	/// The JSON byte length of one message, for the windowing budget. Never throws --
	/// a message that will not serialise counts as zero, so it can never stall the walk.
	function msgBytes(m) {
		try { return byteLen(JSON.stringify(m) || ''); } catch (e) { return 0; }
	}

	/// Window transcripts down to a bounded, RECENT slice, so a snapshot of an account
	/// with hundreds of turns drains in about a minute instead of starving the live
	/// telemetry behind it. Two bounds, both keeping the NEWEST turns: each chat keeps
	/// only its last `MAX_MSGS_PER_CHAT` messages (a transcript is append-only, so the
	/// tail is the most recent turns), and across chats -- freshest `updatedAt` first --
	/// messages are kept, newest of each chat first, until the running total reaches
	/// `TRANSCRIPT_BUDGET_BYTES`, after which a chat keeps none. Each windowed chat
	/// carries `droppedOlderTurns`, the count of messages cut, so the operator reads it
	/// as a window rather than a short chat. Only the `messages` array is touched; every
	/// other chat field is preserved. Returns a NEW array and does not mutate the input;
	/// a non-array (e.g. `null`) is returned unchanged. Budget is measured on the RAW
	/// message, before `elide` shrinks any giant payload, so the wire never exceeds it.
	function windowTranscripts(chats) {
		if (!Array.isArray(chats)) return chats;
		// Freshest chats first, so the byte budget is spent on the most recent
		// conversations; a stable tiebreak keeps equal/absent stamps in original order.
		var order = chats.map(function (c, i) { return { c: c, i: i }; });
		order.sort(function (a, b) {
			var au = ms(a.c && a.c.updatedAt), bu = ms(b.c && b.c.updatedAt);
			return (au !== bu) ? (bu - au) : (a.i - b.i);
		});
		var budget = TRANSCRIPT_BUDGET_BYTES;
		var byIndex = {};
		order.forEach(function (entry) {
			var c = entry.c || {};
			var msgs = Array.isArray(c.messages) ? c.messages : [];
			var total = msgs.length;
			// Per-chat tail cap first: at most the last N turns of THIS chat.
			var tail = total > MAX_MSGS_PER_CHAT ? msgs.slice(total - MAX_MSGS_PER_CHAT) : msgs.slice();
			// Then the cross-chat byte budget, still keeping the newest and dropping the
			// oldest: walk the tail newest-first and stop when the next (older) turn will
			// not fit, so a budget already spent by fresher chats leaves this one empty.
			var out = [];
			for (var j = tail.length - 1; j >= 0; j--) {
				var b = msgBytes(tail[j]);
				if (budget - b < 0) break;
				budget -= b;
				out.unshift(tail[j]);
			}
			var rec = {};
			Object.keys(c).forEach(function (k) { if (k !== 'messages') rec[k] = c[k]; });
			rec.messages = out;
			var dropped = total - out.length;
			if (dropped > 0) rec.droppedOlderTurns = dropped;
			byIndex[entry.i] = rec;
		});
		// Restore the input's original order.
		return chats.map(function (c, i) { return byIndex[i]; });
	}
	// ── Assembling a bundle ──────────────────────────────────────

	/// The always-safe sources this module reads on its own, off public globals:
	/// the cost ledger, the error/console trail, and the diagnostics ring. The
	/// decrypted transcripts, roster, presence, election, config and token stats
	/// come from the registered provider (daimond.js), which alone can see them.
	function publicSources() {
		var ledger = [];
		try { ledger = JSON.parse(read(LEDGER_KEY) || '[]'); } catch (e) { ledger = []; }
		var trail = [];
		try { trail = (window.DaimondTrail && DaimondTrail.rows && DaimondTrail.rows()) || []; } catch (e) {}
		var diag = [];
		try { diag = (window.DaimondDiag && DaimondDiag.rows && DaimondDiag.rows()) || []; } catch (e) {}
		// The per-Diamond / per-model signal index -- turns, spend and misses. Small
		// and structured, so it travels whole and drives the live breakdowns.
		var signals = null;
		try { signals = JSON.parse(read(SIGNALS_KEY) || 'null'); } catch (e) { signals = null; }
		return { ledger: ledger, trail: trail, diag: diag, signals: signals };
	}

	/// Assemble a full snapshot from a `sources` object and the provider's state.
	/// Exposed for tests as `_assemble`. Redacts the whole result before returning,
	/// so no caller can ever hold an un-redacted bundle.
	function assemble(sources, state) {
		sources = sources || {};
		state = state || {};
		// The raw cost ledger is NOT shipped whole any more: telemetry's per-model and
		// per-Diamond aggregates already summarise it every tick, so a full ~400-entry
		// copy in the snapshot was duplicated bulk that delayed the drain. Keep only the
		// most recent tail for a spot-check, and record how many older entries were cut.
		var fullLedger = sources.ledger || [];
		var ledgerTail = fullLedger.length > SNAPSHOT_LEDGER_TAIL
			? fullLedger.slice(fullLedger.length - SNAPSHOT_LEDGER_TAIL)
			: fullLedger;
		var raw = {
			v:          1,
			kind:       'snapshot',
			ts:         Date.now(),
			iso:        new Date().toISOString(),
			// From the provider (daimond.js) -- the decrypted, private-scope state.
			// Only `transcripts` carries the giant verbatim tool outputs and the deep
			// turn history, so it alone is WINDOWED (recent turns only, see
			// windowTranscripts) and then elided; the rest is small, structured and
			// travels COMPLETE.
			config:      redactConfig(state.config || null),
			transcripts: elide(windowTranscripts(state.transcripts || null)),
			roster:      state.roster || null,
			presence:    state.presence || null,
			election:    state.election || null,
			tokenStats:  state.tokenStats || null,
			// From this module's own public reads. The signal index is structured
			// and complete; trail and diag are free-form logs, so their rows are
			// elided against a stray giant string while their shape is kept. The
			// ledger is a recent tail only -- telemetry carries its aggregates.
			signals:       sources.signals || null,
			ledger:        ledgerTail,
			ledgerDropped: fullLedger.length - ledgerTail.length,
			trail:         elide(sources.trail || []),
			diag:          elide(sources.diag || []),
		};
		// Redact after eliding, so a secret-named field is a fingerprint regardless
		// of what elision left of it. `config` was already run through
		// `redactConfig` above, with the looser camelCase-aware match -- so put it
		// back unchanged afterwards, or this general pass would redact an already-
		// redacted `apiKey` a second time and turn its fingerprint into a
		// fingerprint of a fingerprint.
		var out = redact(raw);
		out.config = raw.config;
		return out;
	}

	/// Gather the full decrypted state: the provider's output plus this module's
	/// public reads, assembled and redacted. Async because the provider may load
	/// transcripts from IndexedDB.
	function gatherSnapshot() {
		return Promise.resolve(provider ? provider() : null).then(function (state) {
			return assemble(publicSources(), state || {});
		}, function () {
			// A provider that throws must not stop the safe sources going out.
			return assemble(publicSources(), {});
		});
	}

	/// Fold the whole cost ledger into one row per model -- the discriminator the
	/// developer reads every tick. `ledger` is the raw array this module reads off
	/// `daimond-ledger`, entries shaped `{t,m,p,c,ca,u,r,e}`: `p` prompt tokens
	/// (cumulative per turn), `c` completion, `ca` cached, `u` USD, `r` set when
	/// the provider reported the cost. `cachedPct` is cache hit-rate on the prompt,
	/// `maxPromptTurn` the largest single-turn prompt, `reportedPct` how much of the
	/// spend the provider priced rather than this client guessing.
	function aggregateLedger(ledger) {
		var by = {};	// model id → accumulator
		for (var i = 0; i < ledger.length; i++) {
			var e = ledger[i];
			if (!e) continue;
			var m = e.m || '';
			if (!by[m]) by[m] = { model: m, turns: 0, prompt: 0, completion: 0,
				cached: 0, usd: 0, maxPromptTurn: 0, reported: 0 };
			var a = by[m];
			a.turns      += 1;
			a.prompt     += e.p || 0;
			a.completion += e.c || 0;
			a.cached     += e.ca || 0;
			a.usd        += e.u || 0;
			if ((e.p || 0) > a.maxPromptTurn) a.maxPromptTurn = e.p || 0;
			if (e.r) a.reported += 1;
		}
		return Object.keys(by).map(function (m) {
			var a = by[m];
			return {
				model:         a.model,
				turns:         a.turns,
				prompt:        a.prompt,
				completion:    a.completion,
				cached:        a.cached,
				cachedPct:     a.prompt ? 100 * a.cached / a.prompt : 0,
				usd:           a.usd,
				maxPromptTurn: a.maxPromptTurn,
				reportedPct:   a.turns ? 100 * a.reported / a.turns : 0,
			};
		});
	}

	/// The per-Diamond and per-model breakdowns from the signal index -- turns,
	/// spend and misses each. `ix.diamonds` answers "which Diamond spent what" over
	/// all history; `ix.models` answers "which model cost what". Both are small
	/// maps, so they go every tick. Returns empty arrays when there is no index.
	function signalBreakdown(signals) {
		var out = { diamonds: [], models: [] };
		if (!signals || typeof signals !== 'object') return out;
		var d = signals.diamonds || {};
		Object.keys(d).forEach(function (id) {
			var r = d[id] || {};
			out.diamonds.push({ diamondId: id, turns: r.turns || 0, usd: r.usd || 0, missed: r.missed || 0 });
		});
		var m = signals.models || {};
		Object.keys(m).forEach(function (model) {
			var r = m[model] || {};
			out.models.push({ model: model, turns: r.turns || 0, usd: r.usd || 0, missed: r.missed || 0 });
		});
		return out;
	}

	/// The diamond×model cross this module has accumulated while sharing was on --
	/// `[{diamondId, model, turns, usd}]`, dearest first -- so the operator reads
	/// which Diamond spent what on which model. Empty until turns are recorded.
	function crossBreakdown() {
		var out = [];
		Object.keys(crossIx).forEach(function (id) {
			var byModel = crossIx[id] || {};
			Object.keys(byModel).forEach(function (model) {
				var r = byModel[model] || {};
				out.push({ diamondId: id, model: model, turns: r.turns || 0, usd: r.usd || 0 });
			});
		});
		out.sort(function (a, b) { return b.usd - a.usd; });
		return out;
	}

	/// The live numbers from daimond.js's stats seam, or null when none is
	/// registered or it throws. Sync and cheap by contract -- no transcripts.
	function liveStats() {
		if (!statsFn) return null;
		try {
			var v = statsFn();
			return (v && typeof v === 'object') ? v : null;
		} catch (e) { return null; }
	}

	/// A lightweight telemetry object, sent EVERY tick: the ledger/trail/diag rows
	/// that are new since the last tick, plus a `stats` block -- per-model ledger
	/// aggregation and the live context/worker numbers -- that goes every time so
	/// the developer sees the figures that matter even on a quiet tick. No
	/// transcripts. Redacted like everything else. Returns null only when there is
	/// genuinely nothing to say (no new rows and no stats seam).
	function gatherTelemetry() {
		var s = publicSources();
		var ledDelta  = s.ledger.slice(lastLedgerLen);
		var trailNew  = s.trail.slice(lastTrailLen);
		var diagNew   = s.diag.slice(lastDiagLen);
		var sig = signalBreakdown(s.signals);
		var stats = {
			models:       aggregateLedger(s.ledger),	// per-model, from the cost ledger
			diamonds:     sig.diamonds,					// per-Diamond, from the signal index
			signalModels: sig.models,					// per-model, from the signal index
			cross:        crossBreakdown(),				// diamond×model, accumulated while on
			live:         liveStats(),					// context/worker, from the stats seam
		};
		if (!ledDelta.length && !trailNew.length && !diagNew.length && !stats) return null;
		lastLedgerLen = s.ledger.length;
		lastTrailLen  = s.trail.length;
		lastDiagLen   = s.diag.length;
		return redact({
			v:      1,
			kind:   'telemetry',
			ts:     Date.now(),
			iso:    new Date().toISOString(),
			ledger: ledDelta,
			trail:  trailNew,
			diag:   diagNew,
			stats:  stats,
		});
	}

	// ── Chunking a bundle into debug-trace rows ──────────────────

	/// UTF-8-safe base64 of a string (the JSON survives the handler's control-char
	/// scrub and byte-boundary clip intact, which raw JSON would not guarantee).
	function b64(str) {
		try {
			var bytes = new TextEncoder().encode(str);
			var bin = '';
			for (var i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
			return btoa(bin);
		} catch (e) {
			try { return btoa(unescape(encodeURIComponent(str))); } catch (e2) { return ''; }
		}
	}

	/// Split an assembled bundle into an array of POSTS (each an array of rows the
	/// `/api/debug-trace` handler accepts). A snapshot's rows are tagged
	/// `ds <kind> <id> i/N` so the operator reassembles by concatenating `data` in
	/// order and base64-decoding. Exposed for tests as `_chunk`.
	function chunk(bundle) {
		var json = '';
		// THE EGRESS SEAM, half one. Nothing reaches the wire as a `ds` row except
		// through here, so this is where the content rules meet a whole bundle --
		// after which it is base64, and no later pass could read it.
		try { json = JSON.stringify(scrubDeep(bundle)); }
		catch (e) { json = '{"error":"stringify"}'; }
		var payload = b64(json);
		var id = (bundle && bundle.kind === 'telemetry' ? 't' : 's')
			+ Date.now().toString(36) + Math.random().toString(36).slice(2, 5);
		var slices = [];
		for (var i = 0; i < payload.length; i += MAX_DATA_BYTES) {
			slices.push(payload.slice(i, i + MAX_DATA_BYTES));
		}
		if (!slices.length) slices.push('');
		var n = slices.length;
		var kind = (bundle && bundle.kind) || 'snapshot';
		var rows = slices.map(function (data, idx) {
			return {
				ts:  Date.now(),
				tag: 'ds ' + kind + ' ' + id + ' ' + (idx + 1) + '/' + n,
				data: data,
			};
		});
		// Group rows into posts under both the row cap and the body cap.
		var posts = [];
		var cur = [], curBytes = 0;
		rows.forEach(function (r) {
			var rowBytes = r.tag.length + r.data.length + 48;	// JSON overhead per row
			if (cur.length >= MAX_ROWS_POST || (curBytes + rowBytes) > MAX_BODY_BYTES) {
				if (cur.length) posts.push(cur);
				cur = []; curBytes = 0;
			}
			cur.push(r); curBytes += rowBytes;
		});
		if (cur.length) posts.push(cur);
		return posts;
	}

	/// THE THREE CAPABILITY FACTS a stuck device cannot otherwise be seen to be
	/// missing: whether the tool surface exists at all, whether a workspace folder
	/// is actually mounted, and whether this device may commit a chunk set. The
	/// third is the one that matters most -- a device whose chunk index has not
	/// merged refuses every commit, silently, and that state was invisible until
	/// it cost a turn. `null` means the answer is not knowable yet (the core has
	/// not loaded), which is a different thing from `false`.
	function capabilities() {
		var cap = { tools: false, folder: false, mayCommit: null };
		try { cap.tools = !!window.DaimondTools; } catch (e) {}
		try { cap.folder = !!(window.DaimondFiles && DaimondFiles.folder && DaimondFiles.folder()); } catch (e) {}
		try {
			if (window.DaimondCore && DaimondCore.syncMayCommitChunks) {
				cap.mayCommit = !!DaimondCore.syncMayCommitChunks();
			}
		} catch (e) { /* the core is not up; `null` stands */ }
		return cap;
	}

	/// A FOLD HAPPENS IN RUST and the JS side is told only when the engine emits
	/// `compacted`; a fold the engine performs silently shows up here as nothing
	/// but a context that got smaller. So a round whose `ctx` has dropped by more
	/// than `FOLD_DROP` against the previous round of the same turn is reported as
	/// a fold and MARKED `inferred:1`, which is the honest label for a fact that
	/// was deduced rather than observed. A real fold reported within
	/// `FOLD_REAL_MS` suppresses the guess, so the two never double up.
	function inferFold(p) {
		if (!p || typeof p !== 'object') return;
		var id = String(p.turn || p.chat || '');
		var ctx = Number(p.ctx) || 0;
		if (!id || ctx <= 0) return;
		var was = lastCtx[id] || 0;
		lastCtx[id] = ctx;
		if (was <= 0 || ctx >= was * (1 - FOLD_DROP)) return;
		var real = lastRealFold[id] || 0;
		if (real && (Date.now() - real) < FOLD_REAL_MS) return;
		W.event('fold', { turn: id, before: was, after: ctx, trigger: 'est', inferred: 1 });
	}

	/// Record that the engine reported a REAL fold for this turn, so the inference
	/// above stands down. Called beside the `fold` event in daimond.js.
	function noteRealFold(id) {
		try {
			if (!id) return;
			lastRealFold[String(id)] = Date.now();
			lastCtx[String(id)] = 0;			// the next round re-seeds the baseline
		} catch (e) { W.fault(e); }
	}

	// ── The beat ───────────────────────────────────────────────

	/// Where this device is, on a clock rather than on an event: build (in the
	/// envelope), context against the window and the fold point, worker state,
	/// credits when the gateway has said, and how deep the outbox is. Every 30 s
	/// while a turn runs, every 5 min when nothing does -- one timer, with the
	/// due time decided here, so a turn starting mid-interval is picked up within
	/// one tick rather than after five minutes.
	function beatTick() {
		if (!enabled || !W.ok()) return;
		var busy = false;
		try { busy = !!(window.DaimondCore && DaimondCore.busy && DaimondCore.busy()); } catch (e) {}
		var now = Date.now();
		var due = busy ? BEAT_TURN_MS : BEAT_IDLE_MS;
		if (lastBeatAt && (now - lastBeatAt) < (due - 500)) return;
		lastBeatAt = now;
		// Nothing held for dedupe should outlive a beat: a line logged once and
		// never repeated would otherwise wait out its whole minute.
		W.flushConsole(now, true);
		var live = liveStats() || {};
		var wk = live.workerState || null;
		var credits = null;
		try {
			var gs = (window.DaimondGateway && DaimondGateway.state) ? DaimondGateway.state() : null;
			if (gs && typeof gs.credits === 'number') credits = gs.credits;
		} catch (e) { /* the gateway has not answered */ }
		event('beat', {
			ctx:   live.contextActual || 0,
			win:   live.contextWindow || 0,
			fold:  live.foldAt || 0,
			model: clip(live.activeModel || '', 48),
			wk:    wk ? (wk.active | 0) : 0,
			wq:    wk ? (wk.queued | 0) : 0,
			busy:  busy ? 1 : 0,
			cr:    (credits == null) ? undefined : credits,
			ob:    W.depth(),
			// FEED HEALTH, which nothing else reports: how often the gateway has
			// refused a post for rate (429), how often one failed for any other
			// reason, and how many console lines the cap dropped since the last
			// beat. A steady state that shows any of these is a bug in the pacing,
			// which is exactly what these numbers are here to make visible.
			throttled: W.health().throttled,
			postFail:  W.health().postFail,
			cdrop:     W.takeConsoleDropped(),
		});
		screenTick();
	}

	function deviceId() {
		try { return (window.DaimondIdentity && DaimondIdentity.deviceId && DaimondIdentity.deviceId()) || ''; }
		catch (e) { return ''; }
	}

	// ── The writer core, handed Daimond's seams ──
	function buildRaw() {
		try {
			if (window.DaimondUpdater && DaimondUpdater.booted && DaimondUpdater.booted()) return DaimondUpdater.booted();
		} catch (e) { /* the updater has not polled */ }
		return read(BUILD_KEY) || '';
	}
	var W = L.createWriter({
		host:    { storage: localStorage, setTimeout: setTimeout, clearTimeout: clearTimeout, console: console,
		           now: function () { return Date.now(); }, document: typeof document !== 'undefined' ? document : null,
		           // Read at call time, so the test that swaps the tab's Error for one with no stack is seen.
		           get Error() { return Error; } },
		keys:    { outbox: EVENT_KEY, seq: SEQ_KEY, postAt: POST_AT_KEY },
		device:  deviceId,
		build:   buildRaw,
		enabled: function () { return enabled; },
		send:    function (rows) {
			return fetch(ENDPOINT, {
				method:      'POST',
				credentials: 'same-origin',
				headers:     { 'content-type': 'application/json', 'x-daimond-api': String(CLIENT_API) },
				body:        W.postBody(rows),
			});
		},
		redact:  REDACT,
		scrub:   SCRUB,
		extra:   function (kind) {
			if (kind !== 'boot' && kind !== 'beat') return null;
			var cap = capabilities();
			return { tools: cap.tools, folder: cap.folder, mayCommit: cap.mayCommit };
		},
		lane:    {
			pending: function () { return telQueue.length > 0 || snapQueue.length > 0; },
			next:    function () { return telQueue.length ? telQueue.shift() : snapQueue.shift(); },
		},
		ownPath:    ENDPOINT,
		skipFrames: ['debugshare.js'],
		after:   function (kind, payload) { if (kind === 'round') inferFold(payload); },
		onFault: function () { stopTimers(); },
		caps:    { gapMs: DRAIN_MS },
	});
	function clip(s, n) { return W.clip(s, n); }
	function event(kind, payload) { return W.event(kind, payload); }
	function fault(e) { W.fault(e); }
	function noteFetchFail(p, s, l, e) { return W.noteFetchFail(p, s, l, e); }
	function persistNow() { W.persistNow(); }
	function noteError(m, w) { W.noteError(m, w); }
	function noteConsole(lvl, args) { W.noteConsole(lvl, args); }
	function flushConsole(t, force) { W.flushConsole(t, force); }
	function looksSecret(m) { return L.looksSecret(m); }
	function gapLeft() { return W.gapLeft(); }
	function fit(o) { return W.fit(o); }
	function eventBatch() { return W.eventBatch(); }

	/// Enqueue a bundle's posts onto the telemetry lane when `priority` is true, else
	/// the snapshot lane, and kick the drainer. A no-op when off.
	function enqueue(posts, priority) {
		if (!enabled || !posts || !posts.length) return;
		var q = priority ? telQueue : snapQueue;
		for (var i = 0; i < posts.length; i++) q.push(posts[i]);
		W.drain();
	}

	/// Assemble and enqueue a full snapshot. A no-op when off, or once the feed
	/// has faulted -- a feed that threw collects nothing more this session.
	function snapshotNow() {
		if (!enabled || !W.ok()) return Promise.resolve(false);
		return gatherSnapshot().then(function (bundle) {
			enqueue(chunk(bundle));
			return true;
		});
	}

	function telemetryTick() {
		if (!enabled || !W.ok()) return;
		var tel = gatherTelemetry();
		if (tel) enqueue(chunk(tel), true);		// priority lane -- ahead of any snapshot backlog
	}

	// ── The header indicator ─────────────────────────────────────
	//
	// A red, gently pulsing eye in the header's action group, shown the whole time
	// the feature is on and gone the instant it is off. Its title/hover carries the
	// plain warning. Theme-aware: the alert red is deliberately close in both
	// themes (an alarm should not go quiet in the dark), but the glyph and ring
	// adjust so it reads on either ground.

	var INDICATOR_TITLE = 'Debug data sharing is ON — all your Daimond data is being '
		+ 'shared with the developer for debugging. Turn off in Settings.';

	function ensureStyle() {
		try {
			if (document.getElementById('ds-style')) return;
			var s = document.createElement('style');
			s.id = 'ds-style';
			s.textContent =
				'.ds-indicator{display:inline-flex;align-items:center;justify-content:center;'
				+ 'width:34px;height:34px;margin:0 2px;border-radius:8px;cursor:pointer;'
				+ 'border:1px solid #ef4444;background:#fee2e2;color:#b91c1c;'
				+ 'animation:ds-pulse 1.6s ease-in-out infinite;}'
				+ '.ds-indicator:hover{background:#fecaca;}'
				+ '.ds-indicator .ic{width:20px;height:20px;stroke:currentColor;stroke-width:2;'
				+ 'fill:none;stroke-linecap:round;stroke-linejoin:round;}'
				+ '@keyframes ds-pulse{0%,100%{box-shadow:0 0 0 0 rgba(239,68,68,.55);}'
				+ '50%{box-shadow:0 0 0 5px rgba(239,68,68,0);}}'
				+ '@media (prefers-color-scheme:dark){'
				+ '.ds-indicator{background:#450a0a;color:#fca5a5;border-color:#f87171;}'
				+ '.ds-indicator:hover{background:#5b1010;}}'
				+ ':root[data-theme="dark"] .ds-indicator{background:#450a0a;color:#fca5a5;border-color:#f87171;}'
				+ ':root[data-theme="light"] .ds-indicator{background:#fee2e2;color:#b91c1c;border-color:#ef4444;}';
			(document.head || document.body || document.documentElement).appendChild(s);
		} catch (e) {}
	}

	function mountIndicator() {
		try {
			if (indicator || typeof document === 'undefined' || !document.querySelector) return;
			ensureStyle();
			var host = document.querySelector('.top-actions') || document.querySelector('.topbar');
			if (!host) return;
			var b = document.createElement('button');
			b.type = 'button';
			b.className = 'ds-indicator';
			b.id = 'ds-indicator';
			b.title = INDICATOR_TITLE;
			b.setAttribute('aria-label', INDICATOR_TITLE);
			// An eye with a dot -- "your data is being watched" -- in an alert frame.
			b.innerHTML = '<svg class="ic" viewBox="0 0 24 24" aria-hidden="true">'
				+ '<path d="M1.5 12S5 5.5 12 5.5 22.5 12 22.5 12 19 18.5 12 18.5 1.5 12 1.5 12z"/>'
				+ '<circle cx="12" cy="12" r="3"/></svg>';
			b.addEventListener('click', function () {
				// Best-effort nudge toward Settings; harmless if nobody listens.
				try { window.dispatchEvent(new CustomEvent('daimond:opensettings', { detail: { from: 'debugshare' } })); }
				catch (e) {}
			});
			// First child, so it sits at the leading edge of the action group and is
			// the first thing the eye meets.
			if (host.firstChild) host.insertBefore(b, host.firstChild);
			else host.appendChild(b);
			indicator = b;
		} catch (e) {}
	}

	function unmountIndicator() {
		try { if (indicator && indicator.remove) indicator.remove(); } catch (e) {}
		indicator = null;
	}

	// ── The switch ───────────────────────────────────────────────

	function startTimers() {
		stopTimers();
		if (!W.ok()) return;			// a faulted feed collects nothing more
		try { telTimer  = setInterval(telemetryTick, TELEMETRY_MS); } catch (e) {}
		try { snapTimer = setInterval(function () { snapshotNow(); }, RESNAP_MS); } catch (e) {}
		try { beatTimer = setInterval(function () { try { beatTick(); } catch (e2) { fault(e2); } }, BEAT_TICK_MS); } catch (e) {}
	}
	function stopTimers() {
		try { if (telTimer) clearInterval(telTimer); } catch (e) {}
		try { if (snapTimer) clearInterval(snapTimer); } catch (e) {}
		try { if (beatTimer) clearInterval(beatTimer); } catch (e) {}
		telTimer = null; snapTimer = null; beatTimer = null;
	}

	function isOn() { return enabled; }

	/// Apply the on/off EFFECT without recording a decision or nudging sync. On:
	/// show the indicator, start the timers, and post a full snapshot. Off: hide the
	/// indicator, stop the timers, drop any queued posts, and reset the telemetry
	/// cursors -- nothing more leaves the device. Idempotent and safe to call before
	/// the DOM exists (the indicator is simply not mounted then, and mounts on the
	/// next `on`). This is the shared body: `setEnabled` wraps it with a fresh stamp
	/// for a LOCAL decision, and `adoptSync` calls it after writing the remote stamp
	/// verbatim, so an adopted value never restamps and cannot ping-pong.
	function applyState(v) {
		enabled = !!v;
		write(ENABLED_KEY, enabled ? '1' : '0');
		try {
			window.dispatchEvent(new CustomEvent('daimond:debugshare', { detail: { on: enabled } }));
		} catch (e) {}
		if (enabled) {
			mountIndicator();
			// Seed the telemetry cursors at the current tail, so the first telemetry
			// tick sends only what happens AFTER toggle-on (the snapshot already
			// carried the backlog).
			var s = publicSources();
			lastLedgerLen = s.ledger.length;
			lastTrailLen  = s.trail.length;
			lastDiagLen   = s.diag.length;
			startTimers();
			snapshotNow();
			// NO IMMEDIATE BEAT. The snapshot that has just been queued carries the
			// same state and more, and `boot` -- emitted by daimond.js at start and
			// unlock -- is what says which build this device is on. The beat's job is
			// the CLOCK: it says a quiet device is still there. So the first one is
			// the timer's, not this.
			lastBeatAt = 0;
			lastScreenAt = 0;
			lastScreenKey = null;
		} else {
			stopTimers();
			telQueue = [];
			snapQueue = [];
			// The outbox, and what the console lane held, go with it: see `W.reset`.
			W.reset();
			unmountIndicator();
		}
	}

	/// Turn the feature on or off from a LOCAL action (the Settings toggle). Stamps
	/// the decision with the clock -- which is how this choice wins over an older one
	/// on every linked device (see `adoptSync`) -- applies the effect, and nudges the
	/// sync engine so the flag reaches the fleet without waiting for the next push.
	function setEnabled(v) {
		var on = !!v;
		// Stamp BEFORE applying, so a snapshot the effect kicks off already carries the
		// new decision when `collectSync` reads `syncSnapshot()`. Past the stamp it
		// replaces, so turning it off on a device whose clock is behind the one that
		// turned it on still wins (CLK-3).
		write(STAMP_KEY, String(DaimondStamp.next(ms(read(STAMP_KEY)))));
		applyState(on);
		nudgeSync();
	}

	/// The flag as it rides the sync parcel: `{ on, at }`, or `null` when this device
	/// has never touched the toggle. Verbatim -- no restamp -- so a value this device
	/// already agrees with serialises to the same bytes and the push-skip still holds.
	/// `null` (never touched) reads to the other side as "nothing to say", so a fresh
	/// device cannot clear a fleet another device has just armed.
	function syncSnapshot() {
		var at = ms(read(STAMP_KEY));
		if (!at) return null;
		return { on: enabled, at: at };
	}

	/// Adopt a flag that arrived from another device: the fresher `at` wins, and at an
	/// equal `at` OFF wins, on every device alike, so a tie never leaves collection
	/// running anywhere. Written VERBATIM, so a record this device already holds moves
	/// nothing and the next parcel is byte-identical. When the fresher value differs from what this
	/// device shows, the effect is applied through `applyState` -- the indicator mounts
	/// or unmounts and collection starts or stops -- so the eye and the collection match
	/// the fleet. Only the boolean and its stamp are touched; no key or secret is read
	/// or written here.
	function adoptSync(rec) {
		if (!rec || typeof rec !== 'object') return;
		var at = ms(rec.at);
		if (!at) return;
		var on = !!rec.on;
		var mineAt = ms(read(STAMP_KEY));
		if (DaimondStamp.beats(at, on, mineAt, enabled, offFirst)) {
			write(STAMP_KEY, String(at));		// verbatim: no restamp, so no ping-pong
			if (on !== enabled) applyState(on);
		}
	}

	/// The flag's rank for a tie: off above on.
	function offFirst(on) { return on ? 0 : 1; }

	/// Register the provider daimond.js supplies: a function returning (or
	/// resolving to) the decrypted private-scope state. Called once at boot.
	function registerProvider(fn) {
		if (typeof fn === 'function') provider = fn;
	}

	/// Register the live-stats seam daimond.js supplies: a cheap, synchronous
	/// function returning the current context/token/worker numbers (never
	/// transcripts). Telemetry calls it every tick. Called once at boot, beside
	/// `registerProvider`.
	function registerStats(fn) {
		if (typeof fn === 'function') statsFn = fn;
	}

	/// Register the screen seam daimond.js supplies: a cheap, synchronous function
	/// returning what the person is actually LOOKING AT -- which view, the seat
	/// line, the last tile's role and text head, an open dialog's kind, the
	/// composer's length and the lock state. Called once at boot, beside the two
	/// seams above; the fields this module cannot know on its own (window size,
	/// tab visibility, the updater's state) are added in `gatherScreen`.
	function registerScreen(fn) {
		if (typeof fn === 'function') screenFn = fn;
	}

	/// The updater's state, in the one word a reader needs: `'none'` (nothing
	/// pending), `'countdown'` (an automatic reload is due), `'manual'` or
	/// `'manual:<why>'` (the watch has given up finding a safe moment, or a
	/// controlling worker will not advance -- only a manual reload will move this
	/// device; `<why>` is the LAST reason it was refused, when one was ever
	/// recorded, see `heldWhy` in updater.js), `'held:<why>'` (a build is pending
	/// but a named guard is holding the automatic path back right now -- see
	/// `updater.js`'s `whyUnsafe`), or `'ready'` (safe and quiet, waiting only on
	/// the next tick). `window.DaimondUpdater` absent -- an older build, or a
	/// test -- reads as `'none'`.
	///
	/// `manual` used to say nothing more, even once `heldWhy` had a reason on
	/// file -- `gaveUp`/`stuck` short-circuited the `held` check below and the
	/// lens saw a device stuck on manual with no way to tell why. Same reason
	/// word either way now, since it is the SAME question -- what is stopping
	/// this build -- read at a different moment.
	function updaterState() {
		try {
			var U = window.DaimondUpdater;
			if (!U || !(U.pending && U.pending())) return 'none';
			if (U.countdown && U.countdown() > 0) return 'countdown';
			if ((U.stuck && U.stuck()) || (U.gaveUp && U.gaveUp())) {
				var manualWhy = (U.held && U.held()) || '';
				return manualWhy ? 'manual:' + manualWhy : 'manual';
			}
			if (U.held) { var why = U.held(); if (why) return 'held:' + why; }
			return 'ready';
		} catch (e) { return 'none'; }
	}

	/// The screen picture, assembled from the registered seam plus the three
	/// facts only this module can see: the viewport size, whether the tab is
	/// visible, and the updater's own state. Every string is bounded here, so
	/// `screenTick`'s change-detection compares an already-capped object and
	/// `fit()` in `emit` is a safety net rather than the only thing keeping this
	/// under the 360-byte cap. Never throws: a screen seam that is absent, or
	/// that itself throws, yields the fields this module can still answer.
	function gatherScreen() {
		var s = null;
		try { s = screenFn ? screenFn() : null; } catch (e) { s = null; }
		s = (s && typeof s === 'object') ? s : {};
		var role = clip(s.role || '', MAX_TILE_ROLE_CHARS);
		var text = clip(s.text || '', MAX_TILE_TEXT_CHARS);
		// One string, "role: text", which is what a reader wants on one line; an
		// absent tile (a fresh chat, or no seam registered) is the empty string,
		// not "': '".
		var tile = text ? (role ? role + ': ' + text : text) : '';
		var w = 0, h = 0, vis = '';
		try { w = (window.innerWidth  | 0) || 0; } catch (e) { /* no window */ }
		try { h = (window.innerHeight | 0) || 0; } catch (e) { /* no window */ }
		try { vis = (typeof document !== 'undefined' && document.visibilityState) || ''; }
		catch (e) { /* no document */ }
		return {
			view:   clip(s.view || '', MAX_VIEW_CHARS) || 'chat',
			seat:   clip(s.seat || '', MAX_SEAT_CHARS),
			tile:   tile,
			dlg:    clip(s.dlg || 'none', MAX_DLG_CHARS) || 'none',
			comp:   Number(s.comp) || 0,
			locked: s.locked ? 1 : 0,
			upd:    updaterState(),
			w:      w,
			h:      h,
			vis:    vis,
		};
	}

	/// Gather the screen and ship it as an `ev screen` row -- but only when its
	/// picture has actually CHANGED since the last one shipped, or `SCREEN_FLOOR_MS`
	/// has passed since it last did, whichever comes first. Called from `beatTick`,
	/// so it is checked on the same clock as the beat (30 s busy, 5 min idle) without
	/// a timer of its own; most ticks say nothing at all, which is the point -- a
	/// device sitting on one screen must not repeat itself every thirty seconds.
	function screenTick() {
		if (!enabled || !W.ok()) return;
		var s = gatherScreen();
		var key = '';
		try { key = str(s); } catch (e) { key = ''; }
		var now = Date.now();
		if (key === lastScreenKey && lastScreenAt && (now - lastScreenAt) < SCREEN_FLOOR_MS) return;
		lastScreenKey = key;
		lastScreenAt  = now;
		event('screen', s);
	}

	// If the switch was left on from a previous session, restore the indicator and
	// resume collection once the DOM is ready.
	function bootRestore() {
		if (!enabled) return;
		mountIndicator();
		var s = publicSources();
		lastLedgerLen = s.ledger.length;
		lastTrailLen  = s.trail.length;
		lastDiagLen   = s.diag.length;
		startTimers();
		// A boot snapshot lands the current state the moment the app is up.
		snapshotNow();
		// And whatever the LAST session could not deliver goes now, ahead of it: the
		// outbox is already loaded, and this is the moment it starts moving again.
		lastBeatAt = 0;
		W.drain();
	}
	try {
		if (typeof document !== 'undefined' && document.addEventListener) {
			if (document.readyState === 'loading') {
				document.addEventListener('DOMContentLoaded', bootRestore);
			} else {
				// Defer a tick so daimond.js has a chance to register its provider.
				setTimeout(bootRestore, 0);
			}
		}
	} catch (e) {}

	// A switch flipped in one tab reaches the others of the SAME device, so turning
	// it off in one place stops collection everywhere on this machine. The sibling
	// tab that flipped it already stamped `STAMP_KEY` and nudged sync, so this one
	// only mirrors the EFFECT -- `applyState`, never `setEnabled` -- and does not
	// restamp. (Cross-DEVICE propagation is `syncSnapshot`/`adoptSync` on the parcel.)
	try {
		window.addEventListener('storage', function (e) {
			if (e && e.key === ENABLED_KEY) {
				var now = read(ENABLED_KEY) === '1';
				if (now !== enabled) applyState(now);
			}
		});
	} catch (e) {}

	// ── Capture: errors, the console, and the page going away. All three are the core's. ──
	W.captureErrors(window);
	W.captureConsole(typeof console !== 'undefined' ? console : null);
	W.captureLifecycle(window, typeof document !== 'undefined' ? document : undefined);

	window.DEBUG_SHARE = {
		isOn:             isOn,
		setEnabled:       setEnabled,
		// Cross-device flag sync, ridden on the existing parcel by daimond.js
		// (`collectSync` reads `syncSnapshot`, `applySync` calls `adoptSync`).
		syncSnapshot:     syncSnapshot,
		adoptSync:        adoptSync,
		registerProvider: registerProvider,
		registerStats:    registerStats,
		registerScreen:   registerScreen,
		noteCross:        noteCross,
		snapshotNow:      snapshotNow,
		// THE EVENT SEAM. One call, `DEBUG_SHARE.event(kind, payload)`, from every
		// call site in the app; a no-op when sharing is off and never a throw into
		// the caller. `noteFetchFail` is the gateway wrapper's shorthand for the
		// `fetch.fail` kind, and `noteRealFold` tells the fold inference to stand
		// down because the engine reported a fold itself.
		event:            event,
		noteFetchFail:    noteFetchFail,
		noteRealFold:     noteRealFold,
		/// Is the feed still collecting? False once it has faulted, even while the
		/// share switch is on -- see `fault`.
		feedOk:           function () { return !!W.ok(); },
		/// How many events are waiting to go out.
		outboxDepth:      function () { return W.depth(); },
		// Exposed for the verifier: drive one telemetry tick without the 30 s timer.
		_telemetryTick:   telemetryTick,
		// Exposed for the verifier (www/js/debugshare.test.mjs):
		_fingerprint: fingerprint,
		_redact:      redact,
		// The content scrubber -- the shared block's two entry points.
		_scrubText:   scrubText,
		_scrubDeep:   scrubDeep,
		_elide:       elide,
		_windowTranscripts: windowTranscripts,
		_byteLen:     byteLen,
		_assemble:    assemble,
		_chunk:       chunk,
		_publicSources: publicSources,
		_gatherSnapshot: gatherSnapshot,
		_gatherTelemetry: gatherTelemetry,
		_aggregateLedger: aggregateLedger,
		_signalBreakdown: signalBreakdown,
		_crossBreakdown:  crossBreakdown,
		_queueLen:    function () { return telQueue.length + snapQueue.length; },
		// Exposed for the verifier: the event lane, its persistence, and the two
		// timed collectors, so the outage/reload/fault rules can be driven without
		// waiting out an interval.
		_outbox:      function () { return W.outbox(); },
		_persistNow:  persistNow,
		_beatTick:    beatTick,
		_capabilities: capabilities,
		_gatherScreen: gatherScreen,
		_screenTick:   screenTick,
		_updaterState: updaterState,
		// Simulate the five-minute floor having elapsed, without a real wait: the
		// change-detection compares against `lastScreenAt`, and this is the one
		// thing a test cannot otherwise move.
		_expireScreen: function () { lastScreenAt = 0; },
		_noteError:   noteError,
		// The console lane, driven without waiting out a dedupe window.
		_noteConsole: function (lvl, args) { noteConsole(lvl, args || []); },
		_flushConsole: function (force) { flushConsole(Date.now(), force !== false); },
		_looksSecret: looksSecret,
		/// What the last beat would report: the 429s, the other post failures, and
		/// the console lines the cap dropped.
		_health:      function () { return W.health(); },
		// Exposed for the verifier: whether a post may go NOW, per the clock this
		// instance booted with -- the property a reload used to lose.
		_gapLeft:     gapLeft,
		_fit:         fit,
		_eventBatch:  eventBatch,
		_backoffMs:   function (n) { return W.backoffMs(n); },
		_drain:       function () { return W.drain(); },
		// Exposed for the verifier so it can assert lane ordering directly.
		_telQueueLen:  function () { return telQueue.length; },
		_snapQueueLen: function () { return snapQueue.length; },
	};
})();
