/* lens_daimond.mjs -- GENERATED by make_lens_adapter.mjs. Daimond's dev/lens.mjs as it would
 * stand after adopting fe2o3_net/lens/js/reader.mjs: its own views over the extracted reader core.
 * Run Daimond's test against it with
 *   LENS_UNDER_TEST=<this file> node <daimond>/dev/lens.test.mjs
 */
// lens.mjs — the reader half of Daimond's full-visibility feed.
//
// USAGE
//
//   node dev/lens.mjs pull     [--no-rsync]                  fetch + archive (idempotent)
//   node dev/lens.mjs status   [--device D] [--since today]    one block per device
//   node dev/lens.mjs turns    [--since 24h] [--device D]     one line per turn
//   node dev/lens.mjs errors   [--since 1h] [--grep RE]       deduplicated, worst first
//   node dev/lens.mjs console  [--since 1h] [--lvl warn|all]   what the tab printed
//   node dev/lens.mjs events   [--kind K] [--since 1h] [--grep RE]
//   node dev/lens.mjs snapshot [--latest|--id ID] [--device D] [--out FILE]
//   node dev/lens.mjs watch    [--since 5m] [--once] [--no-pull]
//   node dev/lens.mjs digest                                  <= 2 KB, for /pickup
//
//   Common: --json (machine form), --limit N, --since 30s|5m|2h|7d|today|<ISO>,
//           --device (an id prefix, OR a roster name substring: "argonaut",
//           "gilgamesh", "iOS" -- whatever this archive has ever called it).
//           Every device is printed as its id BESIDE that name, because the id
//           alone is how two sessions in one day mis-assigned a7b34e2
//           (gilgamesh) as argonaut (96a1474 is the real argonaut).
//
// `console` is the browser console as the device saw it -- every level, one row
// per distinct line with `x` saying how many times it repeated inside its minute.
// It defaults to warn and error, because that is what a reader is looking for;
// `--lvl all` adds log, info and debug. The same warn/error lines also join
// `errors`, so a question asked there does not have to be asked twice.
//
// `errors` HIDES ABORTED REQUESTS by default. A reload kills every call in
// flight and each arrives as a status 0 that means nothing was wrong; the client
// marks those `aborted`, and a status 0 within five seconds of the same device's
// next `boot` is read the same way even when it did not -- an unannounced reload
// (the updater's own, a crash-and-restart, iOS re-instantiating a backgrounded
// tab) kills the same calls with nothing set. `--aborted` shows them.
//
// A `fetch.fail` GROUPS BY PATH AND STATUS, not by its flattened message. Every
// other kind dedupes on a message with the digits turned into `N`, which read
// `/api/sync 409`, `413` and `502` as one line with a count -- three faults with
// three remedies, reported as one.
//
// WHERE THE DATA LIVES
//
//   jarrah:~/usr/daimond-gateway/debug-traces/   the gateway's own files, rotated
//                                                at 2 MB with only two kept
//   ~/.cache/daimond-lens/traces/                the rsync mirror
//   ~/.cache/daimond-lens/archive/               the durable archive (NDJSON)
//   ~/.cache/daimond-lens/state.json             what has been ingested
//
// Rotation on jarrah destroys a device's third-oldest file, so `pull` runs on a
// five-minute timer (dev/lens-pull.timer) and appends only what it has not seen.
// The archive is the authority for every question; nothing re-reads jarrah.
//
// THE ON-THE-WIRE FORMAT (gateway/src/handlers/debug_trace.rs, render_block)
//
//   ===== <recv ms> account=<a> device=<d> rows=<n> =====
//     <client ms>  <tag>  <data>
//
// Tag and data are separated by the FIRST double space, because a tag may hold
// single spaces (`ds telemetry <id> 3/12`, `election peer`) and data may hold
// double ones. Three row families matter:
//
//   ds telemetry <id> i/N   base64 JSON chunk of a per-tick telemetry bundle
//   ds snapshot  <id> i/N   base64 JSON chunk of a periodic full snapshot
//   ev <kind>               one JSON event, envelope {v,d,n,b,t,...}
//
// `ev console` is one of those kinds and needs no special ingestion: it is filed
// like every other event, on the same `(d,n)` dedupe. Its payload is
// `{lvl, msg, src, x}` -- level, the message clipped to 200 characters, the
// `file:line` it came from where the client could sample a stack, and the repeat
// count inside its dedupe window.
//
// `ev` rows do not exist in the logs yet — the client half is a parallel lane —
// so every question prefers them and falls back to what telemetry already
// carries: the raw ledger delta (one entry per TURN, `{t,m,p,c,ca,u,r,e}`), the
// per-model RUNNING TOTALS (`stats.models`, differenced tick to tick where the
// ledger delta was lost), the live context/worker numbers (`stats.live`), the
// breadcrumb trail (`{t,a,w,d}`) and the diagnostics ring (`{ts,a,tag,data}`).
//
// COVERAGE IS STATED, NOT ASSUMED, AND IT IS NOT ONE NUMBER. jarrah keeps two
// 2 MB files per device, so whatever rotated away before the first pull is gone
// for good — and each device's record starts at a different moment, from a
// different source. An election trace from three days ago is coverage for
// `events` and none at all for a turn or a cost, so the header quotes the
// earliest TELEMETRY tick (or `ev` event) and names the row coverage separately
// only when it differs. Every device line carries its own first tick, and a
// device whose record starts after the window says so in place of a count. A
// zero over a window the archive cannot see is not a quiet day.
//
// OUTPUT SIZE IS THE BUDGET. `status` and `digest` are read by a language model
// at every pickup, so they are capped (40 lines / 2 KB) and the cap is enforced
// here rather than trusted to the caller. A change that grows them is a
// regression, not a feature.

import { execFileSync }	from 'node:child_process';
import fs			from 'node:fs';
import os			from 'node:os';
import path			from 'node:path';

// ── Where everything lives ───────────────────────────────────────────

const HOME	= process.env.DAIMOND_LENS_HOME
	|| path.join(os.homedir(), '.cache', 'daimond-lens');
// Set (even to empty) by the verifier, which has no jarrah and no network; an
// `||` default would read an empty string as unset and try to reach the host.
const REMOTE	= process.env.DAIMOND_LENS_REMOTE !== undefined
	? process.env.DAIMOND_LENS_REMOTE
	: 'jarrah:~/usr/daimond-gateway/debug-traces/';
const TRACES	= path.join(HOME, 'traces');
const ARCHIVE	= path.join(HOME, 'archive');
const SNAPS	= path.join(ARCHIVE, 'snapshots');
const PENDING	= path.join(HOME, 'pending');
const STATEF	= path.join(HOME, 'state.json');

// A block whose receive time is more than this behind the newest one seen for
// that device cannot be new: the gateway appends in receive order and we read
// `.log.1` before `.log`. Inside the window we consult an exact key set, so two
// blocks sharing a millisecond are still told apart.
const RECENT_MS		= 10 * 60 * 1000;
// A chunk set that has not gained a part in this long will never complete --
// the missing rows were rotated away on jarrah before a pull reached them.
const PENDING_TTL_MS	= 6 * 60 * 60 * 1000;
const STATUS_MAX_LINES	= 40;
const DIGEST_MAX_BYTES	= 2048;
// How close a status 0 has to sit in front of a device's next boot to be read as
// a request the reload took rather than a gateway that failed. Generous enough to
// cover a tab that takes its time coming up, short enough that an ordinary
// network failure minutes before an unrelated reload is still a fault.
const RELOAD_GRACE_MS	= 5000;

// ── The core's reader, handed Daimond's seams ────────────────────────
import { createRedactor, createScrubber } from '../../redact.js';
import {
	ago, covLabel, createReader, dev7, emit, ensureDir, idsMatch, num, parseArgs, rangeAdd, rangeCount,
	rangeHas, rangeMissing, readJson, readNdjson, safeName, sinceLabel, sinceMs, utcLabel, windowLabel, writeJson, hm,
} from '../../reader.mjs';

const R = createReader({
	home:    HOME,
	mirror:  'traces',
	pull:    REMOTE ? [['rsync', '-az', REMOTE, TRACES + '/']] : null,
	// The gateway's own session cookie, and the fields whose values are ids this reader navigates by.
	scrub:   createScrubber({
		pairs:  [{ k: 'cookie', g: 2, re: /(daimond_gw_sess=)([^;,\s"'\[\]]{4,})/g }],
		idKeys: { holder: 1, self: 1, nominated: 1, body: 1 },
	}),
	prepare: (b) => { if (b.config) b.config = createRedactor({ loose: true }).value(b.config); return b; },
	tick:    (b) => ({ iso: b.iso || null, stats: b.stats || null, ledger: b.ledger || [], trail: b.trail || [], diag: b.diag || [] }),
	index:   (b) => summariseSnapshot(b),
	nameFor: (d) => nameFor(d),
	recentMs: RECENT_MS, pendingTtlMs: PENDING_TTL_MS,
});
const { appendLine, archiveDevices, coverage, eventsFile, loadEvents, loadSnapshotIndex, loadState, loadTelemetry,
	pendingSets, snapBodyFile, snapIndexFile, telFile, wantDevice } = R;


// ── Arguments ────────────────────────────────────────────────────────


const ARGS	= parseArgs(process.argv.slice(2));
const JSONOUT	= !!ARGS.bool.json;


// ── Small file helpers ───────────────────────────────────────────────






// ── Integer range sets ───────────────────────────────────────────────
//
// Chunk indices and event sequence numbers both arrive almost in order with
// occasional redelivery, so a list of [lo,hi] ranges collapses to one or two
// entries and keeps state.json small where a plain set of every number seen
// would reach megabytes within a day.





// ── Parsing a trace file ─────────────────────────────────────────────




// ── State ────────────────────────────────────────────────────────────






// ── Ingest ───────────────────────────────────────────────────────────



/// The shortest form of a roster entry's `name` a reader still recognises: the
/// word after " on " (`"Chrome on argonaut"` -> `argonaut`, `"Safari on iOS"` ->
/// `iOS`), which is the machine or platform a reader actually asks about --
/// two sessions today read the bare id instead and mis-assigned a7b34e2 to
/// argonaut when it was gilgamesh. Falls back to the whole name where there is
/// no " on " to split on.
function shortRosterName(name) {
	const s = String(name || '').trim();
	const m = /\bon\s+(\S+)\s*$/i.exec(s);
	return (m ? m[1] : s).replace(/[.,;]+$/, '');
}

/// The handful of facts `status` and `digest` read out of a snapshot, so the
/// body file stays closed for every ordinary question.
function summariseSnapshot(bundle) {
	const out = { builds: {}, names: {}, chats: 0, roster: 0 };
	const reg = bundle && bundle.roster;
	if (reg && typeof reg === 'object') {
		for (const id of Object.keys(reg)) {
			const r = reg[id] || {};
			out.roster++;
			if (r.build) out.builds[id] = String(r.build).slice(0, 32);
			if (r.name) out.names[id] = shortRosterName(r.name);
		}
	}
	if (Array.isArray(bundle && bundle.tokenStats)) out.chats = bundle.tokenStats.length;
	if (bundle && bundle.election && bundle.election.self) out.self = String(bundle.election.self);
	return out;
}





function cmdPull(args) {
	const stat = R.pull({ noPull: !!args.bool['no-rsync'] });
	stat.rsync = stat.pull;
	if (JSONOUT) { console.log(JSON.stringify(stat)); return 0; }
	console.log(`pull: rsync ${stat.rsync}; ${stat.blocks} new block(s), ${stat.skipped} seen`);
	console.log(`  rows ${stat.rows}  events ${stat.events} (+${stat.dupEvents} dup)`
		+ `  chunks ${stat.chunks} (+${stat.dupChunks} dup)`);
	console.log(`  telemetry sets ${stat.telemetry}  snapshots ${stat.snapshots}`
		+ `  gapped ${stat.gapped}  broken ${stat.broken}`);
	return 0;
}

// ── Reading the archive ──────────────────────────────────────────────










// ── The derived model ────────────────────────────────────────────────
//
// Every question is answered from `ev` rows where they exist and from telemetry
// where they do not. The two paths produce the same record shapes, so the
// commands below never branch on which half of the feed is shipped.

/// One record per TURN, from whichever of three sources can see it. Each record
/// carries a `turns` COUNT, because the third source can only say how many turns
/// an interval held, not what each one did.
///
///   `ev`         an `ev turn.end` event — everything known, one turn.
///   `ledger`     a cost-ledger entry — one turn, with its own tokens and USD
///                (`p` and `ca` are that turn's cumulative prompt and cached
///                tokens, `u` its USD, `r` set when the provider priced it).
///   `cumulative` the difference between two ticks of `stats.models[]`, which is
///                a running total per model and survives the loss of the ledger
///                deltas that rotation eats. It knows the count, the spend and
///                the tokens for an interval, and nothing about outcome.
///
/// The third is used only where the first two are silent for that device, that
/// model and that interval, so a turn is never counted twice.
///
/// `turn.end`'s `out` and `ended`'s `how` are two different vocabularies for the
/// same question (daimond.js, two call sites, two histories) -- `cap` against
/// `round_limit`. Collapsed to one here so a reader never has to know both.
function normalizeOutcome(w) {
	return w === 'cap' ? 'round_limit' : w;
}

function turnRecords(filter, since) {
	const out = [];
	// Loaded ONCE and reused below for the `turn.end`, `ended` and `round`/`fold`
	// passes -- previously three separate reads of the same NDJSON. Still
	// unbounded (`0`, not `since`): a marathon daimon turn can straddle the
	// window, and its early `round`s must still reach `maxPromptByTurn` even
	// when the turn itself closes inside `since`. Only the RETURNED rows are
	// filtered to the window, at the very end, as before.
	const events = loadEvents(filter, 0);
	// `turn.end`'s own fields, short for the 360-byte cap (daimond.js `dsEvent('turn.end', …)`):
	// `p`/`c`/`ca` prompt/completion/cached, `usd`, `r` rounds, `out` outcome. The long names
	// (`prompt`/`rounds`/`outcome`/…) are read too, so a fixture or a future caller using either
	// shape still works -- but the short ones are what the app actually sends. Collected rather
	// than pushed straight to `out`, so the ledger join below can match against them first.
	const endedTurns = new Set();		// turn ids already covered by a `turn.end` row
	const turnEndRows = [];
	for (const e of events) {
		if (e.src !== 'ev' || e.kind !== 'turn.end') continue;
		const p = e.ev || {};
		if (p.turn) endedTurns.add(String(p.turn));
		turnEndRows.push({
			ts: e.ts, device: e.device, model: p.model || p.m || '?', turns: 1,
			turn: p.turn || null,
			rounds: p.rounds ?? p.r ?? null, prompt: p.prompt ?? p.p ?? 0,
			completion: p.completion ?? p.c ?? 0,
			cached: p.cached ?? p.ca ?? 0, usd: p.usd ?? p.cost ?? 0,
			// `prov`, short like `turn.start`'s own field -- absent on a build before
			// this fix, so a `?` model there is what says the id join still has to
			// borrow the ledger's.
			provider: p.provider || p.prov || '',
			outcome: normalizeOutcome(p.outcome || p.out || 'done'), reported: !!p.reported, src: 'ev',
		});
	}
	// A daimon turn (`round`/`fold`/`tool` with no chat-shaped close) still ends with
	// its OWN `turn.end` -- the 2026-09-13 archive confirms it for a7b34e2 (gilgamesh) --
	// so this only ever fires for a turn id that genuinely named no `turn.end` at all.
	// Tokens/spend are left unknown (`null`) rather than guessed, since neither the
	// ledger nor the cumulative totals below are keyed by turn id.
	for (const e of events) {
		if (e.src !== 'ev' || e.kind !== 'ended') continue;
		const p = e.ev || {};
		if (p.turn && endedTurns.has(String(p.turn))) continue;
		out.push({
			ts: e.ts, device: e.device, model: '?', turns: 1, turn: p.turn || null,
			rounds: p.rounds ?? null, prompt: null, completion: null, cached: null, usd: null,
			outcome: p.how || 'done', reported: false, src: 'ended',
		});
		if (p.turn) endedTurns.add(String(p.turn));
	}
	// Per-round tells, joined onto turns by `turn` id: the HIGHEST per-round
	// `last_prompt_tokens` the turn reached (the figure that actually tracks
	// prompt-carry across a marathon turn's rounds) and how many times it
	// folded. Both are throttled at the source -- a `round` only every 5th
	// round, plus the one it ended on -- so `maxPrompt` can miss a spike
	// between samples; it is still the best count an unthrottled re-read
	// would give for the same budget of events.
	const maxPromptByTurn = new Map(), foldsByTurn = new Map();
	// The LAST `round_meta`/`stalled` seen for a turn: the provider's own trace facts for
	// whichever round they were most recently true of. Proposal 15, 2026-09-15 -- a round
	// that answered nothing had no id, no `finish_reason` and no upstream provider name
	// anywhere this tool could read, so a stall or a cut could not be traced back to the
	// provider afterwards. Last rather than first: the round that mattered is the one the
	// turn actually ended on.
	const lastRoundByTurn = new Map();
	for (const e of events) {
		if (e.src !== 'ev') continue;
		const p = e.ev || {};
		if (!p.turn) continue;
		const key = String(p.turn);
		if (e.kind === 'round') {
			const ctx = Number(p.ctx) || 0;
			if (ctx > (maxPromptByTurn.get(key) || 0)) maxPromptByTurn.set(key, ctx);
		} else if (e.kind === 'fold') {
			foldsByTurn.set(key, (foldsByTurn.get(key) || 0) + 1);
		} else if (e.kind === 'round_meta' || e.kind === 'stalled') {
			lastRoundByTurn.set(key, {
				r: p.r ?? null, gen: p.gen || '', finish: p.finish || '',
				nfinish: p.nfinish || '', provider: p.provider || '',
				stalled: e.kind === 'stalled',
			});
		}
	}
	// The ledger delta is resent whole after a reload (the client's high-water
	// mark is per page life), so the same turn arrives on many ticks. It also
	// SYNCS TO EVERY DEVICE -- the same account-wide ledger, held in full by each
	// device's own telemetry snapshot -- so keying the dedupe by `t.device` as
	// well as the entry's own fingerprint made one turn into one row PER DEVICE
	// it happened to sync to: "24h $28.39 / 23 turns" read as ~6 turns, ~$7. The
	// entry's own (t, m, p) already names the turn; the device that happened to
	// report it first is not part of what makes it unique.
	const led = new Set();
	const ledgerRows = [];
	for (const t of loadTelemetry(filter, 0)) {
		for (const e of (t.ledger || [])) {
			if (!e || typeof e !== 'object') continue;
			const key = e.t + '|' + (e.m || '') + '|' + (e.p || 0);
			if (led.has(key)) continue;
			led.add(key);
			ledgerRows.push({
				ts: e.t || t.ts, device: t.device, model: e.m || '?', turns: 1,
				rounds: null, prompt: e.p || 0, completion: e.c || 0, cached: e.ca || 0,
				usd: e.u || 0, outcome: e.e ? 'error' : 'done', reported: !!e.r,
				provider: e.pv || '', src: 'ledger',
				// The turn id, when this entry was written by a build that stamps one
				// (`www/js/ledger.js` `record()`'s `tid`). Absent on every entry written
				// before that build, and on the few paths (a whole-chat fold) that spend
				// against no single turn at all.
				tid: e.tid ? String(e.tid) : null,
			});
		}
	}
	// A daimon turn posts BOTH the ledger tick and its own `turn.end` -- the same
	// turn under two channels, which is why a `turns`/`status` total once counted
	// its spend twice (`glm-5.3 r- rep $0.87` alongside `? r24 est $0.87`, summing
	// $1.74). The two used to be joined by device + a five-second clock skew +
	// equal prompt tokens, which is a GUESS: the ledger SYNCS TO EVERY DEVICE (see
	// above), so `lr.device` can be whichever device's telemetry copy happened to
	// carry the entry, not the device that ran the turn -- and the owner saw the
	// same turn twice, once correctly and once as `? r33 … est` on a device that
	// never ran it. Fixed by joining on the turn's OWN identity first: `turn.end`
	// has always carried `p.turn`, and the ledger entry now carries the same id as
	// `tid` (`www/js/ledger.js` `record()`, threaded through `recordSpend` from
	// the chat and daimon-steer call sites). An id match is authoritative --
	// the merged row takes `turn.end`'s device (the one that actually ran it),
	// turn id, rounds, model and provider outright, keeping only the ledger's
	// price and `reported` flag, which `turn.end` does not carry.
	const teByTid = new Map();
	for (const te of turnEndRows) if (te.turn) teByTid.set(String(te.turn), te);
	const usedTurnEnd = new Set(), idMatchedLedger = new Set();
	for (const lr of ledgerRows) {
		if (!lr.tid) continue;
		const te = teByTid.get(lr.tid);
		if (!te || usedTurnEnd.has(te)) continue;
		usedTurnEnd.add(te);
		idMatchedLedger.add(lr);
		out.push(Object.assign({}, lr, {
			device:   te.device,
			turn:     te.turn,
			rounds:   te.rounds,
			model:    te.model && te.model !== '?' ? te.model : lr.model,
			provider: te.provider || lr.provider,
			outcome:  te.outcome || lr.outcome,
		}));
	}
	// The old heuristic survives ONLY for a ledger entry with no `tid` -- one
	// written before this build. It is a guess, so a row it produces is marked
	// `est` even where the ledger itself said a provider billed it (`r`): an
	// unproven join must not borrow the confidence a proven one earned. A
	// ledger entry that DOES carry a `tid` but matched no `turn.end` (the event
	// was lost to rotation, say) is never handed to this guess -- it stands on
	// its own rather than risk pairing with an unrelated turn.
	for (const lr of ledgerRows) {
		if (idMatchedLedger.has(lr)) continue;			// already pushed, above
		if (lr.tid) { out.push(lr); continue; }		// has an id; not a guessing candidate
		let match = null;
		for (const te of turnEndRows) {
			if (usedTurnEnd.has(te)) continue;
			if (te.device !== lr.device) continue;
			if (Math.abs((te.ts || 0) - (lr.ts || 0)) >= 5000) continue;
			if ((te.prompt || 0) !== (lr.prompt || 0)) continue;
			match = te;
			break;
		}
		if (match) {
			usedTurnEnd.add(match);
			out.push(Object.assign({}, lr, { turn: match.turn, rounds: match.rounds, reported: false }));
		} else {
			out.push(lr);
		}
	}
	for (const te of turnEndRows) if (!usedTurnEnd.has(te)) out.push(te);
	for (const r of out) {
		if (!r.turn) continue;
		const key = String(r.turn);
		r.maxPrompt = maxPromptByTurn.has(key) ? maxPromptByTurn.get(key) : null;
		r.folds     = foldsByTurn.get(key) || 0;
		// The provider's own trace facts for this turn's last traced round, or `null`
		// where none arrived (an older build, or a dialect off OpenRouter). See
		// `lastRoundByTurn` above.
		r.lastRound = lastRoundByTurn.has(key) ? lastRoundByTurn.get(key) : null;
	}
	for (const r of cumulativeRecords(filter, out)) out.push(r);
	out.sort((a, b) => a.ts - b.ts);
	return since ? out.filter(r => r.ts >= since) : out;
}

/// Turns recovered by differencing the per-model running totals every telemetry
/// tick carries. `known` is every turn the other two sources already found; an
/// interval one of them covers for the same device and model yields nothing
/// here, so the two never add up to the same turn twice.
function cumulativeRecords(filter, known) {
	const byDevice = new Map();
	for (const t of loadTelemetry(filter, 0)) {
		if (!t.stats || !Array.isArray(t.stats.models)) continue;
		const list = byDevice.get(t.device) || [];
		list.push(t);
		byDevice.set(t.device, list);
	}
	const out = [];
	for (const [device, ticks] of byDevice) {
		ticks.sort((a, b) => (a.ts || a.bt || 0) - (b.ts || b.bt || 0));
		let prev = null;
		for (const tick of ticks) {
			const now = new Map((tick.stats.models || []).map(m => [m.model, m]));
			if (prev) {
				const from = prev.ts || prev.bt || 0, to = tick.ts || tick.bt || 0;
				for (const [model, m] of now) {
					const was = prev.models.get(model);
					// A model absent from the previous tick is new, so its running
					// total starts at zero; a total that went DOWN is a ledger that
					// was cleared, and a reset is not a turn.
					const dTurns = (m.turns || 0) - (was ? (was.turns || 0) : 0);
					if (dTurns <= 0) continue;
					if (known.some(r => r.device === device && r.model === model
						&& r.ts > from && r.ts <= to)) continue;
					out.push({
						ts: to, device, model, turns: dTurns, rounds: null,
						prompt:     Math.max(0, (m.prompt || 0)     - (was ? (was.prompt || 0) : 0)),
						completion: Math.max(0, (m.completion || 0) - (was ? (was.completion || 0) : 0)),
						cached:     Math.max(0, (m.cached || 0)     - (was ? (was.cached || 0) : 0)),
						usd:        Math.max(0, (m.usd || 0)        - (was ? (was.usd || 0) : 0)),
						// A running total says how many and how much, never how they
						// ended. Claiming `done` here would invent a fact.
						outcome: '?', reported: false, from, src: 'cumulative',
					});
				}
			}
			prev = { ts: tick.ts || tick.bt || 0, bt: tick.bt, models: now };
		}
	}
	return out;
}

/// The newest live picture per device: build, last beat, model, context, worker.
function deviceStates(filter) {
	const by = {};
	const dev = (d) => by[d] || (by[d] = {
		device: d, build: '', name: '', lastBeat: 0, live: null, outbox: null,
		models: [], activity: '', account: '', evSeq: null, health: null,
		screen: null, screenAt: 0,
	});
	for (const d of archiveDevices()) if (wantDevice(d, filter)) dev(d);

	for (const t of loadTelemetry(filter, 0)) {
		const s = dev(t.device);
		const ts = t.ts || t.bt || 0;
		if (ts >= s.lastBeat) {
			s.lastBeat = ts;
			if (t.stats && t.stats.live) s.live = t.stats.live;
			if (t.stats && t.stats.models) s.models = t.stats.models;
		}
		// The build is announced once per boot on the breadcrumb trail, not on
		// every tick, so it is taken from the newest trail row that carries it.
		for (const r of (t.trail || [])) {
			if (!r || r.w !== 'build') continue;
			const id = String(r.d || '').split(' ')[0];
			if (id && (r.t || 0) >= (s.buildAt || 0)) { s.build = id; s.buildAt = r.t || 0; }
		}
	}
	// A snapshot's device roster states the build of every device the account
	// knows, which is the only build the feed carries until `ev` rows ship.
	for (const r of loadSnapshotIndex(filter)) {
		if (!r.builds) continue;
		for (const id of Object.keys(r.builds)) {
			for (const s of Object.values(by)) {
				if (!idsMatch(id, s.device)) continue;
				if ((r.ts || 0) >= (s.buildAt || 0)) { s.build = r.builds[id]; s.buildAt = r.ts || 0; }
			}
		}
	}
	// The short NAME ("argonaut", "gilgamesh", "iOS") a reader recognises, from
	// the same roster -- via `nameFor`, which is where the fallback lives for an
	// archive whose index predates this lane.
	for (const s of Object.values(by)) s.name = nameFor(s.device);
	for (const e of loadEvents(filter, 0)) {
		if (e.src !== 'ev') continue;
		const s = dev(e.device);
		const p = e.ev || {};
		if (p.b && (e.ts || 0) >= (s.buildAt || 0)) { s.build = String(p.b); s.buildAt = e.ts || 0; }
		if (Number.isFinite(p.n)) s.evSeq = Math.max(s.evSeq ?? 0, p.n);
		if (e.kind === 'beat' || e.kind === 'boot') {
			// FEED HEALTH, which only the beat carries: posts the gateway refused
			// for rate, posts that failed for anything else, and console lines the
			// client's own cap dropped. A steady state shows zeroes; anything else
			// is the feed in trouble, and the feed in trouble is why a question
			// below it would have no answer. Taken from the newest BEAT on its own
			// clock -- a telemetry tick arriving after it says nothing about the
			// feed, and must not hide what the beat said.
			if ((p.throttled !== undefined || p.postFail !== undefined || p.cdrop !== undefined)
				&& (e.ts || 0) >= (s.healthAt || 0)) {
				s.health = {
					throttled: Number(p.throttled) || 0,
					postFail:  Number(p.postFail) || 0,
					cdrop:     Number(p.cdrop) || 0,
					at:        e.ts || 0,
				};
				s.healthAt = e.ts || 0;
			}
			if ((e.ts || 0) >= s.lastBeat) {
				s.lastBeat = e.ts || 0;
				if (p.outbox !== undefined) s.outbox = p.outbox;
				if (p.ob !== undefined) s.outbox = p.ob;
				if (p.context !== undefined || p.window !== undefined) {
					s.live = Object.assign({}, s.live, {
						contextActual: p.context ?? (s.live && s.live.contextActual),
						contextWindow: p.window ?? (s.live && s.live.contextWindow),
						foldAt:        p.fold_at ?? (s.live && s.live.foldAt),
						activeModel:   p.model ?? (s.live && s.live.activeModel),
					});
				}
			}
		}
		// THE SCREEN (added 2026-09-13): what the person is actually looking at,
		// shipped only on change or a five-minute floor (see debugshare.js
		// `screenTick`), so the newest one by timestamp is simply the current
		// picture -- there is no aggregation to do, unlike the beat's health.
		if (e.kind === 'screen' && (e.ts || 0) >= s.screenAt) {
			s.screen = p;
			s.screenAt = e.ts || 0;
		}
	}
	return Object.values(by).sort((a, b) => b.lastBeat - a.lastBeat);
}

/// Errors, deduplicated by a normalised message so twenty copies of one fault
/// are one line with a count. Numbers are flattened to `N` for that match, since
/// a line differing only in an id or a byte count is the same fault.
function errorRecords(filter, since, opts) {
	const withAborted = !!(opts && opts.aborted);
	const byMsg = new Map();
	const add = (ts, device, kind, msg, weight, groupKey) => {
		const text = String(msg || '').replace(/\s+/g, ' ').trim().slice(0, 200);
		if (!text) return;
		const key = groupKey || (kind + '|' + text.replace(/\d+/g, 'N'));
		let r = byMsg.get(key);
		if (!r) byMsg.set(key, r = { kind, msg: text, count: 0, first: ts, last: ts, devices: new Set() });
		r.count += (weight > 0 ? weight : 1);
		r.first = Math.min(r.first, ts);
		r.last  = Math.max(r.last, ts);
		r.devices.add(String(device).slice(0, 7));
	};

	const evs = loadEvents(filter, since);
	// When each device last came up, for the reload inference below. A boot is an
	// `ev` row like any other, so it is read off the same pass the errors are.
	const boots = new Map();
	for (const e of evs) {
		if (e.src !== 'ev' || e.kind !== 'boot') continue;
		const k = String(e.device);
		if (!boots.has(k)) boots.set(k, []);
		boots.get(k).push(e.ts || 0);
	}

	/// Did this device RELOAD within the grace window after `ts`?
	///
	/// A reload kills every call in flight and each arrives as a status 0 that
	/// means nothing was wrong. The client tags one `aborted` when the page has
	/// already said `pagehide` or gone hidden -- but a reload the page never saw
	/// coming (the updater's own `location.reload`, a crash-and-restart, iOS
	/// re-instantiating a backgrounded tab) kills the same calls with nothing set,
	/// and those arrived in `errors` as faults. The boot that follows is the proof
	/// the client could not give: a status 0 seconds before a device came up is a
	/// request the reload took, not a gateway that failed.
	const reloadFollowed = (device, ts) => {
		const a = boots.get(String(device));
		if (!a) return false;
		return a.some((b) => b >= ts && (b - ts) <= RELOAD_GRACE_MS);
	};

	for (const e of evs) {
		if (e.src !== 'ev') continue;
		const p = e.ev || {};
		// A console warning or error is an error the app printed and nobody read;
		// the other three levels are the transcript and live under `console`. The
		// repeat count rides through, so twenty of one line count as twenty.
		if (e.kind === 'console') {
			if (p.lvl !== 'warn' && p.lvl !== 'error') continue;
			add(e.ts, e.device, 'console.' + p.lvl, (p.src ? p.src + ' ' : '') + (p.msg || ''),
				Number(p.x) || 1);
			continue;
		}
		// `truncated` and `stalled` are here since proposal 15 (2026-09-15): a provider
		// length cut or a dead stream is worth exactly the same "go and look" treatment
		// as a fetch failure, and until this fix neither reached the feed at all.
		if (!/^(error|fetch\.fail|feed\.fault|feed\.drop|feed\.throttled|truncated|stalled)$/
			.test(e.kind)) continue;
		if (e.kind === 'truncated' || e.kind === 'stalled') {
			add(e.ts, e.device, e.kind,
				'turn ' + (p.turn || '?') + ' round ' + (p.r ?? '?')
					+ (p.provider ? ' via ' + p.provider : '')
					+ (p.finish ? ' finish=' + p.finish : ''),
				1, e.kind + '|' + (p.turn || '?') + '|' + (p.r ?? '?'));
			continue;
		}
		if (e.kind === 'fetch.fail') {
			// A request the page abandoned on its way out is not a fault. It is kept
			// in the archive and shown on request, never counted by default -- whether
			// the client tagged it or the boot that followed gave it away.
			if (!withAborted && (p.aborted || (!(p.status | 0) && reloadFollowed(e.device, e.ts || 0)))) continue;
			// THE PATH AND THE STATUS ARE THE FAULT, so neither is flattened. The
			// generic key above turns every digit into `N`, which made `/api/sync 409`,
			// `413` and `502` one line with a count -- three different faults with three
			// different remedies, reported as one. A thrown fetch has no status and its
			// message is what distinguishes it, so that part is still normalised.
			add(e.ts, e.device, e.kind,
				p.msg || p.message || p.err || ((p.path || '?') + ' ' + (p.status || '')),
				1, e.kind + '|' + (p.path || '?') + '|' + (p.status | 0) + '|'
					+ String(p.msg || p.message || p.err || '').replace(/\d+/g, 'N'));
			continue;
		}
		add(e.ts, e.device, e.kind,
			p.msg || p.message || p.err || (p.path ? p.path + ' ' + (p.status || '') : JSON.stringify(p)));
	}
	// Without `ev` rows the trail and the diagnostics ring are what there is: the
	// trail records `page error` and `unhandled rejection` verbatim, and a ledger
	// entry flagged `e` is a turn that ended badly.
	const seen = new Set();
	for (const t of loadTelemetry(filter, 0)) {
		for (const r of (t.trail || [])) {
			if (!r || !r.w) continue;
			if (!/error|rejection|fail|fault|refus|denied/i.test(r.w)) continue;
			const key = t.device + '|' + r.t + '|' + r.w;
			if (seen.has(key)) continue;
			seen.add(key);
			if (since && (r.t || 0) < since) continue;
			add(r.t || t.ts, t.device, 'trail', r.w + (r.d ? ': ' + r.d : ''));
		}
		for (const r of (t.diag || [])) {
			if (!r || !r.tag) continue;
			const text = r.tag + ' ' + (r.data || '');
			if (!/error|fail|fault|refus|reject|\b(4\d\d|5\d\d)\b/i.test(text)) continue;
			const key = t.device + '|' + r.ts + '|' + r.tag;
			if (seen.has(key)) continue;
			seen.add(key);
			if (since && (r.ts || 0) < since) continue;
			add(r.ts || t.ts, t.device, 'diag', text);
		}
	}
	for (const t of turnRecords(filter, since)) {
		if (t.outcome === 'error') add(t.ts, t.device, 'turn', 'turn ended in error on ' + t.model);
		// A turn that reasoned itself to nothing, or answered nothing at all, is exactly
		// what proposal 15 needed surfaced here: `endedHow` (www/js/daimond.js) names
		// these words and none of them is `done`, so a reader chasing "what went wrong
		// today" sees them without having to know the turn's `how` field exists.
		if (t.outcome === 'reasoned_only' || t.outcome === 'silent')
			add(t.ts, t.device, 'turn', 'turn ended ' + t.outcome + ' on ' + t.model);
	}
	const out = [...byMsg.values()].map(r => ({ ...r, devices: [...r.devices] }));
	out.sort((a, b) => b.last - a.last);
	return out;
}

/// The console as the device printed it, newest last, one record per event --
/// which is already one record per distinct line per minute, with `x` carrying
/// the repeats. `lvls` is the set of levels wanted; the default is the two a
/// reader is looking for.
function consoleRecords(filter, since, lvls) {
	const out = [];
	for (const e of loadEvents(filter, since)) {
		if (e.src !== 'ev' || e.kind !== 'console') continue;
		const p = e.ev || {};
		const lvl = String(p.lvl || '?');
		if (lvls && !lvls.has(lvl)) continue;
		out.push({ ts: e.ts, device: e.device, lvl, msg: String(p.msg || ''),
			src: String(p.src || ''), x: Number(p.x) || 1, build: p.b || '' });
	}
	return out;
}

/// How much the console said in a window, by level. `lines` counts repeats,
/// which is the honest volume; `distinct` counts the events, which is what a
/// reader will actually have to look at.
function consoleCounts(filter, since) {
	const c = { warn: 0, error: 0, other: 0, distinct: 0, lines: 0 };
	for (const r of consoleRecords(filter, since, null)) {
		c.distinct += 1;
		c.lines += r.x;
		if (r.lvl === 'warn' || r.lvl === 'error') c[r.lvl] += r.x;
		else c.other += r.x;
	}
	return c;
}

/// The levels `--lvl` asks for. `all` is every level; anything else is the two
/// defaults widened by the ones named, comma-separated.
function levelSet(v) {
	if (v === undefined || v === null || v === '') return new Set(['warn', 'error']);
	const s = String(v).toLowerCase();
	if (s === 'all' || s === '*') return null;
	return new Set(s.split(',').map(x => x.trim()).filter(Boolean));
}

// ── Formatting ───────────────────────────────────────────────────────


function usd(v) {
	v = Number(v) || 0;
	if (v === 0) return '$0';
	return '$' + (v < 0.01 ? v.toFixed(4) : v.toFixed(2));
}





/// A model id short enough to read in a column, keeping the part that varies.
function shortModel(m) {
	const s = String(m || '?');
	const cut = s.lastIndexOf('/');
	return (cut < 0 ? s : s.slice(cut + 1)).slice(0, 22);
}



let NAME_INDEX = null;

/// Every device id this archive has ever had a roster name for, newest wins.
/// A device's own roster lists the WHOLE account it belongs to, so any ONE
/// snapshot -- not necessarily the named device's own -- names every device.
/// Memoised for the process's life; a fresh `node lens.mjs` invocation per
/// command is what makes that safe.
function nameIndex() {
	if (NAME_INDEX) return NAME_INDEX;
	const byId = {};
	const rows = loadSnapshotIndex(null);
	for (const r of rows) {
		if (!r.names) continue;
		for (const id of Object.keys(r.names)) {
			const cur = byId[id];
			if (!cur || (r.ts || 0) >= cur.ts) byId[id] = { name: r.names[id], ts: r.ts || 0 };
		}
	}
	// Fall back to a snapshot BODY when every index row predates this lane
	// (2026-09-13, `names` added to `summariseSnapshot`): the lightweight index
	// carries nothing to read, but the body it already points at is still on
	// disk, and any ONE account-wide roster names every device -- so the newest
	// body with a non-empty roster is enough, not a re-pull and not a scan of
	// them all.
	if (!Object.keys(byId).length) {
		const withBody = rows.filter(r => r.body).sort((a, b) => (b.ts || 0) - (a.ts || 0));
		for (const r of withBody) {
			const bundle = readJson(path.join(SNAPS, r.body), null);
			const reg = bundle && bundle.roster;
			if (!reg || typeof reg !== 'object' || !Object.keys(reg).length) continue;
			for (const id of Object.keys(reg)) {
				const nm = reg[id] && reg[id].name;
				if (nm) byId[id] = { name: shortRosterName(nm), ts: r.ts || 0 };
			}
			break;
		}
	}
	NAME_INDEX = byId;
	return byId;
}

/// The short roster name for a device id (`argonaut`, `gilgamesh`, `iOS`), or
/// `''` when this archive has never seen one -- an id typed by hand, or a
/// device too new to have shipped a snapshot yet.
function nameFor(device) {
	const idx = nameIndex();
	if (idx[device]) return idx[device].name;
	for (const id of Object.keys(idx)) {
		if (idsMatch(id, device)) return idx[id].name;
	}
	return '';
}

/// The 7-hex id beside its roster name, when one is known. This is what two
/// sessions today needed and did not have: `dev7` alone is what mis-read
/// a7b34e2 (gilgamesh) as argonaut (96a1474, the actual argonaut).
function devLabel(id) {
	const nm = nameFor(id);
	return nm ? `${dev7(id)} ${nm}` : dev7(id);
}


// ── Questions ────────────────────────────────────────────────────────

/// One line of what a device's `screen` event says the person is looking at, or
/// `null` when none has arrived yet (an older build, or one that has not shipped
/// its first beat). `tile` rides the wire as one string, `"role: text"` -- split
/// back into the two words a reader wants, `tile <role> '<text>'`, rather than
/// printed as the raw joined form.
function screenLine(s) {
	if (!s) return null;
	const parts = [String(s.view || '?')];
	if (s.seat) parts.push(`seat '${s.seat}'`);
	if (s.tile) {
		const m = /^([^:]{1,20}): ([\s\S]*)$/.exec(s.tile);
		parts.push(m ? `tile ${m[1]} '${m[2]}'` : `tile '${s.tile}'`);
	}
	parts.push(`dlg ${s.dlg || 'none'}`);
	if (s.locked) parts.push('locked');
	if (s.upd && s.upd !== 'none') parts.push(`upd ${s.upd}`);
	return parts.join(' · ');
}

function cmdStatus(args) {
	const filter = args.flags.device;
	const hour   = Date.now() - 3600000;
	const midnight = (() => { const d = new Date(); d.setHours(0, 0, 0, 0); return d.getTime(); })();
	const since  = sinceMs(args.flags.since, midnight);
	const cov    = coverage(filter);
	const states = deviceStates(filter);
	const turns  = turnRecords(filter, since);
	const errs   = errorRecords(filter, hour);
	const con    = consoleCounts(filter, hour);
	const count  = (rs) => rs.reduce((a, t) => a + (t.turns || 1), 0);

	if (JSONOUT) {
		console.log(JSON.stringify({
			now: Date.now(), since, coverage: cov, devices: states,
			windowTurns: count(turns), turnRecords: turns.length, errors1h: errs,
			console1h: con,
		}));
		return 0;
	}
	if (!states.length) { console.log('status: no devices in the archive; run `lens.mjs pull`.'); return 0; }

	// Coverage first, and in UTC. Everything below it is a count over a window
	// this archive can actually see; a zero here means "none recorded since",
	// never "none happened".
	// The header quotes the TICK coverage, never the oldest row: an election
	// trace from three days ago says nothing about whether a turn was seen.
	const lines = [`archive since ${utcLabel(cov.ticks)} (telemetry/ev)`
		+ (cov.rows && cov.rows < cov.ticks ? `, rows from ${utcLabel(cov.rows)}` : '')
		+ ` — ${states.length} device(s)`];
	for (const s of states) {
		const l = s.live || {};
		const win = Number(l.contextWindow) || 0;
		const act = Number(l.contextActual) || 0;
		const pct = win ? Math.round(100 * act / win) : 0;
		const mine = turns.filter(t => t.device === s.device);
		const spend = mine.reduce((a, t) => a + (t.usd || 0), 0);
		const myErr = errs.filter(e => e.devices.includes(dev7(s.device)))
			.reduce((a, e) => a + e.count, 0);
		const c = (cov.byDevice[s.device] || {}).ticks || 0;
		lines.push(`${s.name ? dev7(s.device) + ' ' + s.name : dev7(s.device)}  build ${s.build || '?'}`
			+ `  beat ${hm(s.lastBeat)} (${ago(s.lastBeat)} ago)  since ${covLabel(c)}`);
		const sees = screenLine(s.screen);
		if (sees) lines.push(`   sees   ${sees}`);
		lines.push(`   live   ${shortModel(l.activeModel)}  ctx ${num(act)}/${num(win)} (${pct}%)`
			+ `  fold@${l.foldAt ? Math.round(l.foldAt * 100) + '%' : '?'}`
			+ `  ${l.activity || '?'}`
			+ (l.workerState ? `  workers ${l.workerState.active}/${l.workerState.queued}` : '')
			+ (s.outbox === null ? '' : `  outbox ${s.outbox}`));
		// A zero that the archive could not have seen is not a zero. Where the
		// window starts before this device's first tick, the count is replaced by
		// the point its record actually begins.
		const blind = !count(mine) && c && since < c;
		lines.push(`   window ${blind ? `(coverage from ${covLabel(c)})` : count(mine) + ' turn(s)'}`
			+ `  ${usd(spend)}  errors(1h) ${myErr}`);
	}
	const tot = turns.reduce((a, t) => a + (t.usd || 0), 0);
	lines.push(`all devices: ${count(turns)} turn(s) since ${windowLabel(since, cov.ticks)}, ${usd(tot)}; `
		+ `${errs.reduce((a, e) => a + e.count, 0)} error(s) in the last hour`);
	// What the console said, and whether the feed itself is healthy. A feed
	// dropping posts or console lines is the reason the numbers above would be
	// short, so it is stated beside them rather than left to be asked for.
	lines.push(`console (1h): ${con.warn} warn, ${con.error} err`
		+ (con.other ? `, ${con.other} other` : '') + `  (${con.distinct} distinct)`);
	const health = states.map(s => s.health).filter(Boolean);
	if (health.length) {
		const sum = (k) => health.reduce((a, h) => a + (h[k] || 0), 0);
		lines.push(`feed: throttled ${sum('throttled')}, postFail ${sum('postFail')},`
			+ ` console dropped ${sum('cdrop')} (last beat)`);
	}
	emit(lines, STATUS_MAX_LINES);
	return 0;
}

function cmdTurns(args) {
	const since = sinceMs(args.flags.since, Date.now() - 2 * 3600000);
	const cov   = coverage(args.flags.device).ticks;
	const rows  = turnRecords(args.flags.device, since);
	const limit = Number(args.flags.limit) || 30;
	if (JSONOUT) { console.log(JSON.stringify(rows)); return 0; }
	if (!rows.length) { console.log(`turns: none since ${windowLabel(since, cov)}.`); return 0; }
	const lines = [];
	for (const t of rows.slice(-limit)) {
		const cp = t.prompt ? Math.round(100 * t.cached / t.prompt) : 0;
		const src = t.src === 'cumulative' ? 'cum' : t.src === 'ended' ? 'end' : (t.reported ? 'rep' : 'est');
		// `maxPrompt`/`folds` come from `round`/`fold` events joined by turn id, so they
		// are blank wherever those events do not exist for a turn (an older build, or a
		// source -- ledger/cumulative -- that carries no turn id to join on at all).
		const maxP = t.maxPrompt == null ? '-' : num(t.maxPrompt);
		const folds = t.folds || 0;
		const inTok = t.prompt == null ? '-' : num(t.prompt).padStart(6);
		const outTok = t.completion == null ? '-' : num(t.completion).padStart(5);
		const spend = t.usd == null ? '-'.padStart(7) : usd(t.usd).padStart(7);
		lines.push(`${hm(t.ts)}  ${devLabel(t.device)}  ${shortModel(t.model).padEnd(22)}`
			+ `  r${t.rounds ?? '-'}  max ${maxP}  f${folds}  in ${inTok}  out ${outTok}`
			+ `  cache ${String(cp).padStart(3)}%  ${spend}`
			+ `  ${src}  ${t.outcome}` + ((t.turns || 1) > 1 ? `  x${t.turns}` : '')
			// The provider's own trace facts for the last traced round, where any
			// arrived. Blank for an older build or a dialect off OpenRouter.
			+ (t.lastRound ? `  ${t.lastRound.stalled ? 'STALLED' : (t.lastRound.finish || '-')}`
				+ (t.lastRound.provider ? ` via ${t.lastRound.provider}` : '') : ''));
	}
	const spend = rows.reduce((a, t) => a + (t.usd || 0), 0);
	const count = rows.reduce((a, t) => a + (t.turns || 1), 0);
	lines.push(`${count} turn(s) in ${rows.length} record(s), ${usd(spend)} since ${windowLabel(since, cov)}`
		+ (rows.length > limit ? ` (showing last ${limit})` : ''));
	emit(lines, limit + 2);
	return 0;
}

function cmdErrors(args) {
	const since = sinceMs(args.flags.since, Date.now() - 3600000);
	// The tick coverage, not the row coverage: an error is read off the trail and
	// the ledger, both of which arrive on a telemetry tick.
	const cov   = coverage(args.flags.device).ticks;
	let rows = errorRecords(args.flags.device, since, { aborted: !!args.bool.aborted });
	if (args.flags.grep) {
		const re = new RegExp(args.flags.grep, 'i');
		rows = rows.filter(r => re.test(r.msg) || re.test(r.kind));
	}
	if (JSONOUT) { console.log(JSON.stringify(rows)); return 0; }
	if (!rows.length) { console.log(`errors: none since ${windowLabel(since, cov)}.`); return 0; }
	const limit = Number(args.flags.limit) || 15;
	const lines = rows.slice(0, limit).map(r =>
		`${hm(r.last)}  x${String(r.count).padStart(3)}  ${r.kind.padEnd(13)}`
		+ `  ${r.devices.map(devLabel).join(',')}  ${r.msg.slice(0, 110)}`);
	lines.push(`${rows.length} distinct message(s) since ${windowLabel(since, cov)}`);
	emit(lines, limit + 1);
	return 0;
}

/// A readable body for one `ev <kind>` row -- generic `JSON.stringify` for most
/// kinds, but `compile` and `diamond` get a one-line rendering so a scroll of
/// `events` reads without reaching for `--json`.
function fmtEventBody(r) {
	if (r.src !== 'ev') return r.data || '';
	const p = r.ev || {};
	if (r.kind === 'compile') {
		// `producer` replaced `engine` outright (the old name carried the live-view
		// flag, not the door that actually compiled -- see `www/js/daimond.js`
		// `pdfHasPages` and `www/js/typstwatch.js` `liveCompileTelemetry`). The
		// fallback to `p.engine` reads ONLY rows archived before that change; a row
		// written since always has `producer` and never falls back.
		const producer = p.producer || p.engine || '-';
		const via = p.via ? ` via=${p.via}` : '';
		return `main=${p.main || '-'} producer=${producer}${via} ok=${p.ok} ms=${p.ms} bytes=${p.bytes} ${p.err || ''}`.trimEnd();
	}
	if (r.kind === 'diamond') {
		const items = Array.isArray(p.items) ? p.items : [];
		return `${p.id || '-'} items=${items.length}: ${items.slice(0, 4).join(', ')}`;
	}
	return JSON.stringify(p);
}

function cmdEvents(args) {
	const since = sinceMs(args.flags.since, Date.now() - 3600000);
	// The ROW coverage here, because that is what this command reads.
	const cov   = coverage(args.flags.device).rows;
	let rows = loadEvents(args.flags.device, since);
	if (args.flags.kind) {
		// A comma-separated list, not just one kind -- `--kind update,boot` was an
		// exact single match against the whole string "update,boot", so it matched
		// nothing and printed "none" with no hint that the flag was misread.
		const ks = String(args.flags.kind).split(',').map(s => s.trim()).filter(Boolean);
		rows = rows.filter(r => ks.some(k =>
			(r.src === 'ev' ? r.kind === k : String(r.tag || '').startsWith(k))));
	}
	if (args.flags.grep) {
		const re = new RegExp(args.flags.grep, 'i');
		rows = rows.filter(r => re.test(JSON.stringify(r.src === 'ev' ? r.ev : r.data || '')) || re.test(r.kind || r.tag || ''));
	}
	if (JSONOUT) { console.log(JSON.stringify(rows)); return 0; }
	if (!rows.length) { console.log(`events: none since ${windowLabel(since, cov)}.`); return 0; }
	const limit = Number(args.flags.limit) || 30;
	const lines = rows.slice(-limit).map((r) => {
		const body = fmtEventBody(r);
		return `${hm(r.ts)}  ${devLabel(r.device)}  ${(r.src === 'ev' ? r.kind : r.tag).slice(0, 24).padEnd(24)}  ${body.slice(0, 100)}`;
	});
	// `--kind round` is throttled at the source (every 5th round plus the one a
	// turn ended on, see daimond.js), so the raw rows above are samples and not
	// a round-by-round trace. One line per turn id -- round range and the
	// highest `ctx` seen -- says what the samples actually cover.
	let summaryLines = 0;
	if (String(args.flags.kind || '') === 'round') {
		const byTurn = new Map();
		for (const r of rows) {
			if (r.src !== 'ev') continue;
			const p = r.ev || {};
			if (!p.turn) continue;
			const s = byTurn.get(p.turn) || { lo: Infinity, hi: -Infinity, max: 0, n: 0 };
			const rr = Number(p.r) || 0, ctx = Number(p.ctx) || 0;
			s.lo = Math.min(s.lo, rr); s.hi = Math.max(s.hi, rr);
			s.max = Math.max(s.max, ctx); s.n += 1;
			byTurn.set(p.turn, s);
		}
		for (const [turn, s] of byTurn) {
			lines.push(`  turn ${turn}: rounds ${s.lo}-${s.hi} sampled (${s.n}), max prompt ${num(s.max)}`);
		}
		// A WORKER'S OWN ROUNDS, keyed `w` rather than `turn` -- see daimond.js's
		// worker sink. No `ctx`: a worker's round row carries only its id and the
		// round number, so the summary is the range and the sample count alone.
		const byWorker = new Map();
		for (const r of rows) {
			if (r.src !== 'ev') continue;
			const p = r.ev || {};
			if (!p.w) continue;
			const s = byWorker.get(p.w) || { lo: Infinity, hi: -Infinity, n: 0 };
			const rr = Number(p.r) || 0;
			s.lo = Math.min(s.lo, rr); s.hi = Math.max(s.hi, rr); s.n += 1;
			byWorker.set(p.w, s);
		}
		for (const [w, s] of byWorker) {
			lines.push(`  worker ${w}: rounds ${s.lo}-${s.hi} sampled (${s.n})`);
		}
		summaryLines = byTurn.size + byWorker.size;
	}
	lines.push(`${rows.length} row(s) since ${windowLabel(since, cov)}`
		+ (rows.length > limit ? ` (showing last ${limit})` : ''));
	emit(lines, limit + 1 + summaryLines);
	return 0;
}

/// What the tab printed. Default warn and error, because that is the question;
/// `--lvl all` is the whole transcript, which on a busy device is long.
function cmdConsole(args) {
	const since = sinceMs(args.flags.since, Date.now() - 3600000);
	const cov   = coverage(args.flags.device).rows;
	const lvls  = levelSet(args.flags.lvl);
	let rows = consoleRecords(args.flags.device, since, lvls);
	if (args.flags.grep) {
		const re = new RegExp(args.flags.grep, 'i');
		rows = rows.filter(r => re.test(r.msg) || re.test(r.src));
	}
	if (JSONOUT) { console.log(JSON.stringify(rows)); return 0; }
	if (!rows.length) {
		console.log(`console: nothing at ${lvls ? [...lvls].join('/') : 'any level'}`
			+ ` since ${windowLabel(since, cov)}.`);
		return 0;
	}
	const limit = Number(args.flags.limit) || 40;
	const lines = rows.slice(-limit).map(r =>
		`${hm(r.ts)}  ${devLabel(r.device)}  ${r.lvl.padEnd(5)}`
		+ `  ${(r.x > 1 ? 'x' + r.x : '').padStart(4)}  ${r.src.slice(0, 28).padEnd(28)}`
		+ `  ${r.msg.slice(0, 100)}`);
	const lines2 = rows.reduce((a, r) => a + r.x, 0);
	lines.push(`${rows.length} distinct line(s), ${lines2} printed, since ${windowLabel(since, cov)}`
		+ (rows.length > limit ? ` (showing last ${limit})` : ''));
	emit(lines, limit + 1);
	return 0;
}

function cmdSnapshot(args) {
	const idx  = loadSnapshotIndex(args.flags.device);
	const pend = pendingSets(args.flags.device).filter(p => p.kind === 'snapshot');
	if (!idx.length) {
		if (JSONOUT) { console.log(JSON.stringify({ sets: [], pending: pend })); return 0; }
		console.log('snapshot: no completed set in the archive'
			+ (pend.length ? `; ${pend.length} still assembling` : '') + '.');
		for (const p of pend.slice(0, 6)) {
			console.log(`  ${dev7(p.device)}  ${p.id}  ${p.have}/${p.n} chunk(s), last ${ago(p.lastBt)} ago`);
		}
		return 0;
	}
	const complete = idx.filter(r => r.complete && r.body);
	const pick = args.flags.id
		? idx.find(r => r.id === args.flags.id)
		: (complete.length ? complete[complete.length - 1] : idx[idx.length - 1]);
	if (!pick) { console.log('snapshot: no such set.'); return 1; }

	if (!pick.complete || !pick.body) {
		// A gap is reported, never guessed at: the rows are gone because jarrah
		// rotated the file before a pull reached it, which is a fact about the
		// pull cadence and worth saying plainly.
		const msg = {
			id: pick.id, device: pick.device, ts: pick.ts,
			complete: false, have: pick.have, of: pick.n, missing: pick.missing,
			note: 'chunks lost to rotation on jarrah before a pull reached them',
		};
		if (JSONOUT) { console.log(JSON.stringify(msg)); return 0; }
		console.log(`snapshot ${pick.id} (${dev7(pick.device)}, ${hm(pick.ts)}): INCOMPLETE`
			+ ` — ${pick.have} of ${pick.n} chunks, missing ${pick.missing}`);
		console.log(`  ${complete.length} of ${idx.length} set(s) in the archive are complete.`);
		return 0;
	}
	const body = readJson(path.join(SNAPS, pick.body), null);
	if (!body) { console.log('snapshot: the body file is missing or unreadable.'); return 1; }
	if (args.flags.out) {
		fs.writeFileSync(args.flags.out, JSON.stringify(body, null, 1));
		console.log(`snapshot ${pick.id} → ${args.flags.out} (${fs.statSync(args.flags.out).size} bytes)`);
		return 0;
	}
	if (JSONOUT) { console.log(JSON.stringify(body)); return 0; }
	// A snapshot is megabytes; printing it whole would blow the reader's budget
	// for no gain, so the default is its shape and `--out` writes the real thing.
	const lines = [`snapshot ${pick.id}  ${dev7(pick.device)}  ${pick.iso || hm(pick.ts)}`
		+ `  ${pick.n} chunk(s)`];
	for (const k of Object.keys(body)) {
		const v = body[k];
		let shape;
		if (Array.isArray(v))		shape = `[${v.length}]`;
		else if (v && typeof v === 'object')	shape = `{${Object.keys(v).length} keys}`;
		else				shape = JSON.stringify(v);
		lines.push(`  ${k.padEnd(14)} ${String(shape).slice(0, 60)}`);
	}
	lines.push(`  (--out FILE for the whole bundle, --json for stdout)`);
	emit(lines, 40);
	return 0;
}

function cmdDigest(args) {
	const day    = Date.now() - 86400000;
	const hour   = Date.now() - 3600000;
	const states = deviceStates(args.flags.device);
	const turns  = turnRecords(args.flags.device, day);
	const errs   = errorRecords(args.flags.device, day);
	const con    = consoleCounts(args.flags.device, hour);
	const tel    = loadTelemetry(args.flags.device, 0);
	const lastTel = tel.length ? tel[tel.length - 1] : null;
	const snaps  = loadSnapshotIndex(args.flags.device);

	const cov = coverage(args.flags.device);
	const byModel = new Map();
	for (const t of turns) {
		const r = byModel.get(t.model) || { turns: 0, usd: 0, prompt: 0, cached: 0 };
		r.turns += t.turns || 1; r.usd += t.usd || 0;
		r.prompt += t.prompt || 0; r.cached += t.cached || 0;
		byModel.set(t.model, r);
	}
	const spend = turns.reduce((a, t) => a + (t.usd || 0), 0);
	const count = turns.reduce((a, t) => a + (t.turns || 1), 0);
	const errs1h = errs.filter(e => e.last >= hour);

	if (JSONOUT) {
		console.log(JSON.stringify({
			now: Date.now(), coverage: cov,
			devices: states.map(s => ({ device: s.device, build: s.build, lastBeat: s.lastBeat, live: s.live })),
			turns24h: count, spend24h: spend,
			models: [...byModel].map(([m, r]) => ({ model: m, ...r })),
			errors1h: errs1h.length, errors24h: errs.length,
			console1h: con,
			feedHealth: states.map(s => s.health).filter(Boolean),
			telemetryTicks: tel.length, snapshotSets: snaps.length,
			snapshotComplete: snaps.filter(s => s.complete).length,
			pendingSets: pendingSets(args.flags.device).length,
		}));
		return 0;
	}

	const lines = [];
	lines.push(`daimond lens — ${utcLabel(Date.now())}  ${states.length} device(s)`
		+ `  archive since ${utcLabel(cov.ticks)}`
		+ (cov.rows && cov.rows < cov.ticks ? ` (rows ${utcLabel(cov.rows)})` : ''));
	for (const s of states.slice(0, 4)) {
		const l = s.live || {};
		const win = Number(l.contextWindow) || 0, act = Number(l.contextActual) || 0;
		lines.push(`${dev7(s.device)} b${s.build || '?'} ${ago(s.lastBeat)} ago`
			+ ` since ${covLabel((cov.byDevice[s.device] || {}).ticks || 0)}`
			+ ` ${shortModel(l.activeModel)} ctx ${num(act)}/${num(win)}`
			+ (win ? ` ${Math.round(100 * act / win)}%` : '')
			+ ` fold@${l.foldAt ? Math.round(l.foldAt * 100) + '%' : '?'} ${l.activity || '?'}`);
	}
	// The window says what it actually covered. "24h: 0" over an archive four
	// hours old is a lie a pickup would act on.
	lines.push(`${cov.ticks && cov.ticks > day ? 'since ' + utcLabel(cov.ticks) : '24h'}:`
		+ ` ${count} turn(s) ${usd(spend)}`);
	const models = [...byModel].sort((a, b) => b[1].usd - a[1].usd).slice(0, 4);
	for (const [m, r] of models) {
		lines.push(`  ${shortModel(m).padEnd(22)} ${String(r.turns).padStart(4)} turn(s)`
			+ ` ${usd(r.usd).padStart(7)}  cache ${r.prompt ? Math.round(100 * r.cached / r.prompt) : 0}%`);
	}
	// An empty window over an archive that begins after the turns it is missing
	// would otherwise read as a quiet account. The running counters on the newest
	// tick are all-time totals, so they still say what this account has done.
	if (!count && lastTel && lastTel.stats && Array.isArray(lastTel.stats.models)) {
		const all = lastTel.stats.models.slice().sort((a, b) => (b.usd || 0) - (a.usd || 0));
		const tt = all.reduce((a, m) => a + (m.turns || 0), 0);
		const tu = all.reduce((a, m) => a + (m.usd || 0), 0);
		if (tt) {
			lines.push(`  counters (all time, ${dev7(lastTel.device)}): ${tt} turn(s) ${usd(tu)}`
				+ ' — ' + all.slice(0, 2).map(m => `${shortModel(m.model)} ${m.turns} ${usd(m.usd)}`).join(', '));
		}
	}
	lines.push(`errors: ${errs1h.reduce((a, e) => a + e.count, 0)} in 1h,`
		+ ` ${errs.reduce((a, e) => a + e.count, 0)} in 24h, ${errs.length} distinct`);
	for (const e of errs.slice(0, 3)) lines.push(`  x${e.count} ${e.kind}: ${e.msg.slice(0, 88)}`);
	lines.push(`console (1h): ${con.warn} warn, ${con.error} err`
		+ (con.other ? `, ${con.other} other` : '') + ` (${con.distinct} distinct)`);
	const pend = pendingSets(args.flags.device);
	const health = states.map(s => s.health).filter(Boolean);
	const sum = (k) => health.reduce((a, h) => a + (h[k] || 0), 0);
	lines.push(`feed: ${tel.length} telemetry tick(s), last ${lastTel ? ago(lastTel.ts || lastTel.bt) + ' ago' : 'never'};`
		+ ` ${snaps.filter(s => s.complete).length}/${snaps.length} snapshot set(s) complete`
		+ (pend.length ? `, ${pend.length} assembling` : '')
		+ (health.length ? `; throttled ${sum('throttled')} postFail ${sum('postFail')} cdrop ${sum('cdrop')}` : ''));

	// The cap is the contract. Drop from the middle -- the device block and the
	// feed line are what a pickup needs -- rather than truncating the tail.
	let out = lines.join('\n');
	while (Buffer.byteLength(out) > DIGEST_MAX_BYTES && lines.length > 4) {
		lines.splice(Math.max(1, lines.length - 3), 1);
		out = lines.join('\n');
	}
	console.log(out);
	return 0;
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function cmdWatch(args) {
	let mark = sinceMs(args.flags.since, Date.now() - 5 * 60000);
	const once = !!args.bool.once;
	for (;;) {
		if (!args.bool['no-pull']) cmdPullQuiet(args);
		const rows = loadEvents(args.flags.device, mark);
		for (const r of rows) {
			const body = r.src === 'ev' ? JSON.stringify(r.ev) : (r.data || '');
			console.log(`${hm(r.ts)}  ${dev7(r.device)}  ${(r.src === 'ev' ? r.kind : r.tag).slice(0, 24).padEnd(24)}  ${body.slice(0, 100)}`);
			mark = Math.max(mark, (r.ts || 0) + 1);
		}
		const tel = loadTelemetry(args.flags.device, mark);
		for (const t of tel) {
			const l = (t.stats && t.stats.live) || {};
			console.log(`${hm(t.ts)}  ${dev7(t.device)}  tick`.padEnd(45)
				+ `  ${shortModel(l.activeModel)} ctx ${num(l.contextActual)}/${num(l.contextWindow)}`
				+ ` ${l.activity || '?'}  +${(t.ledger || []).length} ledger`);
			mark = Math.max(mark, (t.ts || 0) + 1);
		}
		if (once) return 0;
		await sleep(15000);
	}
}

/// `watch` pulls on every cycle but must not print a pull report each time.
function cmdPullQuiet(args) {
	const saved = console.log;
	console.log = () => {};
	try { cmdPull(args); } finally { console.log = saved; }
}

// ── Dispatch ─────────────────────────────────────────────────────────

const COMMANDS = {
	pull:     cmdPull,
	status:   cmdStatus,
	turns:    cmdTurns,
	errors:   cmdErrors,
	console:  cmdConsole,
	events:   cmdEvents,
	snapshot: cmdSnapshot,
	watch:    cmdWatch,
	digest:   cmdDigest,
};

const fn = COMMANDS[ARGS.cmd];
if (!fn) {
	console.log('lens.mjs — commands: ' + Object.keys(COMMANDS).join(', ')
		+ '\n  see the usage block at the top of this file');
	process.exit(ARGS.cmd === 'help' || ARGS.bool.help ? 0 : 2);
}
const rc = await fn(ARGS);
process.exit(rc || 0);
