// make_adapter.mjs -- builds `daimond_debugshare.js`: what Daimond's `www/js/debugshare.js` becomes
// when it adopts the extracted writer core.
//
//   node test/adapter/make_adapter.mjs <path to daimond/www/js/debugshare.js>
//
// The app layer (the Settings flag and its sync, the snapshot and telemetry lanes, the beat, the
// screen, the fold inference, the indicator) is cut from Daimond's own file by line range, so it
// is Daimond's code and not a rewrite. What the core now owns (the outbox, the envelope, the
// fit, the drain and its clock, console and error capture, the redactor, the scrubber) is
// replaced by the glue below. The result is committed, so the test needs no Daimond file but the
// two it runs; this script is how it was made, and the line ranges are valid for the file whose
// sha-256 begins as recorded in `T5b_record.md`.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const src  = readFileSync(process.argv[2], 'utf8').split('\n');
const seg  = (a, b) => src.slice(a - 1, b).join('\n');

function sub(text, from, to) {
	if (text.split(from).length !== 2) throw new Error('expected exactly one: ' + from.slice(0, 70));
	return text.replace(from, () => to);
}

// ── Daimond's own text, by line range ──
let consts   = [seg(113, 145), seg(153, 156), seg(163, 165), seg(166, 182), seg(199, 240)].join('\n');
let reading  = [seg(319, 345), seg(358, 374)].join('\n');
let assembly = [seg(682, 774), seg(776, 1036)].join('\n');
let caps     = seg(1209, 1226);
let fold     = seg(1287, 1315);
let beat     = seg(1507, 1553);
let device   = seg(1596, 1599);
let enqueue  = seg(1711, 1734);
let indic    = seg(1736, 1803);
let sw       = seg(1805, 2075);
let exports  = seg(2164, 2245);

// ── What changes where the core took over ──
beat = sub(beat, 'ob:    outbox.length,', 'ob:    W.depth(),');
beat = sub(beat, 'throttled: throttledCount,', 'throttled: W.health().throttled,');
beat = sub(beat, 'postFail:  postFailCount,', 'postFail:  W.health().postFail,');
beat = sub(beat, 'cdrop:     (function () { var n = conDropped; conDropped = 0; return n; })(),', 'cdrop:     W.takeConsoleDropped(),');
beat = sub(beat, 'flushConsole(now, true);', 'W.flushConsole(now, true);');
fold = sub(fold, "emit('fold', {", "W.event('fold', {");
fold = sub(fold, 'catch (e) { fault(e); }', 'catch (e) { W.fault(e); }');
const a = sw.indexOf('\t\t\t// AND THE OUTBOX.');
const b = sw.indexOf('\t\t\tpersistNow();') + '\t\t\tpersistNow();'.length;
if (a < 0 || b < a) throw new Error('applyState off-branch not found');
sw = sw.slice(0, a) + '\t\t\t// The outbox, and what the console lane held, go with it: see `W.reset`.\n\t\t\tW.reset();' + sw.slice(b);
enqueue = enqueue.replace(/(?<![.\w])drain\(\)/g, 'W.drain()');
sw      = sw.replace(/(?<![.\w])drain\(\)/g, 'W.drain()');
// `feedOff` was a local; the writer owns it now.
const feed = (t) => t.replace(/\bfeedOff\b/g, '!W.ok()');
beat = feed(beat); enqueue = feed(enqueue); sw = feed(sw); exports = feed(exports);
exports = sub(exports, 'outboxDepth:      function () { return outbox.length; },', 'outboxDepth:      function () { return W.depth(); },');
exports = sub(exports, '_outbox:      function () { return outbox.slice(); },', '_outbox:      function () { return W.outbox(); },');
exports = sub(exports, '_backoffMs:   function (n) { failStreak = n; return backoffMs(); },', '_backoffMs:   function (n) { return W.backoffMs(n); },');
exports = sub(exports, '_drain:       drain,', '_drain:       function () { return W.drain(); },');
const h0 = exports.indexOf('\t\t_health:      function () {');
const h1 = exports.indexOf('\t\t},', h0) + '\t\t},'.length;
exports = exports.slice(0, h0) + '\t\t_health:      function () { return W.health(); },' + exports.slice(h1);

const out = `/* daimond_debugshare.js -- GENERATED by make_adapter.mjs. Daimond's www/js/debugshare.js as it
 * would stand after adopting fe2o3_net/lens/js/writer.js: its own app layer, cut from its own
 * file by line range, over the extracted writer core in \`__lensCore\`.
 *
 * It is a classic script, evaluated by Daimond's own test harness exactly as the original is, so
 * the core arrives as a global the preload supplies; in the page it would be an import.
 */
(function () {
\t'use strict';
\tvar L = __lensCore;

${consts.split('\n').slice(1).join('\n')}

\t// ── App state. What the writer owns (the outbox, the post clock, the console lane) is gone. ──
\tvar enabled  = read(ENABLED_KEY) === '1';
\tvar provider = null;			// registered by daimond.js: () -> (obj | Promise<obj>)
\tvar statsFn  = null;			// registered by daimond.js: () -> live-stats obj (sync, cheap)
\tvar screenFn = null;			// registered by daimond.js: () -> {view,seat,role,text,dlg,comp,locked}
\tvar crossIx  = {};				// diamondId -> model -> {turns, usd}, filled while on
\tvar telQueue  = [];				// priority lane: telemetry posts, each an array of rows
\tvar snapQueue = [];				// snapshot lane: drained only when telQueue is empty
\tvar telTimer = null, snapTimer = null, beatTimer = null;
\tvar lastBeatAt  = 0;
\tvar lastScreenAt = 0, lastScreenKey = null;
\tvar lastCtx     = {};
\tvar lastRealFold = {};
\tvar indicator = null;
\tvar lastLedgerLen = 0, lastTrailLen = 0, lastDiagLen = 0;

${reading}

\t// ── Names, content shapes and the redactor: the core's, with Daimond's two parameters. ──
\tvar SCRUB = L.createScrubber({
\t\t// The gateway's own session cookie. It is HttpOnly, so this app cannot read it, but a server
\t\t// log line pasted into a chat is not bound by that.
\t\tpairs:  [{ k: 'cookie', g: 2, re: /(daimond_gw_sess=)([^;,\\s"'\\[\\]]{4,})/g }],
\t\t// \`body\` is the archive's own snapshot FILENAME, which the entropy catch used to take.
\t\tidKeys: { holder: 1, self: 1, nominated: 1, body: 1 },
\t});
\tvar REDACT = L.createRedactor();
\tvar REDACT_CONFIG = L.createRedactor({ loose: true });
\tfunction scrubText(s, isId) { return SCRUB.text(s, isId); }
\tfunction scrubDeep(o) { return SCRUB.deep(o); }
\tfunction redact(o) { return REDACT.value(o); }
\tfunction redactConfig(o) { return REDACT_CONFIG.value(o); }
\tfunction fingerprint(v) { return L.fingerprint(v); }
\tfunction byteLen(s) { return L.byteLen(s); }
\tfunction str(o) { return JSON.stringify(o); }

${assembly}

${caps}

${fold}

${beat}

${device}

\t// ── The writer core, handed Daimond's seams ──
\tfunction buildRaw() {
\t\ttry {
\t\t\tif (window.DaimondUpdater && DaimondUpdater.booted && DaimondUpdater.booted()) return DaimondUpdater.booted();
\t\t} catch (e) { /* the updater has not polled */ }
\t\treturn read(BUILD_KEY) || '';
\t}
\tvar W = L.createWriter({
\t\thost:    { storage: localStorage, setTimeout: setTimeout, clearTimeout: clearTimeout, console: console,
\t\t           now: function () { return Date.now(); }, document: typeof document !== 'undefined' ? document : null,
		           // Read at call time, so the test that swaps the tab's Error for one with no stack is seen.
		           get Error() { return Error; } },
\t\tkeys:    { outbox: EVENT_KEY, seq: SEQ_KEY, postAt: POST_AT_KEY },
\t\tdevice:  deviceId,
\t\tbuild:   buildRaw,
\t\tenabled: function () { return enabled; },
\t\tsend:    function (rows) {
\t\t\treturn fetch(ENDPOINT, {
\t\t\t\tmethod:      'POST',
\t\t\t\tcredentials: 'same-origin',
\t\t\t\theaders:     { 'content-type': 'application/json', 'x-daimond-api': String(CLIENT_API) },
\t\t\t\tbody:        W.postBody(rows),
\t\t\t});
\t\t},
\t\tredact:  REDACT,
\t\tscrub:   SCRUB,
\t\textra:   function (kind) {
\t\t\tif (kind !== 'boot' && kind !== 'beat') return null;
\t\t\tvar cap = capabilities();
\t\t\treturn { tools: cap.tools, folder: cap.folder, mayCommit: cap.mayCommit };
\t\t},
\t\tlane:    {
\t\t\tpending: function () { return telQueue.length > 0 || snapQueue.length > 0; },
\t\t\tnext:    function () { return telQueue.length ? telQueue.shift() : snapQueue.shift(); },
\t\t},
\t\townPath:    ENDPOINT,
\t\tskipFrames: ['debugshare.js'],
\t\tafter:   function (kind, payload) { if (kind === 'round') inferFold(payload); },
\t\tonFault: function () { stopTimers(); },
\t\tcaps:    { gapMs: DRAIN_MS },
\t});
\tfunction clip(s, n) { return W.clip(s, n); }
\tfunction event(kind, payload) { return W.event(kind, payload); }
\tfunction fault(e) { W.fault(e); }
\tfunction noteFetchFail(p, s, l, e) { return W.noteFetchFail(p, s, l, e); }
\tfunction persistNow() { W.persistNow(); }
\tfunction noteError(m, w) { W.noteError(m, w); }
\tfunction noteConsole(lvl, args) { W.noteConsole(lvl, args); }
\tfunction flushConsole(t, force) { W.flushConsole(t, force); }
\tfunction looksSecret(m) { return L.looksSecret(m); }
\tfunction gapLeft() { return W.gapLeft(); }
\tfunction fit(o) { return W.fit(o); }
\tfunction eventBatch() { return W.eventBatch(); }

${enqueue}

${indic}

${sw}

\t// ── Capture: errors, the console, and the page going away. All three are the core's. ──
\tW.captureErrors(window);
\tW.captureConsole(typeof console !== 'undefined' ? console : null);
\tW.captureLifecycle(window, typeof document !== 'undefined' ? document : undefined);

${exports}
`;
writeFileSync(join(HERE, 'daimond_debugshare.js'), out);
console.log('wrote daimond_debugshare.js, ' + out.split('\n').length + ' lines');
