#!/usr/bin/env python3
"""Generates a deterministic synthetic Typst document for the S0 bench harness.

No book content: every word is drawn from a small fixed vocabulary by a seeded
PRNG, so the text carries no meaning and no licence. Each page mixes a heading,
two or three prose paragraphs, and -- on every fifth page -- a small table or a
maths block, so the document exercises more than the pure-text path without
pulling in cetz or other package fixtures S0 was not asked to touch.

Every paragraph opens with a sentinel token `EDITTOK{n}` (n = 1-based paragraph
index across the whole document), so `edit_latency.mjs` can find paragraph N by
string search and flip one character in it without parsing the document.

Usage: gen_synthetic.py <pages> <out.typ>
"""
import random
import sys

VOCAB = (
	"lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod "
	"tempor incididunt ut labore et dolore magna aliqua enim ad minim veniam "
	"quis nostrud exercitation ullamco laboris nisi aliquip ex ea commodo "
	"consequat duis aute irure in reprehenderit voluptate velit esse cillum "
	"eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident"
).split()


def sentence(rng, n_words):
	words = [rng.choice(VOCAB) for _ in range(n_words)]
	words[0] = words[0].capitalize()
	return " ".join(words) + "."


def paragraph(rng, tok):
	sentences = [sentence(rng, rng.randint(6, 14)) for _ in range(rng.randint(3, 6))]
	return f"{tok} " + " ".join(sentences)


def table_block(rng, page):
	rows = []
	for r in range(4):
		cells = [str(rng.randint(0, 9999)) for _ in range(3)]
		rows.append("  [" + "], [".join(cells) + "],")
	body = "\n".join(rows)
	return (
		f"#table(\n  columns: 3,\n  [A], [B], [C],\n{body}\n)"
	)


def maths_block(rng, page):
	a, b, c = rng.randint(2, 9), rng.randint(2, 9), rng.randint(2, 9)
	return f"$ ({a}x + {b})^{c} = sum_(k=0)^{c} binom({c}, k) ({a}x)^k {b}^({c}-k) $"


def main():
	if len(sys.argv) != 3:
		print("usage: gen_synthetic.py <pages> <out.typ>", file=sys.stderr)
		sys.exit(2)
	pages = int(sys.argv[1])
	out_path = sys.argv[2]
	rng = random.Random(20260923)  # fixed seed: reproducible across runs and machines

	lines = [
		"// Generated by tools/bench/gen_synthetic.py -- synthetic, no book content.",
		"// Regenerate rather than hand-edit; edit_latency.mjs depends on the EDITTOK",
		"// markers below staying at paragraph-start.",
		"#set page(width: 15cm, height: 21cm, margin: 2cm)",
		"#set text(size: 10pt)",
		"#set par(justify: true)",
		"",
	]
	tok = 0
	for page in range(1, pages + 1):
		lines.append(f"= Section {page}")
		n_paras = 2 if page % 5 == 0 else 3
		for _ in range(n_paras):
			tok += 1
			lines.append(paragraph(rng, f"EDITTOK{tok}"))
			lines.append("")
		if page % 10 == 0:
			lines.append(maths_block(rng, page))
			lines.append("")
		elif page % 5 == 0:
			lines.append(table_block(rng, page))
			lines.append("")
		if page != pages:
			lines.append("#pagebreak()")
			lines.append("")

	with open(out_path, "w") as f:
		f.write("\n".join(lines) + "\n")
	print(f"wrote {out_path}: {pages} pages, {tok} paragraphs", file=sys.stderr)


if __name__ == "__main__":
	main()
