#!/bin/bash
CC=/usr/bin/gcc
CFLAGS="-Wall -Wextra -Wmissing-prototypes -Wredundant-decls -O3 -fomit-frame-pointer -march=native" 
NISTFLAGS="-Wno-unused-result -O3 -fomit-frame-pointer -march=native -std=c99" 
RM=/bin/rm

# Uncomment one of these to choose scheme
STATIC=liblightsaber.a
#STATIC=libsaber.a
#STATIC=libfiresaber.a
rm -fr $STATIC
SOURCES="pack_unpack.c poly.c fips202.c verify.c cbd.c SABER_indcpa.c kem.c"
OBJS="pack_unpack.o poly.o fips202.o verify.o cbd.o SABER_indcpa.o kem.o rng.o"
#HEADERS="SABER_params.h pack_unpack.h poly.h rng.h fips202.h verify.h cbd.h SABER_indcpa.h"

gcc ${NISTFLAGS} -c rng.c -lcrypto -o rng.o 
gcc ${CFLAGS} ${SOURCES} rng.o -c -lcrypto
ar rcs ${STATIC} ${OBJS}

rm -f *.o
touch bindgen_wrapper.h
