#!/bin/bash
# Regenerates the JPEG fixtures in this directory.
#
# Nothing here is a photograph: every source image is generated by this script, written out as a
# PPM, and handed to ImageMagick to compress. The JPEGs are therefore ImageMagick's work and not
# ours, which is the point -- a codec that agrees only with itself has been tested against nothing.
#
# Requires ImageMagick's `convert`. Run from this directory.
set -eu
cd "$(dirname "$0")"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# ---- The sources, each written as a binary PPM by a short Python program. ----
python3 - "$tmp" <<'PYEOF'
import sys, os, math
d = sys.argv[1]

def ppm(name, w, h, fn):
	px = bytearray()
	for y in range(h):
		for x in range(w):
			r, g, b = fn(x, y)
			px += bytes((r & 255, g & 255, b & 255))
	with open(os.path.join(d, name + ".ppm"), "wb") as f:
		f.write(b"P6\n%d %d\n255\n" % (w, h))
		f.write(px)

# A smooth two-axis gradient: the easy case, where every block is nearly flat.
ppm("gradient", 64, 48, lambda x, y: (x * 4, y * 5, (x + y) * 2))

# Deterministic noise: the hard case, where every coefficient carries something.
def noise(x, y):
	s = (x * 1103515245 + y * 12345 + 7) & 0x7FFFFFFF
	s = (s ^ (s >> 13)) * 2654435761 & 0x7FFFFFFF
	return (s & 255, (s >> 8) & 255, (s >> 16) & 255)
ppm("noise", 33, 17, noise)

# Saturated primaries in hard-edged blocks: the case chroma subsampling is worst at.
def prim(x, y):
	c = [(255,0,0), (0,255,0), (0,0,255), (255,255,0),
	     (0,255,255), (255,0,255), (255,255,255), (0,0,0)]
	return c[((x // 8) + (y // 8) * 3) % 8]
ppm("primaries", 48, 32, prim)

# A single pixel, where every edge case in an upsampler meets at once.
ppm("tiny", 1, 1, lambda x, y: (200, 40, 90))

# Odd dimensions, so that neither axis is a multiple of a block or an MCU.
ppm("odd", 17, 13, lambda x, y: (
	int(127 + 120 * math.sin(x * 0.7)),
	int(127 + 120 * math.sin(y * 0.9)),
	int(127 + 120 * math.sin((x + y) * 0.5)),
))

# A grey ramp, for the single-component path.
ppm("ramp", 40, 24, lambda x, y: ((x * 6) % 256,) * 3)
PYEOF

# ---- The JPEGs. ----
c() { convert "$tmp/$1.ppm" "${@:3}" "$2.jpg"; }

c gradient  gradient_q90_444  -quality 90 -sampling-factor 1x1
c gradient  gradient_q75_420  -quality 75 -sampling-factor 2x2
c gradient  gradient_q50_422  -quality 50 -sampling-factor 2x1
c gradient  gradient_q80_prog -quality 80 -sampling-factor 2x2 -interlace JPEG
c noise     noise_q95_444     -quality 95 -sampling-factor 1x1
c noise     noise_q60_420     -quality 60 -sampling-factor 2x2
c noise     noise_q85_prog    -quality 85 -sampling-factor 1x1 -interlace JPEG
c primaries primaries_q92_444 -quality 92 -sampling-factor 1x1
c primaries primaries_q70_420 -quality 70 -sampling-factor 2x2
c primaries primaries_q70_422 -quality 70 -sampling-factor 2x1
c tiny      tiny_q90_420      -quality 90 -sampling-factor 2x2
c odd       odd_q88_444       -quality 88 -sampling-factor 1x1
c odd       odd_q64_420       -quality 64 -sampling-factor 2x2
c odd       odd_q88_prog      -quality 88 -sampling-factor 2x2 -interlace JPEG
c ramp      ramp_q90_grey     -quality 90 -colorspace Gray -type Grayscale
c ramp      ramp_q90_prog     -quality 90 -colorspace Gray -type Grayscale -interlace JPEG

# Restart markers, which nothing above exercises.
convert "$tmp/noise.ppm" -quality 80 -sampling-factor 2x2 -define jpeg:restart-interval=2 \
	noise_q80_rst.jpg

# The reference decodings, as ImageMagick reads its own files back.
for f in *.jpg; do
	convert "$f" "${f%.jpg}.ppm"
done

ls -l
