// crosscheck.test.mjs -- the JavaScript redactor against the oracle tables T5a's Rust redactor
// is tested on, so that the two halves of the lens cannot drift apart.
//
// `fe2o3_net/tests/data/lens_secret_re.tsv` and `lens_fingerprint.tsv` were generated by
// `lens_oracle.mjs` from Daimond's own `SECRET_RE`, `SECRET_RE_LOOSE` and `fingerprint`, and
// `tests/lens.rs` holds `secret_name`, `secret_name_loose` and `fingerprint` to them in Rust.
// Here the same tables hold `redact.js`: if it, Daimond's source and the Rust agree on every
// row, a name or a value is covered identically on the page and at the peer.
//
//   node test/crosscheck.test.mjs
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRedactor, fingerprint, secretName } from '../redact.js';
import { check, finish, section } from './harness.mjs';

const DATA = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'tests', 'data');
const lines = (f) => readFileSync(join(DATA, f), 'utf8').split('\n').filter((l) => l.length);

section('crosscheck: secret names, strict and loose, against lens_secret_re.tsv');
{
	const rows = lines('lens_secret_re.tsv').map((l) => l.split('\t'));
	let strictBad = 0, looseBad = 0, strictHits = 0, firstBad = '';
	const R = createRedactor(), L = createRedactor({ loose: true });
	for (const [name, strict, loose] of rows) {
		const s = secretName(name) ? 1 : 0, lo = secretName(name, true) ? 1 : 0;
		if (s !== Number(strict)) { strictBad += 1; firstBad = firstBad || name; }
		if (lo !== Number(loose)) { looseBad += 1; firstBad = firstBad || name; }
		if (R.secret(name) !== (Number(strict) === 1) || L.secret(name) !== (Number(loose) === 1)) { strictBad += 1; firstBad = firstBad || name; }
		strictHits += Number(strict);
	}
	check('the table has the 3,136 names Rust is tested on', rows.length === 3136, rows.length + ' rows');
	check('the strict rule agrees on every name', strictBad === 0, strictBad + ' differ, first ' + JSON.stringify(firstBad));
	check('the loose rule agrees on every name', looseBad === 0, looseBad + ' differ');
	check('the table is not one answer: it holds both hits and misses', strictHits > 500 && strictHits < rows.length - 500, strictHits + ' strict hits');
}

section('crosscheck: fingerprints against lens_fingerprint.tsv');
{
	const rows = lines('lens_fingerprint.tsv').map((l) => l.split('\t').map((c) => JSON.parse(c)));
	const bad = rows.filter(([input, want]) => fingerprint(input) !== want);
	check('the table has its 21 inputs, including a number, a null, an astral and a long string', rows.length === 21, rows.length + ' rows');
	check('every fingerprint agrees, character for character', bad.length === 0, JSON.stringify(bad.slice(0, 2)));
	check('the table has a surrogate pair, whose length counts in UTF-16 units as the Rust does',
		rows.some(([i]) => typeof i === 'string' && /[\u{10000}-\u{10ffff}]/u.test(i)));
	check('a redactor walk fingerprints through the same function',
		createRedactor().value({ apiKey: 'abcdefghi' }).apiKey === fingerprint('abcdefghi'));
}

finish('crosscheck');
