// crosscheck.test.mjs -- the JavaScript redactor against the oracle tables T5a's Rust redactor
// is tested on, so that the two halves of the lens cannot drift apart.
//
// `fe2o3_net/tests/data/lens_secret_re.tsv` and `lens_fingerprint.tsv` were generated by
// `lens_oracle.mjs` from Daimond's own `SECRET_RE`, `SECRET_RE_LOOSE` and `fingerprint`, and
// `tests/lens.rs` holds `secret_name`, `secret_name_loose` and `fingerprint` to them in Rust.
// Here the same tables hold `redact.js`: if it, Daimond's source and the Rust agree on every
// row, a name or a value is covered identically on the page and at the peer.
//
//   node test/crosscheck.test.mjs
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRedactor, fingerprint, scrubText, secretName } from '../redact.js';
import { check, finish, section } from './harness.mjs';
import { TEMPLATES, expand } from './scrub_corpus.mjs';

const DATA = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'tests', 'data');
const lines = (f) => readFileSync(join(DATA, f), 'utf8').split('\n').filter((l) => l.length);

section('crosscheck: secret names, strict and loose, against lens_secret_re.tsv');
{
	const rows = lines('lens_secret_re.tsv').map((l) => l.split('\t'));
	let strictBad = 0, looseBad = 0, strictHits = 0, firstBad = '';
	const R = createRedactor(), L = createRedactor({ loose: true });
	for (const [name, strict, loose] of rows) {
		const s = secretName(name) ? 1 : 0, lo = secretName(name, true) ? 1 : 0;
		if (s !== Number(strict)) { strictBad += 1; firstBad = firstBad || name; }
		if (lo !== Number(loose)) { looseBad += 1; firstBad = firstBad || name; }
		if (R.secret(name) !== (Number(strict) === 1) || L.secret(name) !== (Number(loose) === 1)) { strictBad += 1; firstBad = firstBad || name; }
		strictHits += Number(strict);
	}
	check('the table has the 3,136 names Rust is tested on', rows.length === 3136, rows.length + ' rows');
	check('the strict rule agrees on every name', strictBad === 0, strictBad + ' differ, first ' + JSON.stringify(firstBad));
	check('the loose rule agrees on every name', looseBad === 0, looseBad + ' differ');
	check('the table is not one answer: it holds both hits and misses', strictHits > 500 && strictHits < rows.length - 500, strictHits + ' strict hits');
}

section('crosscheck: fingerprints against lens_fingerprint.tsv');
{
	const rows = lines('lens_fingerprint.tsv').map((l) => l.split('\t').map((c) => JSON.parse(c)));
	const bad = rows.filter(([input, want]) => fingerprint(input) !== want);
	check('the table has its 21 inputs, including a number, a null, an astral and a long string', rows.length === 21, rows.length + ' rows');
	check('every fingerprint agrees, character for character', bad.length === 0, JSON.stringify(bad.slice(0, 2)));
	check('the table has a surrogate pair, whose length counts in UTF-16 units as the Rust does',
		rows.some(([i]) => typeof i === 'string' && /[\u{10000}-\u{10ffff}]/u.test(i)));
	check('a redactor walk fingerprints through the same function',
		createRedactor().value({ apiKey: 'abcdefghi' }).apiKey === fingerprint('abcdefghi'));
}

section('crosscheck: the content scrubber against lens_scrub.tsv, the table Rust\'s Shapes is held to');
{
	// Template, scrubbed output and the id flag, from `gen_scrub_oracle.mjs`. The table holds the recipe
	// of each input and never a credential; `scrub_corpus.mjs` says how to expand one.
	const rows = lines('lens_scrub.tsv').map((l) => l.split('\t')).map(([t, o, id]) => [JSON.parse(t), JSON.parse(o), id === '1']);
	const bad = rows.filter(([t, o, id]) => scrubText(expand(t), id) !== o);
	check('every case scrubs to the table\'s output, character for character', bad.length === 0, bad.length + ' differ, first ' + JSON.stringify(bad[0] && bad[0][0]));
	check('the table is the corpus, expanded and scrubbed now (regenerate it if redact.js moved)',
		rows.length === TEMPLATES.length && rows.every(([t, , id], i) => t === TEMPLATES[i][0] && id === (TEMPLATES[i][1] === 1)), rows.length + ' rows');
	const kinds = new Set();
	for (const [, o] of rows) for (const m of o.matchAll(/\[redacted (\w+) #/g)) kinds.add(m[1]);
	check('it exercises every shape, pair and the entropy catch',
		['pem', 'gh', 'ghpat', 'stripe', 'whsec', 'sk', 'aws', 'gcp', 'slack', 'jwt', 'tune', 'bearer', 'urlarg', 'named', 'awssec', 'hi'].every((k) => kinds.has(k)), [...kinds].join());
	const same = rows.filter(([t, o]) => o === expand(t)).length;
	check('and it holds decoys that must come through untouched', same >= 15 && same < rows.length - 50, same + ' of ' + rows.length + ' unchanged');
	check('a case that was already scrubbed stays as it is (the second pass is idempotent)',
		rows.every(([, o, id]) => scrubText(o, id) === o));
	check('the table holds no literal credential: no template has a long run of characters outside a token',
		rows.every(([t]) => { const r = t.replace(/\{\{[^}]*\}\}/g, ''); return !/[A-Za-z0-9]{20,}/.test(r) && !/(?:sk_|rk_|pk_|sk-|ghp_|gho_|AKIA|ASIA|eyJ|xox.-|AIza|whsec_|tune-)[A-Za-z0-9]{8,}/.test(r); }));
	// Pinned expansions, so a port of the expander can be checked before it is trusted with the table.
	check('the expander gives the pinned vectors',
		expand('{{8:1:hex}}') === '8388dbc2' && expand('{{12:7:alnum}}') === 'Dn8QmkIRy6vU' && expand('{{10:3:digit}}') === '0086285001'
		&& expand('{{6:5:upper36}}') === 'PJMEIR' && expand('a{{dash5}}b') === 'a-----b');
}

finish('crosscheck');
