//! `fe2o3_net::lens`, the generic half of a debug lens.
//!
//! The gates, the envelope and the redaction rule are Daimond's (`gateway/src/handlers/
//! debug_trace.rs` and `www/js/debugshare.js`), so each test here either re-states a Daimond test
//! against the Rust code or pins a value to the JavaScript it mirrors. The two oracle tables in
//! `tests/data` are generated by running `SECRET_RE` and `fingerprint` themselves (see
//! `tests/data/lens_oracle.mjs`), so a transcription error in the Rust cannot hide.

use oxedyne_fe2o3_core::prelude::*;
use oxedyne_fe2o3_jdat::{
    bdat::limits::DecodeLimits,
    prelude::*,
};
use oxedyne_fe2o3_net::{
    guard::floor::KeyFloor,
    lens::{
        compact,
        fingerprint,
        is_stamp,
        sanitise,
        secret_name,
        secret_name_loose,
        stamp,
        Deny,
        Gates,
        Posted,
        Redact,
        Refusal,
        Row,
        Shapes,
        Sink,
        StrTest,
    },
};
use oxedyne_fe2o3_text::{
    regex::Regex,
    secret,
};

use std::{
    fs,
    path::{
        Path,
        PathBuf,
    },
    sync::atomic::{
        AtomicU64,
        Ordering,
    },
    time::{
        Duration,
        SystemTime,
        UNIX_EPOCH,
    },
};


// Scratch directories ====================================================================

static SERIAL: AtomicU64 = AtomicU64::new(0);

/// A directory of its own, removed again when the test ends.
struct Scratch(PathBuf);

impl Scratch {
    fn new(tag: &str) -> Self {
        let n = SERIAL.fetch_add(1, Ordering::SeqCst);
        let dir = std::env::temp_dir().join(fmt!("lens-test-{}-{}-{}", std::process::id(), tag, n));
        let _ = fs::remove_dir_all(&dir);
        Self(dir)
    }
    fn dir(&self) -> PathBuf { self.0.join("lens") }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

const T0: u64 = 1_757_635_200_000; // A fixed instant, so rotated names are predictable.
const DAY: u64 = 86_400_000;

// Builders ===============================================================================

fn omap(kv: Vec<(&str, Dat)>) -> Dat {
    create_dat_ordmap(kv.into_iter().map(|(k, v)| (Dat::Str(k.to_string()), v)).collect())
}

fn st(s: &str) -> Dat { Dat::Str(s.to_string()) }

/// The member of a map at a dotted path, lists excluded.
fn at<'a>(d: &'a Dat, path: &str) -> Option<&'a Dat> {
    let mut cur = d;
    for seg in path.split('.') {
        cur = cur.map_get(&st(seg)).ok().flatten()?;
    }
    Some(cur)
}

fn text_of(d: &Dat) -> String {
    match d {
        Dat::Str(s) => s.clone(),
        other       => fmt!("<{:?}>", other),
    }
}

fn text_at(d: &Dat, path: &str) -> String {
    match at(d, path) {
        Some(Dat::Str(s)) => s.clone(),
        other => fmt!("<{:?}>", other),
    }
}

/// A trace body in Daimond's request shape, `{v, device, rows:[{ts, tag, data}]}`.
fn body(device: &str, rows: &[(i64, &str, &str)]) -> Vec<u8> {
    let j = |s: &str| Dat::Str(s.to_string()).json().unwrap_or_default();
    let list: Vec<String> = rows.iter()
        .map(|(ts, tag, data)| fmt!("{{\"ts\":{},\"tag\":{},\"data\":{}}}", ts, j(tag), j(data)))
        .collect();
    fmt!("{{\"v\":1,\"device\":{},\"rows\":[{}]}}", j(device), list.join(",")).into_bytes()
}

fn lines(path: &Path) -> Outcome<Vec<Dat>> {
    let text = res!(fs::read_to_string(path));
    let mut out = Vec::new();
    for line in text.lines() {
        out.push(res!(Dat::decode_json_strict(line, &DecodeLimits::default())));
    }
    Ok(out)
}

fn names(dir: &Path) -> Vec<String> {
    let mut v: Vec<String> = match fs::read_dir(dir) {
        Ok(rd) => rd.filter_map(|e| e.ok()).filter_map(|e| e.file_name().into_string().ok()).collect(),
        Err(_) => Vec::new(),
    };
    v.sort();
    v
}

fn all_bytes(dir: &Path) -> Outcome<Vec<u8>> {
    let mut out = Vec::new();
    for n in names(dir) {
        out.extend(res!(fs::read(dir.join(n))));
    }
    Ok(out)
}

fn has(hay: &[u8], needle: &str) -> bool {
    let n = needle.as_bytes();
    !n.is_empty() && hay.windows(n.len()).any(|w| w == n)
}

fn stored(p: Posted) -> usize {
    match p {
        Posted::Stored(n)   => n,
        Posted::Refused(r)  => panic!("expected the post to be stored, but it was refused: {:?}", r),
    }
}

fn refused(p: Posted) -> Refusal {
    match p {
        Posted::Refused(r)  => r,
        Posted::Stored(n)   => panic!("expected the post to be refused, but {} row(s) were stored", n),
    }
}

/// Pushes a live file past `max_file` so the next write rotates it.
fn overfill(sink: &Sink, key: &[&str]) -> Outcome<()> {
    res!(fs::create_dir_all(sink.dir()));
    res!(fs::write(sink.path(key), vec![b'x'; (sink.gates().max_file + 1) as usize]));
    Ok(())
}

fn small_gates() -> Gates {
    Gates { max_file: 600, ..Gates::default() }
}

fn rotated_name(stem: &str, at_ms: u64) -> String {
    fmt!("{}.ndjson.{}", stem, stamp(at_ms))
}

fn now_real_ms() -> u64 {
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_millis() as u64).unwrap_or(0)
}

// The envelope ===========================================================================

#[test]
fn the_row_envelope_is_daimonds_v_d_n_b_t() -> Outcome<()> {
    let row = Row::new("dev1", 7, "b1", T0, "console")
        .with("lvl", st("warn"))
        // The envelope wins over a payload key of the same name, as it does in `emit`.
        .with("n", Dat::U64(99))
        .with("t", Dat::U64(1))
        .with("x", Dat::U64(3));
    let j = res!(row.json());
    assert_eq!(j, fmt!(
        "{{\"v\":1,\"d\":\"dev1\",\"n\":7,\"b\":\"b1\",\"t\":{},\"lvl\":\"warn\",\"x\":3}}", T0));
    assert_eq!(row.tag(), "ev console");
    Ok(())
}

#[test]
fn a_small_row_is_not_trimmed() -> Outcome<()> {
    let row = Row::new("d", 1, "b", T0, "k").with("msg", st("short"));
    let j = res!(row.fit(360));
    assert_eq!(j, res!(row.json()));
    assert!(!j.contains("\"tr\""));
    Ok(())
}

#[test]
fn fit_trims_the_largest_string_and_marks_tr() -> Outcome<()> {
    let row = Row::new("dev1", 7, "b1", T0, "fetch.fail")
        .with("tool", st("bash"))
        .with("err", st(&"e".repeat(1000)));
    let j = res!(row.fit(360));
    assert!(j.len() <= 360, "the fitted event is {} bytes", j.len());
    let d = res!(Dat::decode_json_strict(&j, &DecodeLimits::default()));
    assert_eq!(text_at(&d, "tool"), "bash", "the short field must survive the trimming of the long one");
    let err = text_at(&d, "err");
    assert!(!err.is_empty() && err.len() < 1000 && "e".repeat(err.len()) == err);
    assert!(at(&d, "tr").is_some(), "tr must be present");
    assert!(j.ends_with(",\"tr\":1}"), "tr:1 is the last key: {}", j);
    // The envelope is never sacrificed.
    assert!(j.starts_with(&fmt!("{{\"v\":1,\"d\":\"dev1\",\"n\":7,\"b\":\"b1\",\"t\":{},", T0)));
    Ok(())
}

#[test]
fn fit_counts_bytes_and_still_converges_on_multibyte_text() -> Outcome<()> {
    // 200 characters of two bytes each are trimmed by characters, and the result is whole JSON.
    let row = Row::new("d", 1, "b", T0, "k").with("msg", st(&"é".repeat(200)));
    let j = res!(row.fit(360));
    assert!(j.len() <= 360, "{} bytes", j.len());
    let d = res!(Dat::decode_json_strict(&j, &DecodeLimits::default()));
    let msg = text_at(&d, "msg");
    assert!(!msg.is_empty() && msg.chars().count() < 200 && msg.chars().all(|c| c == 'é'), "{:?}", msg);
    // With 500 the excess in bytes is larger than the characters there are, so the field goes
    // whole, which is what `fit` in debugshare.js does too (`keep > 0` else `delete`).
    let row = Row::new("d", 1, "b", T0, "k").with("msg", st(&"é".repeat(500)));
    let j = res!(row.fit(360));
    assert!(j.len() <= 360, "{} bytes", j.len());
    let d = res!(Dat::decode_json_strict(&j, &DecodeLimits::default()));
    assert!(at(&d, "msg").is_none() && at(&d, "tr").is_some(), "{}", j);
    Ok(())
}

#[test]
fn fit_falls_back_to_the_bare_envelope() -> Outcome<()> {
    // Nothing here is a string, so nothing can be trimmed.
    let big = Dat::List((0..300).map(|i| Dat::U64(1_000_000 + i)).collect());
    let row = Row::new("dev1", 7, "b1", T0, "k").with("big", big);
    let j = res!(row.fit(360));
    assert_eq!(j, fmt!("{{\"v\":1,\"d\":\"dev1\",\"n\":7,\"b\":\"b1\",\"t\":{},\"tr\":1}}", T0));
    Ok(())
}

#[test]
fn an_entry_is_one_ndjson_line_carrying_the_row() -> Outcome<()> {
    let row = Row::new("dev1", 7, "b1", T0, "console").with("msg", st("a\nb\"c\\d"));
    let entry = res!(row.entry(360));
    assert_eq!(entry.ts, T0 as i64);
    assert_eq!(entry.tag, "ev console");
    let line = entry.line("devABC", T0 + 5);
    assert!(line.ends_with('\n'));
    assert_eq!(line.matches('\n').count(), 1, "a row is one line however its text is built");
    let d = res!(Dat::decode_json_strict(line.trim_end(), &DecodeLimits::default()));
    assert_eq!(at(&d, "bt").and_then(|x| x.get_i64()), Some((T0 + 5) as i64));
    assert_eq!(text_at(&d, "device"), "devABC");
    assert_eq!(at(&d, "ts").and_then(|x| x.get_i64()), Some(T0 as i64));
    assert_eq!(text_at(&d, "tag"), "ev console");
    // The data is the event's own JSON, which parses again to the same fields.
    let ev = res!(Dat::decode_json_strict(&text_at(&d, "data"), &DecodeLimits::default()));
    assert_eq!(text_at(&ev, "msg"), "a\nb\"c\\d");
    assert_eq!(text_at(&ev, "d"), "dev1");
    Ok(())
}

// The gates ==============================================================================

#[test]
fn the_gates_carry_daimonds_values_and_the_plans_defaults() {
    let d = Gates::daimond();
    assert_eq!(d.max_body, 256 * 1024);
    assert_eq!(d.max_rows, 1000);
    assert_eq!(d.max_tag, 64);
    assert_eq!(d.max_data, 400);
    assert_eq!(d.min_interval_ms, 2_000);
    assert_eq!(d.max_file, 2 * 1024 * 1024);
    assert_eq!(d.retain_days, 14);
    assert_eq!(d.max_rotated, 200);
    assert_eq!(d.max_total, u64::MAX, "Daimond bounds a device, not the directory");
    assert!(!d.sweep_idle);
    // The plan's defaults (§6): 2 MB files, 7 days or 20 files, 200 MB in all.
    let p = Gates::default();
    assert_eq!((p.max_body, p.max_rows, p.max_tag, p.max_data), (d.max_body, d.max_rows, d.max_tag, d.max_data));
    assert_eq!(p.min_interval_ms, d.min_interval_ms);
    assert_eq!(p.max_file, 2 * 1024 * 1024);
    assert_eq!(p.retain_days, 7);
    assert_eq!(p.max_rotated, 20);
    assert_eq!(p.max_total, 200 * 1024 * 1024);
    assert!(p.sweep_idle);
}

#[test]
fn an_authed_post_appends_a_file_the_operator_can_read() -> Outcome<()> {
    let s = Scratch::new("post");
    let sink = Sink::new(s.dir(), Gates::default());
    let b = body("devABC", &[
        (1000, "dispatch election", "self=aa nominee=bb PRESENT"),
        (1001, "collect CLAIMED", "turn=t1"),
    ]);
    assert_eq!(stored(res!(sink.post(&["acct-diag"], &b, T0))), 2);
    let path = s.dir().join("acct-diag.ndjson");
    assert_eq!(sink.path(&["acct-diag"]), path);
    let got = res!(lines(&path));
    assert_eq!(got.len(), 2);
    assert_eq!(text_at(&got[0], "tag"), "dispatch election");
    assert_eq!(text_at(&got[0], "data"), "self=aa nominee=bb PRESENT");
    assert_eq!(text_at(&got[0], "device"), "devABC");
    assert_eq!(at(&got[0], "bt").and_then(|x| x.get_i64()), Some(T0 as i64));
    assert_eq!(text_at(&got[1], "tag"), "collect CLAIMED");
    Ok(())
}

#[test]
fn a_body_over_the_cap_is_refused_413_and_writes_nothing() -> Outcome<()> {
    let s = Scratch::new("body");
    let sink = Sink::new(s.dir(), Gates::default());
    let mut b = body("d", &[(1, "t", "x")]);
    b.resize(sink.gates().max_body + 1, b' ');
    let r = refused(res!(sink.post(&["k"], &b, T0)));
    assert_eq!(r, Refusal::TooLarge);
    assert_eq!(r.status(), 413);
    assert_eq!(r.message(), "Diagnostic trace too large.");
    assert!(names(&s.dir()).is_empty(), "a refused body must not create a file");
    Ok(())
}

#[test]
fn a_body_exactly_at_the_cap_is_not_refused_for_size() -> Outcome<()> {
    let s = Scratch::new("bodyat");
    let sink = Sink::new(s.dir(), Gates::default());
    let mut b = body("d", &[(1, "t", "x")]);
    b.resize(sink.gates().max_body, b' ');
    assert_eq!(stored(res!(sink.post(&["k"], &b, T0))), 1);
    Ok(())
}

#[test]
fn more_rows_than_the_cap_are_refused_not_truncated() -> Outcome<()> {
    let s = Scratch::new("rows");
    let sink = Sink::new(s.dir(), Gates::default());
    let many: Vec<(i64, &str, &str)> = (0..1001).map(|i| (i as i64, "t", "x")).collect();
    let r = refused(res!(sink.post(&["k"], &body("d", &many), T0)));
    assert_eq!(r, Refusal::TooManyRows);
    assert_eq!(r.status(), 400);
    assert_eq!(r.message(), "Too many rows in one trace.");
    assert!(names(&s.dir()).is_empty(), "a disagreement is loud: nothing is written");
    // Exactly the cap is accepted, whole.
    assert_eq!(stored(res!(sink.post(&["k"], &body("d", &many[..1000]), T0))), 1000);
    assert_eq!(res!(lines(&sink.path(&["k"]))).len(), 1000);
    Ok(())
}

#[test]
fn a_body_with_no_rows_list_or_no_json_is_refused_400() -> Outcome<()> {
    let s = Scratch::new("shape");
    let sink = Sink::new(s.dir(), Gates::default());
    let r = refused(res!(sink.post(&["k"], br#"{"v":1,"device":"d"}"#, T0)));
    assert_eq!(r, Refusal::NoRows);
    assert_eq!(r.status(), 400);
    assert_eq!(r.message(), "A trace must carry a `rows` list.");
    let r = refused(res!(sink.post(&["k"], b"not json at all", T0 + 10_000)));
    assert!(matches!(r, Refusal::Malformed(_)));
    assert_eq!(r.status(), 400);
    let r = refused(res!(sink.post(&["k"], b"", T0 + 20_000)));
    assert!(matches!(r, Refusal::Malformed(_)));
    assert!(names(&s.dir()).is_empty());
    Ok(())
}

#[test]
fn a_tag_and_a_data_field_are_clipped_on_a_character_boundary() -> Outcome<()> {
    let s = Scratch::new("clip");
    let sink = Sink::new(s.dir(), Gates::default());
    let long_tag = "t".repeat(100);
    let long_data = "d".repeat(500);
    let wide = "é".repeat(300); // 600 bytes
    let b = body("d", &[(1, &long_tag, &long_data), (2, "wide", &wide)]);
    assert_eq!(stored(res!(sink.post(&["k"], &b, T0))), 2);
    let got = res!(lines(&sink.path(&["k"])));
    assert_eq!(text_at(&got[0], "tag").len(), 64);
    assert_eq!(text_at(&got[0], "data").len(), 400);
    let w = text_at(&got[1], "data");
    assert!(w.len() <= 400 && w.len() >= 398, "{} bytes", w.len());
    assert!(w.chars().all(|c| c == 'é'), "the clip must not cut a character");
    Ok(())
}

#[test]
fn a_row_cannot_forge_another_by_carrying_a_line_break() -> Outcome<()> {
    let s = Scratch::new("forge");
    let sink = Sink::new(s.dir(), Gates::default());
    let b = body("d", &[(1, "tag", "line1\n{\"forged\":1}\r\n\tend")]);
    assert_eq!(stored(res!(sink.post(&["k"], &b, T0))), 1);
    let text = res!(fs::read_to_string(sink.path(&["k"])));
    assert_eq!(text.matches('\n').count(), 1, "one row, one line: {:?}", text);
    let got = res!(lines(&sink.path(&["k"])));
    assert_eq!(text_at(&got[0], "data"), "line1 {\"forged\":1}   end");
    Ok(())
}

#[test]
fn a_row_with_no_tag_is_marked_not_dropped() -> Outcome<()> {
    let s = Scratch::new("malformed");
    let sink = Sink::new(s.dir(), Gates::default());
    let b = br#"{"v":1,"device":"d","rows":[{"ts":1},{"ts":2,"tag":"ok","data":"x"}]}"#;
    assert_eq!(stored(res!(sink.post(&["k"], b, T0))), 2);
    let got = res!(lines(&sink.path(&["k"])));
    assert_eq!(got.len(), 2);
    assert_eq!(text_at(&got[0], "tag"), "(malformed row)");
    assert_eq!(text_at(&got[1], "tag"), "ok");
    Ok(())
}

// The rate floor =========================================================================

#[test]
fn the_rate_floor_refuses_under_two_seconds_and_accepts_over() -> Outcome<()> {
    let s = Scratch::new("rate");
    let sink = Sink::new(s.dir(), Gates::default());
    let b = body("devR", &[(1, "pull", "x")]);
    assert_eq!(stored(res!(sink.post(&["acct-rate"], &b, T0))), 1);
    let r = refused(res!(sink.post(&["acct-rate"], &b, T0 + 1_500)));
    assert_eq!(r, Refusal::TooFast);
    assert_eq!(r.status(), 429);
    assert_eq!(r.message(), "Wait a moment before sharing again.");
    // The refusal did not hold the floor open: 2.5 s after the first is 1 s after the refusal.
    assert_eq!(stored(res!(sink.post(&["acct-rate"], &b, T0 + 2_500))), 1);
    // Exactly the interval is enough, as `now - last < MIN_INTERVAL_MS` is the refusal.
    assert_eq!(stored(res!(sink.post(&["acct-rate"], &b, T0 + 4_500))), 1);
    // Another key is another floor.
    assert_eq!(stored(res!(sink.post(&["acct-other"], &b, T0 + 4_600))), 1);
    assert_eq!(res!(lines(&sink.path(&["acct-rate"]))).len(), 3);
    Ok(())
}

#[test]
fn the_floor_is_keyed_by_the_session_key_never_by_the_body() -> Outcome<()> {
    let s = Scratch::new("bodykey");
    let sink = Sink::new(s.dir(), Gates::default());
    assert_eq!(stored(res!(sink.post(&["acct"], &body("devX", &[(1, "a", "x")]), T0))), 1);
    // The same session claiming another device in the body is still the same floor.
    let r = refused(res!(sink.post(&["acct"], &body("devY", &[(1, "a", "x")]), T0 + 100)));
    assert_eq!(r, Refusal::TooFast);
    // The body's device is a label on the line, and names no file.
    assert_eq!(names(&s.dir()), vec!["acct.ndjson".to_string()]);
    // A hostile label cannot walk out of the directory, or split a line.
    let h = body("../../etc/passwd\nx", &[(1, "a", "x")]);
    assert_eq!(stored(res!(sink.post(&["acct2"], &h, T0))), 1);
    assert_eq!(names(&s.dir()), vec!["acct.ndjson".to_string(), "acct2.ndjson".to_string()]);
    assert_eq!(res!(lines(&sink.path(&["acct2"]))).len(), 1);
    Ok(())
}

#[test]
fn the_key_floor_remembers_the_last_admitted_call_only() -> Outcome<()> {
    let f = KeyFloor::new(2_000);
    assert!(res!(f.admit("a", 10_000)));
    assert!(!res!(f.admit("a", 11_999)));
    assert!(!res!(f.admit("a", 11_999)), "a refusal leaves the record alone");
    assert!(res!(f.admit("a", 12_000)), "the interval itself is enough");
    assert!(res!(f.admit("b", 12_001)), "keys are independent");
    // A clock that steps back never underflows into a long refusal.
    assert!(!res!(f.admit("b", 1)));
    Ok(())
}

#[test]
fn the_key_floor_prunes_stale_keys_only_once_it_has_grown() -> Outcome<()> {
    let f = KeyFloor::new(2_000).with_ttl_ms(10_000).with_prune_at(3);
    for (i, k) in ["a", "b", "c"].iter().enumerate() {
        assert!(res!(f.admit(k, 1_000 + i as u64)));
    }
    // Three entries, at the bound, not past it: nothing is walked.
    assert!(res!(f.admit("d", 20_000)));
    // Now past the bound, and a, b, c are older than the time to live.
    assert!(res!(f.admit("e", 20_001)));
    assert_eq!(res!(f.len()), 2, "only d and e are younger than the time to live");
    Ok(())
}

// Hostile keys ===========================================================================

#[test]
fn a_key_is_reduced_to_a_safe_filename_alphabet() {
    assert_eq!(sanitise("acct_AB-12"), "acct_AB-12");
    assert_eq!(sanitise("../../etc/passwd"), "______etc_passwd");
    assert!(!sanitise("../../etc/passwd").contains('/'));
    assert_eq!(sanitise(""), "unknown");
    assert!(sanitise(&"x".repeat(100)).len() <= 48);
}

#[test]
fn a_hostile_key_cannot_escape_the_directory() -> Outcome<()> {
    let s = Scratch::new("escape");
    let sink = Sink::new(s.dir(), Gates::default());
    let p = sink.path(&["../../etc", "passwd"]);
    assert_eq!(p, s.dir().join("______etc-passwd.ndjson"));
    assert_eq!(stored(res!(sink.post(&["../../etc", "passwd"], &body("d", &[(1, "t", "x")]), T0))), 1);
    assert_eq!(names(&s.dir()), vec!["______etc-passwd.ndjson".to_string()]);
    // Daimond's key is account and device, each reduced on its own and joined by a hyphen.
    assert_eq!(sink.path(&["acct-diag", "devABC"]), s.dir().join("acct-diag-devABC.ndjson"));
    Ok(())
}

// Rotation ===============================================================================

#[test]
fn a_stamp_is_fixed_width_utc_and_sorts_as_a_string() {
    assert_eq!(stamp(0),          "19700101T000000Z");
    assert_eq!(stamp(86_399_000), "19700101T235959Z");
    assert_eq!(stamp(T0),         "20250912T000000Z");
    assert!(is_stamp(&stamp(T0)));
    assert!(!is_stamp("1"), "a pre-stamp `.log.1` suffix is not a stamp");
    assert!(!is_stamp("1970010 T000000Z"));
    assert!(stamp(0) < stamp(86_399_000));
}

#[test]
fn rotation_by_size_stamps_the_closed_file_and_starts_fresh() -> Outcome<()> {
    let s = Scratch::new("size");
    let sink = Sink::new(s.dir(), small_gates());
    let live = sink.path(&["acct"]);
    res!(fs::create_dir_all(s.dir()));
    // A file of exactly the cap is not past it.
    res!(fs::write(&live, vec![b'x'; 600]));
    assert_eq!(stored(res!(sink.post(&["acct"], &body("d", &[(1, "first", "a")]), T0))), 1);
    assert_eq!(names(&s.dir()), vec!["acct.ndjson".to_string()], "600 bytes is not over a cap of 600");
    // Now it is past the cap, so the next append closes it under the instant of the rotation.
    let rot_ms = T0 + 6_000;
    assert_eq!(stored(res!(sink.post(&["acct"], &body("d", &[(2, "after-rotate", "b")]), rot_ms))), 1);
    let rotated = s.dir().join(rotated_name("acct", rot_ms));
    assert!(rotated.exists(), "the oversized file should have rotated to a stamped name: {:?}", names(&s.dir()));
    let old = res!(fs::read_to_string(&rotated));
    assert!(old.contains("first"), "the rotated file must keep the history, not discard it");
    let fresh = res!(fs::read_to_string(&live));
    assert!(fresh.contains("after-rotate"));
    assert!(!fresh.contains("first"), "the fresh file must not hold pre-rotation content");
    Ok(())
}

#[test]
fn two_rotations_in_one_second_do_not_overwrite_each_other() -> Outcome<()> {
    let s = Scratch::new("collide");
    let sink = Sink::new(s.dir(), small_gates());
    let row = Row::new("d", 1, "b", T0, "k").with("m", st("x"));
    res!(sink.write(&["acct"], "dev", &[row.clone()], T0));
    res!(overfill(&sink, &["acct"]));
    res!(sink.write(&["acct"], "dev", &[row.clone()], T0 + 1_000));
    res!(overfill(&sink, &["acct"]));
    res!(sink.write(&["acct"], "dev", &[row.clone()], T0 + 1_000));
    let n = names(&s.dir());
    let first = rotated_name("acct", T0 + 1_000);
    assert!(n.contains(&first), "{:?}", n);
    assert!(n.contains(&fmt!("{}-1", first)), "an occupied stamp takes a -1 suffix: {:?}", n);
    Ok(())
}

#[test]
fn rotation_by_age_drops_the_over_age_files_and_leaves_the_rest() -> Outcome<()> {
    let s = Scratch::new("age");
    let sink = Sink::new(s.dir(), small_gates());
    let now = 40 * DAY;
    res!(fs::create_dir_all(s.dir()));
    let over_age = rotated_name("acct", now - 8 * DAY);   // Past the plan's 7 days.
    let in_age   = rotated_name("acct", now - 6 * DAY);
    let other    = rotated_name("other", now - 20 * DAY); // Past the age, and another key's.
    let other_in = rotated_name("other", now - 2 * DAY);
    for n in [&over_age, &in_age, &other, &other_in, &"acct.ndjson.1".to_string()] {
        res!(fs::write(s.dir().join(n), b"rotated\n"));
    }
    res!(overfill(&sink, &["acct"]));
    res!(sink.write(&["acct"], "dev", &[Row::new("d", 1, "b", now, "k")], now));
    let n = names(&s.dir());
    assert!(!n.contains(&over_age), "a rotation past retain_days should be gone: {:?}", n);
    assert!(n.contains(&in_age));
    // The sweep covers the directory, where Daimond's prune covered one device's files, because
    // a directory keyed by session grows a key at a time and the others never rotate again.
    assert!(!n.contains(&other), "another key's file past the age goes too: {:?}", n);
    assert!(n.contains(&other_in), "and one inside it stays");
    assert!(n.contains(&"acct.ndjson.1".to_string()), "a pre-stamp rotation is left alone");
    assert!(n.contains(&rotated_name("acct", now)), "the rotation that triggered the prune is kept");
    // Daimond's own age is 14 days, which keeps the 8-day-old file.
    let s2 = Scratch::new("age14");
    let sink2 = Sink::new(s2.dir(), Gates { max_file: 600, ..Gates::daimond() });
    res!(fs::create_dir_all(s2.dir()));
    res!(fs::write(s2.dir().join(&over_age), b"rotated\n"));
    res!(fs::write(s2.dir().join(rotated_name("acct", now - 15 * DAY)), b"rotated\n"));
    res!(overfill(&sink2, &["acct"]));
    res!(sink2.write(&["acct"], "dev", &[Row::new("d", 1, "b", now, "k")], now));
    let n2 = names(&s2.dir());
    assert!(n2.contains(&over_age), "an 8-day-old file is inside Daimond's 14 days: {:?}", n2);
    assert!(!n2.contains(&rotated_name("acct", now - 15 * DAY)));
    Ok(())
}

#[test]
fn rotation_by_count_keeps_the_newest_max_rotated() -> Outcome<()> {
    let s = Scratch::new("count");
    let sink = Sink::new(s.dir(), Gates { max_file: 600, max_rotated: 5, ..Gates::default() });
    let now = 40 * DAY;
    res!(fs::create_dir_all(s.dir()));
    // Seven rotations inside the age, a minute apart, newest first in `in_age`.
    let mut in_age = Vec::new();
    for k in 1..=7u64 {
        let n = rotated_name("acct", now - k * 60_000);
        res!(fs::write(s.dir().join(&n), b"rotated\n"));
        in_age.push(n);
    }
    res!(overfill(&sink, &["acct"]));
    res!(sink.write(&["acct"], "dev", &[Row::new("d", 1, "b", now, "k")], now));
    let n = names(&s.dir());
    // Eight rotations now stand (the seven and the one just made); five are kept, newest first.
    assert!(n.contains(&rotated_name("acct", now)));
    for kept in &in_age[..4] {
        assert!(n.contains(kept), "{} should survive: {:?}", kept, n);
    }
    for gone in &in_age[4..] {
        assert!(!n.contains(gone), "{} is over the count and should be gone: {:?}", gone, n);
    }
    assert!(n.contains(&"acct.ndjson".to_string()), "the live file is not a rotation");
    Ok(())
}

#[test]
fn the_total_cap_deletes_the_oldest_rotations_across_keys() -> Outcome<()> {
    let s = Scratch::new("total");
    let sink = Sink::new(s.dir(), Gates {
        max_file:   200,
        max_total:  3_000,
        max_rotated: 100,
        ..Gates::default()
    });
    let now = 40 * DAY;
    res!(fs::create_dir_all(s.dir()));
    let kb = vec![b'r'; 1_000];
    let order = [("a", 6), ("b", 5), ("a", 4), ("b", 3), ("a", 2)]; // Oldest first, in days back.
    let mut made = Vec::new();
    for (stem, back) in order {
        let n = rotated_name(stem, now - back * DAY / 2);
        res!(fs::write(s.dir().join(&n), &kb));
        made.push(n);
    }
    res!(overfill(&sink, &["c"]));
    res!(sink.write(&["c"], "dev", &[Row::new("d", 1, "b", now, "k")], now));
    let n = names(&s.dir());
    for gone in &made[..3] {
        assert!(!n.contains(gone), "{} is among the oldest and should be gone: {:?}", gone, n);
    }
    for kept in &made[3..] {
        assert!(n.contains(kept), "{} should survive: {:?}", kept, n);
    }
    assert!(n.contains(&rotated_name("c", now)));
    assert!(n.contains(&"c.ndjson".to_string()), "the file being written is never swept");
    let total: u64 = n.iter().map(|f| fs::metadata(s.dir().join(f)).map(|m| m.len()).unwrap_or(0)).sum();
    assert!(total <= 3_000, "{} bytes remain", total);
    Ok(())
}

#[test]
fn idle_live_files_age_out_when_the_gates_say_so() -> Outcome<()> {
    let now = now_real_ms();
    let make = |gates: Gates, tag: &str| -> Outcome<(Scratch, Sink)> {
        let s = Scratch::new(tag);
        let sink = Sink::new(s.dir(), gates);
        res!(fs::create_dir_all(s.dir()));
        for (name, back) in [("old.ndjson", 8 * DAY), ("fresh.ndjson", 3_600_000)] {
            let f = res!(fs::File::create(s.dir().join(name)));
            res!(f.set_modified(UNIX_EPOCH + Duration::from_millis(now - back)));
        }
        Ok((s, sink))
    };
    // A first row for a new key is what sets the sweep off.
    let (s, sink) = res!(make(Gates::default(), "idle"));
    assert_eq!(stored(res!(sink.post(&["new"], &body("d", &[(1, "t", "x")]), now))), 1);
    assert_eq!(names(&s.dir()), vec!["fresh.ndjson".to_string(), "new.ndjson".to_string()],
        "an idle file past retain_days goes, a recent one and the new one stay");
    // Daimond never swept a device that had gone quiet.
    let (s, sink) = res!(make(Gates::daimond(), "idle-daimond"));
    assert_eq!(stored(res!(sink.post(&["new"], &body("d", &[(1, "t", "x")]), now))), 1);
    assert_eq!(names(&s.dir()).len(), 3, "{:?}", names(&s.dir()));
    Ok(())
}

#[cfg(unix)]
#[test]
fn the_directory_is_created_0700_and_the_files_0600() -> Outcome<()> {
    use std::os::unix::fs::PermissionsExt;
    let s = Scratch::new("perm");
    let sink = Sink::new(s.dir(), Gates::default());
    assert_eq!(stored(res!(sink.post(&["k"], &body("d", &[(1, "t", "x")]), T0))), 1);
    let mode = |p: &Path| fs::metadata(p).map(|m| m.permissions().mode() & 0o777).unwrap_or(0);
    assert_eq!(mode(&s.dir()), 0o700);
    assert_eq!(mode(&sink.path(&["k"])), 0o600);
    // A directory that already exists, and is open to others, is closed.
    let s2 = Scratch::new("perm2");
    res!(fs::create_dir_all(s2.dir()));
    res!(fs::set_permissions(s2.dir(), fs::Permissions::from_mode(0o755)));
    let sink2 = Sink::new(s2.dir(), Gates::default());
    assert_eq!(stored(res!(sink2.post(&["k"], &body("d", &[(1, "t", "x")]), T0))), 1);
    assert_eq!(mode(&s2.dir()), 0o700);
    Ok(())
}

// The secret rule ========================================================================

#[test]
fn secret_name_is_secret_re_over_three_thousand_names() -> Outcome<()> {
    let table = res!(fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/lens_secret_re.tsv")));
    let mut n = 0;
    let mut hits = 0;
    for line in table.lines() {
        let cols: Vec<&str> = line.split('\t').collect();
        assert_eq!(cols.len(), 3, "bad oracle line {:?}", line);
        let (name, strict, loose) = (cols[0], cols[1] == "1", cols[2] == "1");
        assert_eq!(secret_name(name), strict, "SECRET_RE on {:?}", name);
        assert_eq!(secret_name_loose(name), loose, "SECRET_RE or SECRET_RE_LOOSE on {:?}", name);
        n += 1;
        if strict { hits += 1; }
    }
    assert!(n > 3_000, "the oracle holds {} names", n);
    assert!(hits > 500 && hits < n, "a table that is all one answer proves nothing: {} of {}", hits, n);
    Ok(())
}

#[test]
fn a_fingerprint_is_what_the_javascript_makes() -> Outcome<()> {
    let table = res!(fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/lens_fingerprint.tsv")));
    let red = Redact::new();
    let mut n = 0;
    for line in table.lines() {
        let (input, want) = match line.split_once('\t') {
            Some(p) => p,
            None => panic!("bad oracle line {:?}", line),
        };
        let want = text_of(&res!(Dat::decode_json_strict(want, &DecodeLimits::default())));
        let want = want.as_str();
        // Each input is JSON, so null and a number take the route a field value takes.
        let v = res!(Dat::decode_json_strict(input, &DecodeLimits::default()));
        let out = red.dat(&omap(vec![("secret", v.clone())]));
        assert_eq!(text_at(&out, "secret"), want, "fingerprint of {}", input);
        if let Dat::Str(s) = &v {
            assert_eq!(fingerprint(s, 6), want, "fingerprint() of {}", input);
        }
        n += 1;
    }
    assert!(n >= 20);
    Ok(())
}

#[test]
fn the_head_of_a_fingerprint_can_be_withheld() {
    let fp = fingerprint("hunter2hunter2", 0);
    assert!(fp.starts_with("[redacted …#") && fp.ends_with("/14]"), "{}", fp);
    assert!(!fp.contains("hunter"));
    assert_eq!(fingerprint("", 0), "[redacted:empty]");
    // The same hash whatever the head, so two occurrences of one secret still match.
    let a = fingerprint("hunter2hunter2", 6);
    assert_eq!(a.split('#').nth(1), fp.split('#').nth(1));
    // And a redactor can be set to withhold it everywhere.
    let r = Redact::new().with_head(0).dat(&omap(vec![("password", st("hunter2hunter2"))]));
    assert_eq!(text_at(&r, "password"), fp);
}

// The redactor ===========================================================================

#[test]
fn secret_named_fields_are_fingerprinted_at_any_depth() -> Outcome<()> {
    let d = omap(vec![
        ("a", omap(vec![("b", Dat::List(vec![
            omap(vec![("password", st("p1")), ("ok", st("fine"))]),
            st("a bare string in a list is not a field"),
        ]))])),
        ("token", omap(vec![("x", Dat::U64(1))])),    // A secret-named object is noted, not walked.
        ("key", Dat::List(vec![Dat::U64(1), Dat::U64(2)])),
        ("salt", Dat::U64(77)),
        ("n", Dat::U64(5)),
        ("apiKey", st("sk-live-abcdef")),
        ("gone", Dat::Opt(Box::new(None))),
        ("seed", Dat::Opt(Box::new(None))),
    ]);
    let r = Redact::new().dat(&d);
    assert_eq!(text_at(&r, "token"), "[redacted:object]");
    assert_eq!(text_at(&r, "key"), "[redacted:object]");
    assert_eq!(text_at(&r, "salt"), fingerprint("77", 6));
    assert_eq!(text_at(&r, "apiKey"), fingerprint("sk-live-abcdef", 6));
    assert_eq!(text_at(&r, "seed"), "[redacted:absent]");
    assert_eq!(at(&r, "n"), Some(&Dat::U64(5)));
    assert_eq!(at(&r, "gone"), Some(&Dat::Opt(Box::new(None))), "an empty field not named secret is left alone");
    let j = res!(compact(&r));
    assert!(!j.contains("\"p1\"") && !j.contains("sk-live-abcdef"), "{}", j);
    assert!(j.contains("\"ok\":\"fine\"") && j.contains("a bare string in a list"), "{}", j);
    Ok(())
}

#[test]
fn a_camel_cased_name_needs_the_loose_companion() -> Outcome<()> {
    let d = omap(vec![("pushToken", st("t0k3n-value")), ("tokenStats", Dat::U64(3)), ("note", st("n"))]);
    let strict = Redact::new().dat(&d);
    assert_eq!(text_at(&strict, "pushToken"), "t0k3n-value", "SECRET_RE misses a camel-joined name");
    let loose = Redact::new().loose().dat(&d);
    assert_eq!(text_at(&loose, "pushToken"), fingerprint("t0k3n-value", 6));
    assert_eq!(text_at(&loose, "tokenStats"), fingerprint("3", 6), "the loose pattern is boundary-free");
    assert_eq!(text_at(&loose, "note"), "n");
    Ok(())
}

#[test]
fn deny_names_and_paths_are_redacted_and_anchored_paths_stay_anchored() -> Outcome<()> {
    let red = Redact::new()
        .deny_name("durable")
        .deny(Deny::Path(vec!["state".to_string(), "wallet".to_string(), "coins".to_string()]))
        .deny_path(&["sess", "*", "nonce"]);
    let d = omap(vec![
        ("x", omap(vec![("durable", st("D1")), ("fine", st("F"))])),
        ("state", omap(vec![("wallet", omap(vec![("coins", st("C1")), ("name", st("w"))]))])),
        ("other", omap(vec![("state", omap(vec![("wallet", omap(vec![("coins", st("C2"))]))]))])),
        // A list is transparent to a path, so the elements are the object's own members.
        ("sess", Dat::List(vec![omap(vec![("a", omap(vec![("nonce", st("N1"))]))])])),
    ]);
    let r = red.dat(&d);
    assert_eq!(text_at(&r, "x.durable"), fingerprint("D1", 6));
    assert_eq!(text_at(&r, "x.fine"), "F");
    assert_eq!(text_at(&r, "state.wallet.coins"), fingerprint("C1", 6));
    assert_eq!(text_at(&r, "state.wallet.name"), "w");
    assert_eq!(text_at(&r, "other.state.wallet.coins"), "C2", "a path from the root does not match deeper down");
    let j = res!(compact(&r));
    assert!(j.contains(&fingerprint("N1", 6)) && !j.contains("\"N1\""), "{}", j);
    Ok(())
}

#[test]
fn a_caller_string_test_redacts_values_keys_and_list_members() -> Outcome<()> {
    let eight = "alpha bravo charlie delta echo foxtrot golf hotel";
    let seven = "alpha bravo charlie delta echo foxtrot golf";
    let red = Redact::new().with_test(|s: &str| s.split(' ').count() == 8);
    let d = omap(vec![
        ("msg", st(&fmt!("{} done", "boot"))),
        ("phrase", st(eight)),
        ("near", st(seven)),
        ("list", Dat::List(vec![st("x"), st(eight)])),
        ("nest", omap(vec![("deep", st(eight))])),
        (eight, st("a value under a key that is itself the phrase")),
    ]);
    let r = red.dat(&d);
    assert_eq!(text_at(&r, "phrase"), fingerprint(eight, 6));
    assert_eq!(text_at(&r, "near"), seven, "seven words are not the pattern");
    assert_eq!(text_at(&r, "msg"), "boot done");
    assert_eq!(text_at(&r, "nest.deep"), fingerprint(eight, 6));
    let j = res!(compact(&r));
    assert!(!j.contains(eight), "the phrase survives somewhere: {}", j);
    assert!(j.contains(&fingerprint(eight, 6)));
    Ok(())
}

#[test]
fn the_walk_is_bounded_and_a_marker_stands_where_it_stops() -> Outcome<()> {
    let mut d = omap(vec![("leaf", st("DEEP-PLANT"))]);
    for _ in 0..45 {
        d = omap(vec![("n", d)]);
    }
    let r = Redact::new().dat(&d);
    let j = res!(compact(&r));
    assert!(j.contains("[redacted:cycle-or-deep]"), "{}", j);
    assert!(!j.contains("DEEP-PLANT"));
    Ok(())
}

#[test]
fn redacting_twice_does_not_fingerprint_a_fingerprint() -> Outcome<()> {
    let d = omap(vec![("passphrase", st("correct horse")), ("n", Dat::U64(1))]);
    let red = Redact::new();
    let once = red.dat(&d);
    let (twice, changed) = red.walk(&once);
    assert_eq!(res!(compact(&once)), res!(compact(&twice)));
    assert!(!changed, "a marker already in place is not a change");
    let (_, changed) = red.walk(&d);
    assert!(changed);
    let (_, changed) = red.walk(&omap(vec![("ok", st("fine"))]));
    assert!(!changed);
    Ok(())
}

// Nothing planted reaches a byte =========================================================

const PHRASE: &str = "abandon ability able about above absent absorb abstract";

/// Does the text hold eight lowercase words in a row? Oxegen's own test asks the same of the EFF list.
fn eight_words(s: &str) -> bool {
    let w: Vec<bool> = s.split(' ')
        .map(|x| !x.is_empty() && x.chars().all(|c| c.is_ascii_lowercase()))
        .collect();
    w.windows(8).any(|win| win.iter().all(|&b| b))
}

#[test]
fn a_planted_secret_is_absent_from_every_byte_written() -> Outcome<()> {
    let plants = [
        "PLANT-passphrase-1", "PLANT-wallet-seedling-2", "PLANT-durable-3", "PLANT-token-4",
        "PLANT-apikey-5", "PLANT-listmember-6",
    ];
    let s = Scratch::new("planted");
    let sink = Sink::new(s.dir(), Gates { max_file: 900, ..Gates::default() })
        .with_redact(Redact::new()
            .deny_name("durable_blob")
            .deny_path(&["state", "wallet", "seedling"])
            .with_test(eight_words));
    let dev = "peer";
    // The typed door: rows built in process, as the peer's own taps will.
    for i in 0..12u64 {
        let row = Row::new(dev, i, "b1", T0 + i, "state")
            .with("auth", omap(vec![("passphrase", st(plants[0])), ("user", st("ann"))]))
            .with("state", omap(vec![("wallet", omap(vec![("seedling", st(plants[1])), ("open", Dat::Bool(true))]))]))
            .with("durable_blob", st(plants[2]))
            .with("console", st(&fmt!("boot {} done", PHRASE)))
            .with("list", Dat::List(vec![st("x"), st(PHRASE)]))
            .with("tokenStats", Dat::U64(5));
        assert_eq!(res!(sink.write(&["sid-1"], dev, &[row], T0 + 1_000 * i)), 1);
    }
    // The posted door: a client's batch, whose events are JSON inside a string.
    let ev = fmt!(
        "{{\"v\":1,\"d\":\"dev1\",\"n\":1,\"b\":\"b\",\"t\":1,\"token\":\"{}\",\"nested\":{{\"api_key\":\"{}\",\"list\":[\"{}\"],\"keep\":\"kept\"}}}}",
        plants[3], plants[4], PHRASE);
    let text_row = fmt!("saw {} in a plain text row", PHRASE);
    for i in 0..6i64 {
        let b = body("devX", &[(i, "ev console", &ev), (i, "diag", &text_row)]);
        assert_eq!(stored(res!(sink.post(&["sid-2"], &b, T0 + 3_000 * i as u64))), 2);
    }
    // An event whose data is no JSON cannot be examined by name, so it is not kept.
    let broken = fmt!("{{\"token\":\"{}\" oops", plants[5]);
    assert_eq!(stored(res!(sink.post(&["sid-2"], &body("devX", &[(1, "ev broken", &broken)]), T0 + 60_000))), 1);

    let n = names(&s.dir());
    assert!(n.iter().any(|f| f.contains(".ndjson.2025")), "the run must have rotated at least once: {:?}", n);
    let bytes = res!(all_bytes(&s.dir()));
    for p in plants.iter().chain([PHRASE, "abandon"].iter()) {
        assert!(!has(&bytes, p), "{:?} reached the disk", p);
    }
    // Not vacuous: the rows are there, with the markers and the innocent fields.
    assert!(has(&bytes, "ann") && has(&bytes, "kept") && has(&bytes, "tokenStats"));
    assert!(has(&bytes, &fingerprint(PHRASE, 6)) || has(&bytes, "[redacted"), "markers are expected");
    assert!(has(&bytes, &fingerprint(plants[0], 6)), "the passphrase's fingerprint is expected");

    // The control: the same fields written without the sink do carry the plants, so a pass above
    // is the redactor's doing and not a search that cannot see.
    let raw = res!(Row::new(dev, 0, "b1", T0, "state")
        .with("auth", omap(vec![("passphrase", st(plants[0]))]))
        .with("durable_blob", st(plants[2]))
        .with("console", st(&fmt!("boot {} done", PHRASE)))
        .entry(4096)).line(dev, T0);
    for p in [plants[0], plants[2], PHRASE] {
        assert!(has(raw.as_bytes(), p), "the control line should hold {:?}: {}", p, raw);
    }
    Ok(())
}


// The stock string test ==================================================================

// One credential of each shape `fe2o3_text::secret` knows, in two pieces joined at run time, so
// that the scanners that read this file find nothing in it to refuse.
const SHAPED: &[(&str, &str)] = &[
    ("fw",          "_3ZjKq81mAbCdEfGhIjKlMnOpQrSt"),
    ("sk-ant",      "-api03-AbCdEfGhIjKlMnOpQrStUvWx"),
    ("sk-proj",     "-AbCdEfGhIjKlMnOpQrStUvWxYz01"),
    ("sk-or",       "-v1-0123456789abcdef0123456789abcdef"),
    ("sk-",         "AbCdEfGhIjKlMnOpQrStUvWxYz0123456789"),
    ("AKIA",        "IOSFODNN7EXAMPLE"),
    ("ghp",         "_AbCdEfGhIjKlMnOpQrStUvWxYz0123456789"),
    ("github_pat",  "_11ABCDEFG0AbCdEfGhIjKlMnOpQrStUvWxYz0123456789"),
    ("xoxb",        "-1234567890-abcdefghij"),
    ("sk_live",     "_AbCdEfGhIjKlMnOpQrStUv"),
    ("AIza",        "SyA0123456789abcdefghijklmnopqrstuv"),
    ("-----BEGIN ", "OPENSSH PRIVATE KEY-----"),
];

fn cred(i: usize) -> String {
    fmt!("{}{}", SHAPED[i].0, SHAPED[i].1)
}

#[test]
fn shapes_cover_each_credential_shape_whole_and_leave_prose_alone() -> Outcome<()> {
    // Head 0, so that no character of a credential stands in its own fingerprint.
    let red = Redact::new().with_head(0).with_test(Shapes);
    for i in 0..SHAPED.len() {
        let c = cred(i);
        let doc = omap(vec![
            ("alone", st(&c)),
            ("note",  st(&fmt!("deployed with {} this morning", c))),
            ("list",  Dat::List(vec![st("fine"), st(&fmt!("k={}\n", c))])),
            ("deep",  omap(vec![("x", omap(vec![("y", st(&fmt!("a\nb {} c\nd", c)))]))])),
        ]);
        let out = red.dat(&doc);
        let json = res!(compact(&out));
        assert!(!json.contains(&c), "{:?} survived the redactor: {}", SHAPED[i].0, json);
        for p in ["alone", "note", "deep.x.y"] {
            assert!(text_at(&out, p).starts_with("[redacted"), "{} for {:?}: {:?}", p, SHAPED[i].0, text_at(&out, p));
        }
        assert!(json.contains("fine"), "the innocent list member stays: {}", json);
    }
    // An assigned literal under a secret-looking name is a shape too.
    let lit = fmt!("password = \"{}{}\"", "9f3Bq7", "ZmR4tYuIoPkLjHgFdS");
    assert!(Shapes.hit(&lit));
    for ok in [
        "the quick brown fox", "sk-nope", "skip-tracing and key lore", "AKIA", "fw_short",
        "an api_key = \"\" field", "key = \"your-key-here\"", "", "ghp_tooshort",
    ] {
        assert!(!Shapes.hit(ok), "{:?} is not a credential", ok);
    }
    Ok(())
}

#[test]
fn a_marker_and_a_nul_do_not_excuse_a_credential_in_a_feed() -> Outcome<()> {
    let k = cred(0);
    // `scan` is a file reader and takes the author's word; the control shows it does.
    let excused = [
        fmt!("{} # {}", k, secret::MARKER),
        fmt!("{}\n{}", secret::MARKER, k),
        fmt!("\0{}", k),
    ];
    for t in &excused {
        assert!(secret::scan(t.as_bytes()).is_empty(), "scan should excuse {:?}", t);
        assert!(secret::holds(t), "holds must not excuse {:?}", t);
        assert!(Shapes.hit(t), "Shapes must not excuse {:?}", t);
    }
    // And the same through both doors of a sink: nothing of the key reaches a byte.
    let s = Scratch::new("holds");
    let sink = Sink::new(s.dir(), Gates::default())
        .with_redact(Redact::new().with_head(0).with_test(Shapes));
    let row = Row::new("peer", 1, "b", T0, "console")
        .with("line", st(&excused[0]))
        .with("other", st(&excused[2]));
    assert_eq!(res!(sink.write(&["sid"], "peer", &[row], T0)), 1);
    let ev = fmt!("{{\"v\":1,\"d\":\"x\",\"n\":1,\"b\":\"b\",\"t\":1,\"line\":\"{}\"}}", excused[0]);
    let b = body("devX", &[(1, "ev console", &ev), (2, "diag", &excused[1])]);
    assert_eq!(stored(res!(sink.post(&["sid2"], &b, T0 + 5_000))), 2);
    let bytes = res!(all_bytes(&s.dir()));
    assert!(!has(&bytes, &k), "the key reached the disk");
    assert!(has(&bytes, "[redacted"), "markers are expected");
    Ok(())
}

#[test]
fn secret_name_agrees_with_the_regex_engine_on_every_ascii_name() -> Outcome<()> {
    // The hand matcher stands for the JavaScript, whose `\b` and `/i` are ASCII-only. On ASCII
    // names the crate's own engine, which follows the `regex` crate, must say the same.
    let re = res!(Regex::new(
        r"(?i)(?:^|[_.-])(?:apikey|api_key|key|token|secret|passphrase|password|salt|wrapped|wrappedpriv|sealed|seal|privatekey|priv|mnemonic|seed|masterkey)(?:$|[_.-]|enc\b)"));
    let table = res!(fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/lens_secret_re.tsv")));
    let mut n = 0;
    for line in table.lines() {
        let name = line.split('\t').next().unwrap_or("");
        if !name.is_ascii() {
            continue;
        }
        assert_eq!(secret_name(name), res!(re.is_match(name)), "on {:?}", name);
        n += 1;
    }
    assert!(n > 2_500, "only {} ASCII names were compared", n);
    Ok(())
}


// The content scrubber ===================================================================

// `tests/data/lens_scrub.tsv` holds each input of the JavaScript scrubber as a recipe and never as a
// credential, so that nothing paste-able is in the repository. `{{n:seed:alphabet}}` is n
// characters: the state starts at `seed * 2654435761` mod 2^32, each character steps it by
// `h * 1103515245 + 12345` in u32 wrapping arithmetic and takes `alphabet[(h >> 16) mod len]`.
// `{{dash5}}` is five hyphens.

fn alphabet(name: &str) -> &'static str {
    match name {
        "alnum"     => "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
        "hex"       => "0123456789abcdef",
        "b64"       => "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
        "b64std"    => "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/+",
        "upper36"   => "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
        "digit"     => "0123456789",
        other       => panic!("no alphabet {:?}", other),
    }
}

/// `n` characters of one alphabet, from one seed.
fn run(n: usize, seed: u32, alpha: &str) -> String {
    let a: Vec<char> = alphabet(alpha).chars().collect();
    let mut h = (seed as u64 * 2_654_435_761u64) as u32;
    let mut s = String::new();
    for _ in 0..n {
        h = h.wrapping_mul(1_103_515_245).wrapping_add(12_345);
        s.push(a[((h >> 16) as usize) % a.len()]);
    }
    s
}

/// A template of the table, with its recipes expanded.
fn expand(t: &str) -> Outcome<String> {
    let mut out = String::new();
    let mut rest = t;
    while let Some(i) = rest.find("{{") {
        out.push_str(&rest[..i]);
        let tail = &rest[i + 2..];
        let j = res!(tail.find("}}").ok_or_else(|| err!("An unclosed recipe in {:?}.", t; Invalid, Input)));
        let body = &tail[..j];
        if body == "dash5" {
            out.push_str("-----");
        } else {
            let p: Vec<&str> = body.split(':').collect();
            if p.len() != 3 {
                return Err(err!("The recipe {:?} is not n:seed:alphabet.", body; Invalid, Input));
            }
            out.push_str(&run(res!(p[0].parse::<usize>()), res!(p[1].parse::<u32>()), p[2]));
        }
        rest = &tail[j + 2..];
    }
    out.push_str(rest);
    Ok(out)
}

struct Case {
    template:   String,
    input:      String,     // the template, expanded
    want:       String,     // what the JavaScript made of it
    id:         bool,       // scrubbed as a correlation id, so with no entropy catch
}

fn scrub_cases() -> Outcome<Vec<Case>> {
    let table = res!(fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/lens_scrub.tsv")));
    let mut cases = Vec::new();
    for line in table.lines() {
        let cols: Vec<&str> = line.split('\t').collect();
        assert_eq!(cols.len(), 3, "bad oracle line {:?}", line);
        let template = text_of(&res!(Dat::decode_json_strict(cols[0], &DecodeLimits::default())));
        let want = text_of(&res!(Dat::decode_json_strict(cols[1], &DecodeLimits::default())));
        let input = res!(expand(&template));
        cases.push(Case { template, input, want, id: cols[2] == "1" });
    }
    Ok(cases)
}

#[test]
fn the_expander_gives_the_pinned_vectors() -> Outcome<()> {
    // The port is held to the JavaScript's before it is trusted with the table.
    for (t, want) in [
        ("{{8:1:hex}}",     "8388dbc2"),
        ("{{12:7:alnum}}",  "Dn8QmkIRy6vU"),
        ("{{10:3:digit}}",  "0086285001"),
        ("{{6:5:upper36}}", "PJMEIR"),
        ("a{{dash5}}b",     "a-----b"),
    ] {
        assert_eq!(res!(expand(t)), want, "{}", t);
    }
    Ok(())
}

#[test]
fn shapes_scrub_the_javascripts_table_to_the_same_text() -> Outcome<()> {
    let cases = res!(scrub_cases());
    assert_eq!(cases.len(), 130, "the table has changed size");
    let mut changed = 0;
    for c in &cases {
        let got = Shapes.scrub(&c.input, c.id);
        assert_eq!(got, c.want, "recipe {:?}", c.template);
        // A second pass finds nothing in the markers of the first.
        assert_eq!(Shapes.scrub(&got, c.id), got, "not idempotent, recipe {:?}", c.template);
        if got != c.input {
            changed += 1;
        }
    }
    let unchanged = cases.len() - changed;
    assert!(changed >= 100 && unchanged >= 20,
        "a table that is nearly one answer proves little: {} changed, {} not", changed, unchanged);
    // Every shape, every pair and the entropy catch is exercised.
    for kind in [
        "pem", "gh", "ghpat", "stripe", "whsec", "sk", "aws", "gcp", "slack", "jwt", "tune",
        "bearer", "urlarg", "named", "awssec", "hi",
    ] {
        let tag = fmt!("[redacted {} #", kind);
        assert!(cases.iter().any(|c| c.want.contains(&tag)), "no case yields {:?}", kind);
    }
    Ok(())
}

#[test]
fn a_hit_is_a_string_the_scrubber_would_change() -> Outcome<()> {
    for c in res!(scrub_cases()) {
        let changed = c.want != c.input;
        let hit = if c.id { Shapes.hit_id(&c.input) } else { Shapes.hit(&c.input) };
        assert_eq!(hit, changed, "recipe {:?}", c.template);
        // What the scrubber wrote is not a hit, so a row the client already scrubbed passes the
        // redactor with its own bytes.
        let again = if c.id { Shapes.hit_id(&c.want) } else { Shapes.hit(&c.want) };
        assert!(!again, "the output of recipe {:?} is itself a hit", c.template);
        let red = Redact::new().with_test(Shapes);
        let (out, covered) = red.walk(&omap(vec![(if c.id { "callId" } else { "msg" }, st(&c.want))]));
        assert!(!covered, "recipe {:?} was covered a second time: {:?}", c.template, out);
    }
    Ok(())
}

#[test]
fn the_shapes_the_commit_hook_does_not_know_are_caught_and_its_scan_is_unchanged() -> Outcome<()> {
    // Each is Daimond's and not the hook's, built from recipes so that no literal is in this file.
    let jwt = fmt!("eyJ{}.{}.{}", run(8, 301, "b64"), run(12, 302, "b64"), run(6, 303, "b64"));
    let cases = [
        ("a JWT",                   jwt),
        ("a webhook secret",        fmt!("whsec_{}", run(20, 304, "alnum"))),
        ("a test-mode Stripe key",  fmt!("sk_test_{}", run(14, 305, "alnum"))),
        ("a test-mode restricted",  fmt!("rk_test_{}", run(14, 306, "alnum"))),
        ("a relay key",             fmt!("tune-{}", run(32, 307, "hex"))),
        ("a temporary AWS id",      fmt!("ASIA{}", run(14, 308, "upper36"))),
        ("a role AWS id",           fmt!("AROA{}", run(14, 309, "upper36"))),
        ("a short GitHub run",      fmt!("ghp_{}", run(16, 310, "alnum"))),
        ("a new Slack token",       fmt!("xoxe-{}", run(14, 311, "alnum"))),
        ("a short Google key",      fmt!("AIza{}", run(32, 312, "b64"))),
        ("an `sk-` key of 16",      fmt!("sk-{}", run(16, 313, "b64"))),
        ("a bearer header",         fmt!("Authorization: Bearer {}", run(20, 314, "b64"))),
        ("a URL's token",           fmt!("https://h.example/cb?token={}&z=1", run(12, 315, "alnum"))),
        ("a named secret",          fmt!("config password: {}", run(12, 316, "alnum"))),
        ("an unnamed blob",         fmt!("blob {} end", run(40, 317, "b64"))),
    ];
    for (what, text) in &cases {
        assert!(secret::scan(text.as_bytes()).is_empty(), "the hook would now refuse {}: {:?}", what, text);
        assert!(!secret::holds(text), "holds, which is the hook's shapes, now sees {}", what);
        assert!(Shapes.hit(text), "Shapes misses {}: {:?}", what, text);
        assert_ne!(Shapes.scrub(text, false), *text, "scrub misses {}", what);
        let out = Redact::new().with_head(0).with_test(Shapes).dat(&omap(vec![("msg", st(text))]));
        assert!(text_at(&out, "msg").starts_with("[redacted"), "{}: {:?}", what, text_at(&out, "msg"));
    }
    Ok(())
}

#[test]
fn a_placeholder_under_a_secret_name_is_scrubbed_as_daimond_scrubs_it() -> Outcome<()> {
    // The hook excuses a placeholder, being noisy over source; Daimond's scrubber does not, being
    // over a feed, and `Shapes` is no weaker than it.
    let t = "password: \"your-key-here\"";
    assert!(secret::scan(t.as_bytes()).is_empty() && !secret::holds(t));
    assert!(Shapes.hit(t));
    assert!(Shapes.scrub(t, false).starts_with("password: \"[redacted named #"));
    Ok(())
}

#[test]
fn a_correlation_id_is_excused_from_the_entropy_catch_and_nothing_else() -> Outcome<()> {
    let blob = run(40, 401, "b64");
    let key = fmt!("sk-{}", run(20, 402, "b64"));
    let doc = omap(vec![
        ("callId",  st(&blob)),
        ("note",    st(&blob)),
        ("id",      st(&key)),
        ("sid",     st(&blob)),
        ("inner",   omap(vec![("turn", st(&blob)), ("x", st(&blob))])),
    ]);
    let red = Redact::new().with_test(Shapes);
    let out = red.dat(&doc);
    assert_eq!(text_at(&out, "callId"), blob, "Daimond's own id fields keep their values");
    assert!(text_at(&out, "note").starts_with("[redacted"), "any other field is held to the catch");
    assert!(text_at(&out, "id").starts_with("[redacted"), "an id holding a key is still a key");
    assert!(text_at(&out, "sid").starts_with("[redacted"), "sid is the application's to name");
    assert_eq!(text_at(&out, "inner.turn"), blob, "at any depth");
    assert!(text_at(&out, "inner.x").starts_with("[redacted"), "an id does not excuse its neighbour");
    // The application names its own, and a list under an id field is ids as well.
    let red = Redact::new().with_test(Shapes).id_key("sid");
    let out = red.dat(&omap(vec![
        ("sid",     st(&blob)),
        ("turn",    Dat::List(vec![st(&blob), st(&blob)])),
        ("other",   Dat::List(vec![st(&blob)])),
    ]));
    assert_eq!(text_at(&out, "sid"), blob);
    let j = res!(compact(&out));
    assert_eq!(j.matches(&blob).count(), 3, "two list members under turn, and sid: {}", j);
    assert!(j.contains("[redacted"), "the list under another name is still covered: {}", j);
    // A row meets the same rule through its payload's field names.
    let row = Row::new("peer", 1, "b", T0, "console").with("callId", st(&blob)).with("msg", st(&blob));
    let out = red.row(&row);
    let get = |n: &str| out.body.iter().find(|(k, _)| k == n).map(|(_, v)| text_of(v)).unwrap_or_default();
    assert_eq!(get("callId"), blob);
    assert!(get("msg").starts_with("[redacted"), "{:?}", get("msg"));
    // And a caller's own test is not excused for an id: the default is the same answer.
    let own = Redact::new().with_test(|s: &str| s.contains("zzz"));
    let out = own.dat(&omap(vec![("callId", st("a zzz b"))]));
    assert!(text_at(&out, "callId").starts_with("[redacted"));
    Ok(())
}


// The tap on a websocket's messages ======================================================

#[cfg(feature = "async")]
mod tap {
    use super::*;

    use oxedyne_fe2o3_iop_db::api::NoDatabase;
    use oxedyne_fe2o3_net::{
        lens::{
            Dir,
            Frame,
            Tap,
        },
        ws::{
            encode_message,
            handler::WebSocketEchoHandler,
            read_message,
            tap::{
                encode_message_tapped,
                read_message_tapped,
                FrameTap,
                NoTap,
            },
            WebSocket,
            WebSocketLimits,
            WebSocketMessage,
        },
    };

    use std::sync::Arc;

    use tokio::io::{
        duplex,
        AsyncWriteExt,
    };

    const CHUNK: usize = 1_024;

    /// What a connection knows about itself, which is what a filter gets to see.
    struct Conn {
        sid:    String,
        dev:    String,
    }

    fn conn(sid: &str) -> Conn {
        Conn { sid: sid.to_string(), dev: "peer".to_string() }
    }

    /// The safe filter: every frame, reduced to its kind and its size.
    fn shape_only(_dir: Dir, c: &Conn, msg: &WebSocketMessage) -> Option<Frame> {
        Some(Frame::new(&[&c.sid], &c.dev).shape(msg))
    }

    fn num_at(d: &Dat, path: &str) -> Option<u64> {
        match at(d, path)? {
            Dat::U8(n)  => Some(*n as u64),
            Dat::U16(n) => Some(*n as u64),
            Dat::U32(n) => Some(*n as u64),
            Dat::U64(n) => Some(*n),
            Dat::I8(n)  => u64::try_from(*n).ok(),
            Dat::I16(n) => u64::try_from(*n).ok(),
            Dat::I32(n) => u64::try_from(*n).ok(),
            Dat::I64(n) => u64::try_from(*n).ok(),
            _           => None,
        }
    }

    /// The events a key holds, each the JSON a row carried in its `data`.
    fn events<T: StrTest>(sink: &Sink<T>, key: &[&str]) -> Outcome<Vec<Dat>> {
        let mut out = Vec::new();
        for l in res!(lines(&sink.path(key))) {
            out.push(res!(Dat::decode_json_strict(&text_at(&l, "data"), &DecodeLimits::default())));
        }
        Ok(out)
    }

    fn text(s: &str) -> WebSocketMessage { WebSocketMessage::Text(s.to_string()) }

    /// Frames a message as a client would, masked.
    fn from_client(m: &WebSocketMessage) -> Outcome<Vec<u8>> {
        encode_message(m, true, CHUNK, CHUNK)
    }

    /// One tapped read.
    async fn read_one<X: FrameTap>(bytes: &[u8], tap: &X, ctx: &X::Ctx) -> Outcome<Option<WebSocketMessage>> {
        let mut stream = bytes;
        let mut buf = Vec::new();
        read_message_tapped(&mut stream, &mut buf, CHUNK, WebSocketLimits::default(), tap, ctx).await
    }

    #[tokio::test]
    async fn frames_in_both_directions_reach_the_sink_as_kind_and_size_only() -> Outcome<()> {
        let s = Scratch::new("tap-both");
        let sink = Arc::new(Sink::new(s.dir(), Gates::default()));
        let tap = Tap::new(sink.clone(), "b9", shape_only);
        let c = conn("sess-1");

        // In: a text frame, then a binary one, then a ping.
        let secret_text = "do-not-keep-this-chat-line";
        let got = res!(read_one(&res!(from_client(&text(secret_text))), &tap, &c).await);
        assert!(matches!(got, Some(WebSocketMessage::Text(ref t)) if t == secret_text));
        let got = res!(read_one(&res!(from_client(&WebSocketMessage::Binary(vec![7u8; 300]))), &tap, &c).await);
        assert!(matches!(got, Some(WebSocketMessage::Binary(ref b)) if b.len() == 300));
        res!(read_one(&res!(from_client(&WebSocketMessage::Ping(vec![1, 2, 3]))), &tap, &c).await);

        // Out: a text reply and a close, framed unmasked as a server does.
        let out = res!(encode_message_tapped(&text("pong!"), false, CHUNK, CHUNK, &tap, &c));
        assert_eq!(out, res!(encode_message(&text("pong!"), false, CHUNK, CHUNK)));
        res!(encode_message_tapped(&WebSocketMessage::Close(None, Some("bye".to_string())), false, CHUNK, CHUNK, &tap, &c));

        let ev = res!(events(&sink, &["sess-1"]));
        assert_eq!(ev.len(), 5, "{:?}", ev);
        let want = [
            ("frame.in", "text",   secret_text.len() as u64),
            ("frame.in", "binary", 300),
            ("frame.in", "ping",   3),
            ("frame.out", "text",  5),
            ("frame.out", "close", 3),
        ];
        for (i, (kind, op, bytes)) in want.iter().enumerate() {
            let e = &ev[i];
            assert_eq!(num_at(e, "n"), Some(i as u64 + 1), "n counts from 1, as Daimond's does: {:?}", e);
            assert_eq!(text_at(e, "d"), "peer");
            assert_eq!(text_at(e, "b"), "b9");
            assert_eq!(text_at(e, "op"), *op, "{:?}", e);
            assert_eq!(num_at(e, "bytes"), Some(*bytes), "{:?}", e);
            // The tag carries the direction.
            let tag = text_at(&res!(lines(&sink.path(&["sess-1"])))[i], "tag");
            assert_eq!(tag, fmt!("ev {}", kind));
        }
        // The default arm never carried content.
        let bytes = res!(all_bytes(&s.dir()));
        assert!(!has(&bytes, secret_text), "a frame's text reached the file");
        assert_eq!(tap.lost(), 0);
        Ok(())
    }

    #[tokio::test]
    async fn the_filters_reduction_is_what_lands_and_a_forgetful_filter_meets_the_redactor() -> Outcome<()> {
        let s = Scratch::new("tap-reduce");
        let sink = Arc::new(Sink::new(s.dir(), Gates::default())
            .with_redact(Redact::new().with_head(0)));
        // Oxegen's case: an enrol bundle carries a biometric, and only its shape may be kept.
        let filter = |dir: Dir, c: &Conn, msg: &WebSocketMessage| -> Option<Frame> {
            let t = match msg {
                WebSocketMessage::Text(t)   => t,
                _                           => return Some(Frame::new(&[&c.sid], &c.dev).shape(msg)),
            };
            let d = match Dat::decode_json_strict(t, &DecodeLimits::default()) {
                Ok(d)   => d,
                Err(_)  => return None,
            };
            let kind = text_at(&d, "kind");
            if kind == "EnrolBundle" {
                return Some(Frame::new(&[&c.sid], &c.dev)
                    .with("kind", st(&kind))
                    .with("bundle", st(&text_at(&d, "bundle")))
                    .with("item", st(&text_at(&d, "item")))
                    .with("bytes", Dat::U64(t.len() as u64))
                    .with("dir", st(if dir == Dir::In { "in" } else { "out" })));
            }
            if kind == "Forgetful" {
                // A filter that keeps a field it should not: the sink's redactor still covers it.
                return Some(Frame::new(&[&c.sid], &c.dev).with("token", st(&text_at(&d, "token"))));
            }
            None
        };
        let tap = Tap::new(sink.clone(), "b9", filter);
        let c = conn("sess-2");
        let raw = "RAW-FACE-TEMPLATE-0123456789";
        let enrol = fmt!("{{\"kind\":\"EnrolBundle\",\"bundle\":\"b-7\",\"item\":\"face-3\",\"blob\":\"{}\"}}", raw);
        res!(read_one(&res!(from_client(&text(&enrol))), &tap, &c).await);
        res!(encode_message_tapped(&text(&enrol), false, CHUNK, CHUNK, &tap, &c));
        let leaky = "PLANT-token-from-a-filter";
        let forgot = fmt!("{{\"kind\":\"Forgetful\",\"token\":\"{}\"}}", leaky);
        res!(read_one(&res!(from_client(&text(&forgot))), &tap, &c).await);

        let ev = res!(events(&sink, &["sess-2"]));
        assert_eq!(ev.len(), 3, "{:?}", ev);
        for (i, dir) in ["in", "out"].iter().enumerate() {
            assert_eq!(text_at(&ev[i], "kind"), "EnrolBundle");
            assert_eq!(text_at(&ev[i], "bundle"), "b-7");
            assert_eq!(text_at(&ev[i], "item"), "face-3");
            assert_eq!(num_at(&ev[i], "bytes"), Some(enrol.len() as u64));
            assert_eq!(text_at(&ev[i], "dir"), *dir);
        }
        assert!(text_at(&ev[2], "token").starts_with("[redacted"), "{:?}", ev[2]);
        let bytes = res!(all_bytes(&s.dir()));
        assert!(!has(&bytes, raw), "the raw payload reached a file");
        assert!(!has(&bytes, leaky), "a forgetful filter leaked past the sink's redactor");
        assert!(has(&bytes, "face-3"), "the reduction is there");
        Ok(())
    }

    #[tokio::test]
    async fn none_drops_a_frame_and_leaves_no_gap_in_the_sequence() -> Outcome<()> {
        let s = Scratch::new("tap-none");
        let sink = Arc::new(Sink::new(s.dir(), Gates::default()));
        // Keeps the text frames only.
        let tap = Tap::new(sink.clone(), "b", |_d: Dir, c: &Conn, m: &WebSocketMessage| match m {
            WebSocketMessage::Text(_)   => Some(Frame::new(&[&c.sid], &c.dev).shape(m)),
            _                           => None,
        });
        let c = conn("sess-3");
        for m in [text("a"), WebSocketMessage::Binary(vec![0]), text("bb"), WebSocketMessage::Ping(vec![]), text("ccc")] {
            res!(read_one(&res!(from_client(&m)), &tap, &c).await);
        }
        let ev = res!(events(&sink, &["sess-3"]));
        let ns: Vec<Option<u64>> = ev.iter().map(|e| num_at(e, "n")).collect();
        assert_eq!(ns, vec![Some(1), Some(2), Some(3)], "{:?}", ev);
        let sizes: Vec<Option<u64>> = ev.iter().map(|e| num_at(e, "bytes")).collect();
        assert_eq!(sizes, vec![Some(1), Some(2), Some(3)]);
        Ok(())
    }

    #[tokio::test]
    async fn a_sink_that_cannot_write_counts_the_loss_and_the_frame_still_flows() -> Outcome<()> {
        let s = Scratch::new("tap-lost");
        res!(fs::create_dir_all(&s.0));
        // A regular file where the directory must go.
        let blocker = s.0.join("blocker");
        res!(fs::write(&blocker, b"x"));
        let sink = Arc::new(Sink::new(blocker.join("lens"), Gates::default()));
        let tap = Tap::new(sink.clone(), "b", shape_only);
        let c = conn("sess-4");
        for want in ["one", "two", "three"] {
            let got = res!(read_one(&res!(from_client(&text(want))), &tap, &c).await);
            assert!(matches!(got, Some(WebSocketMessage::Text(ref t)) if t == want), "the frame must flow: {:?}", got);
        }
        let out = res!(encode_message_tapped(&text("x"), false, CHUNK, CHUNK, &tap, &c));
        assert!(!out.is_empty());
        assert_eq!(tap.lost(), 4, "each write that failed is counted");
        Ok(())
    }

    type Echo<'a, S, X> = WebSocket<'a, 8, u64, (), (), NoDatabase<8, u64, (), ()>, S, WebSocketEchoHandler, X>;

    #[tokio::test]
    async fn a_websocket_taps_its_own_read_and_send() -> Outcome<()> {
        let s = Scratch::new("tap-ws");
        let sink = Arc::new(Sink::new(s.dir(), Gates::default()));
        let tap = Tap::new(sink.clone(), "b", shape_only);
        let (mut server_end, mut client_end) = duplex(8_192);
        let mut ws = Echo::new_server(&mut server_end, WebSocketEchoHandler, CHUNK, CHUNK)
            .with_tap(&tap, conn("sess-5"));
        res!(client_end.write_all(&res!(from_client(&text("hello")))).await);
        let got = res!(ws.read().await);
        assert!(matches!(got, Some(WebSocketMessage::Text(ref t)) if t == "hello"));
        res!(ws.send(&text("hello back")).await);
        // The peer hears the same bytes the tap saw framed.
        let mut buf = Vec::new();
        let heard = res!(read_message(&mut client_end, &mut buf, CHUNK, WebSocketLimits::default()).await);
        assert!(matches!(heard, Some(WebSocketMessage::Text(ref t)) if t == "hello back"));
        let ev = res!(events(&sink, &["sess-5"]));
        assert_eq!(ev.len(), 2, "{:?}", ev);
        assert_eq!((text_at(&ev[0], "op"), num_at(&ev[0], "bytes")), ("text".to_string(), Some(5)));
        assert_eq!((text_at(&ev[1], "op"), num_at(&ev[1], "bytes")), ("text".to_string(), Some(10)));
        let tags: Vec<String> = res!(lines(&sink.path(&["sess-5"]))).iter().map(|l| text_at(l, "tag")).collect();
        assert_eq!(tags, vec!["ev frame.in".to_string(), "ev frame.out".to_string()]);
        Ok(())
    }

    #[tokio::test]
    async fn a_websocket_with_no_tap_compiles_unchanged_and_behaves() -> Outcome<()> {
        let (mut server_end, mut client_end) = duplex(8_192);
        // The eight-argument spelling, as `fe2o3_steel` writes it, still names a complete type.
        let mut ws: WebSocket<'_, 8, u64, (), (), NoDatabase<8, u64, (), ()>, _, WebSocketEchoHandler> =
            WebSocket::new_server(&mut server_end, WebSocketEchoHandler, CHUNK, CHUNK);
        res!(client_end.write_all(&res!(from_client(&text("plain")))).await);
        let got = res!(ws.read().await);
        assert!(matches!(got, Some(WebSocketMessage::Text(ref t)) if t == "plain"));
        res!(ws.send(&text("plain back")).await);
        let mut buf = Vec::new();
        let heard = res!(read_message(&mut client_end, &mut buf, CHUNK, WebSocketLimits::default()).await);
        assert!(matches!(heard, Some(WebSocketMessage::Text(ref t)) if t == "plain back"));
        Ok(())
    }

    // Zero cost with no tap is shown by type, not by counting allocations: a counting global
    // allocator needs `unsafe`, which this tree forbids. `NoTap` and its context occupy no bytes,
    // its hooks are empty and inlined, and the tapped free functions give what the untapped ones
    // give, byte for byte.
    #[tokio::test]
    async fn no_tap_costs_nothing_and_changes_nothing() -> Outcome<()> {
        assert_eq!(std::mem::size_of::<NoTap>(), 0);
        assert_eq!(std::mem::size_of::<<NoTap as FrameTap>::Ctx>(), 0);
        for m in [text("same"), WebSocketMessage::Binary(vec![9u8; 2_000]), WebSocketMessage::Ping(vec![1])] {
            // Unmasked, so the framing is deterministic.
            let plain = res!(encode_message(&m, false, 512, 512));
            let tapped = res!(encode_message_tapped(&m, false, 512, 512, &NoTap, &()));
            assert_eq!(plain, tapped);
            let mut a: &[u8] = &plain;
            let mut b: &[u8] = &plain;
            let (mut ba, mut bb) = (Vec::new(), Vec::new());
            let x = res!(read_message(&mut a, &mut ba, 512, WebSocketLimits::default()).await);
            let y = res!(read_message_tapped(&mut b, &mut bb, 512, WebSocketLimits::default(), &NoTap, &()).await);
            assert_eq!(fmt!("{:?}", x), fmt!("{:?}", y));
            assert_eq!(a.len(), b.len(), "both consumed the same bytes");
        }
        // The same holds for a tap behind a reference or an `Arc`.
        let s = Scratch::new("tap-arc");
        let sink = Arc::new(Sink::new(s.dir(), Gates::default()));
        let tap = Arc::new(Tap::new(sink.clone(), "b", shape_only));
        let c = conn("sess-6");
        res!(read_one(&res!(from_client(&text("via arc"))), &tap, &c).await);
        assert_eq!(res!(events(&sink, &["sess-6"])).len(), 1);
        Ok(())
    }

    #[test]
    fn a_direction_names_its_kind() {
        assert_eq!(Dir::In.kind(), "frame.in");
        assert_eq!(Dir::Out.kind(), "frame.out");
    }
}
