// GENERATED FILE. DO NOT EDIT.
//
// The generated Unicode tables.
//
// Generated by fe2o3_text/src/bin/gen_unicode.rs from the Unicode Character Database,
// version 17.0.0, at https://www.unicode.org/Public/17.0.0/.
// Run `cargo run -p oxedyne_fe2o3_text --bin gen_unicode` to rebuild.

//! The tables are partitions of the code point space: a sorted array of run start code points,
//! and a parallel array of the value each run takes. A lookup is a binary search of the starts,
//! about eleven steps for the largest table. This representation was chosen over a staged trie
//! because the tables are committed source: a partition of the Line_Break property is a few
//! thousand entries where a two level trie is tens of thousands, and the difference in lookup cost
//! is invisible next to the rest of a segmentation pass.

pub mod bidi;
pub mod lb;
pub mod norm;
pub mod prop;
pub mod seg;

/// The Unicode Character Database version every table in this module was generated from.
pub const UCD_VERSION: &str = "17.0.0";
