// GENERATED FILE. DO NOT EDIT.
//
// The Unicode character property enums.
//
// Generated by fe2o3_text/src/bin/gen_unicode.rs from the Unicode Character Database,
// version 17.0.0, at https://www.unicode.org/Public/17.0.0/.
// Run `cargo run -p oxedyne_fe2o3_text --bin gen_unicode` to rebuild.


use crate::unicode::lookup::Partitioned;

/// The Line_Break property of UAX #14, as the UCD gives it, before any tailoring.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum LineBreakClass {
	/// Unknown, treated as AL.
	XX,
	/// Ambiguous, treated as AL by default.
	AI,
	/// Aksara.
	AK,
	/// Alphabetic.
	AL,
	/// Aksara pre-base.
	AP,
	/// Aksara start.
	AS,
	/// Break opportunity before and after.
	B2,
	/// Break after.
	BA,
	/// Break before.
	BB,
	/// Mandatory break.
	BK,
	/// Contingent break opportunity.
	CB,
	/// Conditional Japanese starter, treated as NS by default.
	CJ,
	/// Close punctuation.
	CL,
	/// Combining mark.
	CM,
	/// Close parenthesis.
	CP,
	/// Carriage return.
	CR,
	/// Emoji base.
	EB,
	/// Emoji modifier.
	EM,
	/// Exclamation or interrogation.
	EX,
	/// Non-breaking glue.
	GL,
	/// Hangul LV syllable.
	H2,
	/// Hangul LVT syllable.
	H3,
	/// Unambiguous hyphen.
	HH,
	/// Hebrew letter.
	HL,
	/// Hyphen.
	HY,
	/// Ideographic.
	ID,
	/// Inseparable.
	IN,
	/// Infix numeric separator.
	IS,
	/// Hangul leading jamo.
	JL,
	/// Hangul trailing jamo.
	JT,
	/// Hangul vowel jamo.
	JV,
	/// Line feed.
	LF,
	/// Next line.
	NL,
	/// Nonstarter.
	NS,
	/// Numeric.
	NU,
	/// Open punctuation.
	OP,
	/// Postfix numeric.
	PO,
	/// Prefix numeric.
	PR,
	/// Quotation.
	QU,
	/// Regional indicator.
	RI,
	/// Complex context, South East Asian.
	SA,
	/// Surrogate, treated as AL.
	SG,
	/// Space.
	SP,
	/// Symbols allowing break after.
	SY,
	/// Virama final.
	VF,
	/// Virama.
	VI,
	/// Word joiner.
	WJ,
	/// Zero width space.
	ZW,
	/// Zero width joiner.
	ZWJ,
}

impl Partitioned for LineBreakClass {

	const DEFAULT: Self = Self::XX;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::lb::LB_STARTS, &super::lb::LB_VALS)
	}
}

/// The Grapheme_Cluster_Break property of UAX #29.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum GraphemeClass {
	/// Any character not in another class.
	Other,
	/// Carriage return.
	CR,
	/// Line feed.
	LF,
	/// A control, format or line separator character.
	Control,
	/// A character that extends the preceding one.
	Extend,
	/// Zero width joiner.
	ZWJ,
	/// One half of a flag sequence. The UCD name is `Regional_Indicator`.
	RegionalIndicator,
	/// A character that prefixes the following one.
	Prepend,
	/// A spacing combining mark.
	SpacingMark,
	/// Hangul leading jamo.
	L,
	/// Hangul vowel jamo.
	V,
	/// Hangul trailing jamo.
	T,
	/// Hangul LV syllable.
	LV,
	/// Hangul LVT syllable.
	LVT,
}

impl Partitioned for GraphemeClass {

	const DEFAULT: Self = Self::Other;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::seg::GCB_STARTS, &super::seg::GCB_VALS)
	}
}

/// The Word_Break property of UAX #29.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum WordClass {
	/// Any character not in another class.
	Other,
	/// Carriage return.
	CR,
	/// Line feed.
	LF,
	/// A newline character other than CR or LF.
	Newline,
	/// A character that extends the preceding one.
	Extend,
	/// A format character.
	Format,
	/// A katakana character.
	Katakana,
	/// A letter that takes part in words.
	ALetter,
	/// A character found inside a word, such as a colon.
	MidLetter,
	/// A character found inside a number, such as a comma.
	MidNum,
	/// A character found inside either a word or a number.
	MidNumLet,
	/// A decimal digit.
	Numeric,
	/// A character that joins words and numbers, such as an underscore.
	ExtendNumLet,
	/// One half of a flag sequence. The UCD name is `Regional_Indicator`.
	RegionalIndicator,
	/// A Hebrew letter. The UCD name is `Hebrew_Letter`.
	HebrewLetter,
	/// A double quotation mark. The UCD name is `Double_Quote`.
	DoubleQuote,
	/// A single quotation mark. The UCD name is `Single_Quote`.
	SingleQuote,
	/// Zero width joiner.
	ZWJ,
	/// A space that separates words.
	WSegSpace,
}

impl Partitioned for WordClass {

	const DEFAULT: Self = Self::Other;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::seg::WB_STARTS, &super::seg::WB_VALS)
	}
}

/// The Bidi_Class property of UAX #9.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BidiClass {
	/// Strong left to right. The UCD name is `Left_To_Right`.
	L,
	/// Strong right to left. The UCD name is `Right_To_Left`.
	R,
	/// Strong right to left Arabic. The UCD name is `Arabic_Letter`.
	AL,
	/// European number. The UCD name is `European_Number`.
	EN,
	/// European number separator. The UCD name is `European_Separator`.
	ES,
	/// European number terminator. The UCD name is `European_Terminator`.
	ET,
	/// Arabic number. The UCD name is `Arabic_Number`.
	AN,
	/// Common number separator. The UCD name is `Common_Separator`.
	CS,
	/// Nonspacing mark. The UCD name is `Nonspacing_Mark`.
	NSM,
	/// Boundary neutral. The UCD name is `Boundary_Neutral`.
	BN,
	/// Paragraph separator. The UCD name is `Paragraph_Separator`.
	B,
	/// Segment separator. The UCD name is `Segment_Separator`.
	S,
	/// Whitespace. The UCD name is `White_Space`.
	WS,
	/// Other neutral. The UCD name is `Other_Neutral`.
	ON,
	/// Left to right embedding. The UCD name is `Left_To_Right_Embedding`.
	LRE,
	/// Left to right override. The UCD name is `Left_To_Right_Override`.
	LRO,
	/// Right to left embedding. The UCD name is `Right_To_Left_Embedding`.
	RLE,
	/// Right to left override. The UCD name is `Right_To_Left_Override`.
	RLO,
	/// Pop directional format. The UCD name is `Pop_Directional_Format`.
	PDF,
	/// Left to right isolate. The UCD name is `Left_To_Right_Isolate`.
	LRI,
	/// Right to left isolate. The UCD name is `Right_To_Left_Isolate`.
	RLI,
	/// First strong isolate. The UCD name is `First_Strong_Isolate`.
	FSI,
	/// Pop directional isolate. The UCD name is `Pop_Directional_Isolate`.
	PDI,
}

impl Partitioned for BidiClass {

	const DEFAULT: Self = Self::L;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::bidi::BIDI_STARTS, &super::bidi::BIDI_VALS)
	}
}

/// The Indic_Conjunct_Break property of UAX #44, which grapheme rule GB9c consults.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ConjunctBreak {
	/// Not part of a conjunct.
	None,
	/// A consonant that can begin or end a conjunct.
	Consonant,
	/// A mark that does not interrupt a conjunct.
	Extend,
	/// A virama that joins two consonants.
	Linker,
}

/// The Bidi_Paired_Bracket_Type property of UAX #9.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BracketKind {
	/// Not a paired bracket.
	None,
	/// An opening bracket.
	Open,
	/// A closing bracket.
	Close,
}
