// GENERATED FILE. DO NOT EDIT.
//
// The Unicode character property enums.
//
// Generated by fe2o3_text/src/bin/gen_unicode.rs from the Unicode Character Database,
// version 17.0.0, at https://www.unicode.org/Public/17.0.0/.
// Run `cargo run -p oxedyne_fe2o3_text --bin gen_unicode` to rebuild.


use crate::unicode::lookup::Partitioned;

/// The Line_Break property of UAX #14, as the UCD gives it, before any tailoring.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum LineBreakClass {
	/// Unknown, treated as AL.
	XX,
	/// Ambiguous, treated as AL by default.
	AI,
	/// Aksara.
	AK,
	/// Alphabetic.
	AL,
	/// Aksara pre-base.
	AP,
	/// Aksara start.
	AS,
	/// Break opportunity before and after.
	B2,
	/// Break after.
	BA,
	/// Break before.
	BB,
	/// Mandatory break.
	BK,
	/// Contingent break opportunity.
	CB,
	/// Conditional Japanese starter, treated as NS by default.
	CJ,
	/// Close punctuation.
	CL,
	/// Combining mark.
	CM,
	/// Close parenthesis.
	CP,
	/// Carriage return.
	CR,
	/// Emoji base.
	EB,
	/// Emoji modifier.
	EM,
	/// Exclamation or interrogation.
	EX,
	/// Non-breaking glue.
	GL,
	/// Hangul LV syllable.
	H2,
	/// Hangul LVT syllable.
	H3,
	/// Unambiguous hyphen.
	HH,
	/// Hebrew letter.
	HL,
	/// Hyphen.
	HY,
	/// Ideographic.
	ID,
	/// Inseparable.
	IN,
	/// Infix numeric separator.
	IS,
	/// Hangul leading jamo.
	JL,
	/// Hangul trailing jamo.
	JT,
	/// Hangul vowel jamo.
	JV,
	/// Line feed.
	LF,
	/// Next line.
	NL,
	/// Nonstarter.
	NS,
	/// Numeric.
	NU,
	/// Open punctuation.
	OP,
	/// Postfix numeric.
	PO,
	/// Prefix numeric.
	PR,
	/// Quotation.
	QU,
	/// Regional indicator.
	RI,
	/// Complex context, South East Asian.
	SA,
	/// Surrogate, treated as AL.
	SG,
	/// Space.
	SP,
	/// Symbols allowing break after.
	SY,
	/// Virama final.
	VF,
	/// Virama.
	VI,
	/// Word joiner.
	WJ,
	/// Zero width space.
	ZW,
	/// Zero width joiner.
	ZWJ,
}

impl Partitioned for LineBreakClass {

	const DEFAULT: Self = Self::XX;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::lb::LB_STARTS, &super::lb::LB_VALS)
	}
}

/// The Grapheme_Cluster_Break property of UAX #29.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum GraphemeClass {
	/// Any character not in another class.
	Other,
	/// Carriage return.
	CR,
	/// Line feed.
	LF,
	/// A control, format or line separator character.
	Control,
	/// A character that extends the preceding one.
	Extend,
	/// Zero width joiner.
	ZWJ,
	/// One half of a flag sequence. The UCD name is `Regional_Indicator`.
	RegionalIndicator,
	/// A character that prefixes the following one.
	Prepend,
	/// A spacing combining mark.
	SpacingMark,
	/// Hangul leading jamo.
	L,
	/// Hangul vowel jamo.
	V,
	/// Hangul trailing jamo.
	T,
	/// Hangul LV syllable.
	LV,
	/// Hangul LVT syllable.
	LVT,
}

impl Partitioned for GraphemeClass {

	const DEFAULT: Self = Self::Other;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::seg::GCB_STARTS, &super::seg::GCB_VALS)
	}
}

/// The Word_Break property of UAX #29.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum WordClass {
	/// Any character not in another class.
	Other,
	/// Carriage return.
	CR,
	/// Line feed.
	LF,
	/// A newline character other than CR or LF.
	Newline,
	/// A character that extends the preceding one.
	Extend,
	/// A format character.
	Format,
	/// A katakana character.
	Katakana,
	/// A letter that takes part in words.
	ALetter,
	/// A character found inside a word, such as a colon.
	MidLetter,
	/// A character found inside a number, such as a comma.
	MidNum,
	/// A character found inside either a word or a number.
	MidNumLet,
	/// A decimal digit.
	Numeric,
	/// A character that joins words and numbers, such as an underscore.
	ExtendNumLet,
	/// One half of a flag sequence. The UCD name is `Regional_Indicator`.
	RegionalIndicator,
	/// A Hebrew letter. The UCD name is `Hebrew_Letter`.
	HebrewLetter,
	/// A double quotation mark. The UCD name is `Double_Quote`.
	DoubleQuote,
	/// A single quotation mark. The UCD name is `Single_Quote`.
	SingleQuote,
	/// Zero width joiner.
	ZWJ,
	/// A space that separates words.
	WSegSpace,
}

impl Partitioned for WordClass {

	const DEFAULT: Self = Self::Other;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::seg::WB_STARTS, &super::seg::WB_VALS)
	}
}

/// The Bidi_Class property of UAX #9.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BidiClass {
	/// Strong left to right. The UCD name is `Left_To_Right`.
	L,
	/// Strong right to left. The UCD name is `Right_To_Left`.
	R,
	/// Strong right to left Arabic. The UCD name is `Arabic_Letter`.
	AL,
	/// European number. The UCD name is `European_Number`.
	EN,
	/// European number separator. The UCD name is `European_Separator`.
	ES,
	/// European number terminator. The UCD name is `European_Terminator`.
	ET,
	/// Arabic number. The UCD name is `Arabic_Number`.
	AN,
	/// Common number separator. The UCD name is `Common_Separator`.
	CS,
	/// Nonspacing mark. The UCD name is `Nonspacing_Mark`.
	NSM,
	/// Boundary neutral. The UCD name is `Boundary_Neutral`.
	BN,
	/// Paragraph separator. The UCD name is `Paragraph_Separator`.
	B,
	/// Segment separator. The UCD name is `Segment_Separator`.
	S,
	/// Whitespace. The UCD name is `White_Space`.
	WS,
	/// Other neutral. The UCD name is `Other_Neutral`.
	ON,
	/// Left to right embedding. The UCD name is `Left_To_Right_Embedding`.
	LRE,
	/// Left to right override. The UCD name is `Left_To_Right_Override`.
	LRO,
	/// Right to left embedding. The UCD name is `Right_To_Left_Embedding`.
	RLE,
	/// Right to left override. The UCD name is `Right_To_Left_Override`.
	RLO,
	/// Pop directional format. The UCD name is `Pop_Directional_Format`.
	PDF,
	/// Left to right isolate. The UCD name is `Left_To_Right_Isolate`.
	LRI,
	/// Right to left isolate. The UCD name is `Right_To_Left_Isolate`.
	RLI,
	/// First strong isolate. The UCD name is `First_Strong_Isolate`.
	FSI,
	/// Pop directional isolate. The UCD name is `Pop_Directional_Isolate`.
	PDI,
}

impl Partitioned for BidiClass {

	const DEFAULT: Self = Self::L;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::bidi::BIDI_STARTS, &super::bidi::BIDI_VALS)
	}
}

/// The Indic_Conjunct_Break property of UAX #44, which grapheme rule GB9c consults.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ConjunctBreak {
	/// Not part of a conjunct.
	None,
	/// A consonant that can begin or end a conjunct.
	Consonant,
	/// A mark that does not interrupt a conjunct.
	Extend,
	/// A virama that joins two consonants.
	Linker,
}

/// The Bidi_Paired_Bracket_Type property of UAX #9.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BracketKind {
	/// Not a paired bracket.
	None,
	/// An opening bracket.
	Open,
	/// A closing bracket.
	Close,
}

/// The General_Category property of UAX #44, by its two letter abbreviation.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum GeneralCategory {
	Lu,
	Ll,
	Lt,
	Lm,
	Lo,
	Mn,
	Mc,
	Me,
	Nd,
	Nl,
	No,
	Pc,
	Pd,
	Ps,
	Pe,
	Pi,
	Pf,
	Po,
	Sm,
	Sc,
	Sk,
	So,
	Zs,
	Zl,
	Zp,
	Cc,
	Cf,
	Cs,
	Co,
	Cn,
}

impl Partitioned for GeneralCategory {

	const DEFAULT: Self = Self::Cn;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::cat::GC_STARTS, &super::cat::GC_VALS)
	}
}

impl GeneralCategory {

	/// The long UCD name, `Uppercase_Letter` for `Lu`.
	pub fn name(self) -> &'static str {
		match self {
			Self::Lu	=> "Uppercase_Letter",
			Self::Ll	=> "Lowercase_Letter",
			Self::Lt	=> "Titlecase_Letter",
			Self::Lm	=> "Modifier_Letter",
			Self::Lo	=> "Other_Letter",
			Self::Mn	=> "Nonspacing_Mark",
			Self::Mc	=> "Spacing_Mark",
			Self::Me	=> "Enclosing_Mark",
			Self::Nd	=> "Decimal_Number",
			Self::Nl	=> "Letter_Number",
			Self::No	=> "Other_Number",
			Self::Pc	=> "Connector_Punctuation",
			Self::Pd	=> "Dash_Punctuation",
			Self::Ps	=> "Open_Punctuation",
			Self::Pe	=> "Close_Punctuation",
			Self::Pi	=> "Initial_Punctuation",
			Self::Pf	=> "Final_Punctuation",
			Self::Po	=> "Other_Punctuation",
			Self::Sm	=> "Math_Symbol",
			Self::Sc	=> "Currency_Symbol",
			Self::Sk	=> "Modifier_Symbol",
			Self::So	=> "Other_Symbol",
			Self::Zs	=> "Space_Separator",
			Self::Zl	=> "Line_Separator",
			Self::Zp	=> "Paragraph_Separator",
			Self::Cc	=> "Control",
			Self::Cf	=> "Format",
			Self::Cs	=> "Surrogate",
			Self::Co	=> "Private_Use",
			Self::Cn	=> "Unassigned",
		}
	}

	/// The two letter abbreviation.
	pub fn abbr(self) -> &'static str {
		match self {
			Self::Lu	=> "Lu",
			Self::Ll	=> "Ll",
			Self::Lt	=> "Lt",
			Self::Lm	=> "Lm",
			Self::Lo	=> "Lo",
			Self::Mn	=> "Mn",
			Self::Mc	=> "Mc",
			Self::Me	=> "Me",
			Self::Nd	=> "Nd",
			Self::Nl	=> "Nl",
			Self::No	=> "No",
			Self::Pc	=> "Pc",
			Self::Pd	=> "Pd",
			Self::Ps	=> "Ps",
			Self::Pe	=> "Pe",
			Self::Pi	=> "Pi",
			Self::Pf	=> "Pf",
			Self::Po	=> "Po",
			Self::Sm	=> "Sm",
			Self::Sc	=> "Sc",
			Self::Sk	=> "Sk",
			Self::So	=> "So",
			Self::Zs	=> "Zs",
			Self::Zl	=> "Zl",
			Self::Zp	=> "Zp",
			Self::Cc	=> "Cc",
			Self::Cf	=> "Cf",
			Self::Cs	=> "Cs",
			Self::Co	=> "Co",
			Self::Cn	=> "Cn",
		}
	}
}

/// The Script property of UAX #24. A character's Script_Extensions, the wider set of scripts it
/// is used with, are in `unicode::property`.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Script {
	Adlam,
	CaucasianAlbanian,
	Ahom,
	Arabic,
	ImperialAramaic,
	Armenian,
	Avestan,
	Balinese,
	Bamum,
	BassaVah,
	Batak,
	Bengali,
	BeriaErfe,
	Bhaiksuki,
	Bopomofo,
	Brahmi,
	Braille,
	Buginese,
	Buhid,
	Chakma,
	CanadianAboriginal,
	Carian,
	Cham,
	Cherokee,
	Chorasmian,
	Coptic,
	CyproMinoan,
	Cypriot,
	Cyrillic,
	Devanagari,
	DivesAkuru,
	Dogra,
	Deseret,
	Duployan,
	EgyptianHieroglyphs,
	Elbasan,
	Elymaic,
	Ethiopic,
	Garay,
	Georgian,
	Glagolitic,
	GunjalaGondi,
	MasaramGondi,
	Gothic,
	Grantha,
	Greek,
	Gujarati,
	GurungKhema,
	Gurmukhi,
	Hangul,
	Han,
	Hanunoo,
	Hatran,
	Hebrew,
	Hiragana,
	AnatolianHieroglyphs,
	PahawhHmong,
	NyiakengPuachueHmong,
	KatakanaOrHiragana,
	OldHungarian,
	OldItalic,
	Javanese,
	KayahLi,
	Katakana,
	Kawi,
	Kharoshthi,
	Khmer,
	Khojki,
	KhitanSmallScript,
	Kannada,
	KiratRai,
	Kaithi,
	TaiTham,
	Lao,
	Latin,
	Lepcha,
	Limbu,
	LinearA,
	LinearB,
	Lisu,
	Lycian,
	Lydian,
	Mahajani,
	Makasar,
	Mandaic,
	Manichaean,
	Marchen,
	Medefaidrin,
	MendeKikakui,
	MeroiticCursive,
	MeroiticHieroglyphs,
	Malayalam,
	Modi,
	Mongolian,
	Mro,
	MeeteiMayek,
	Multani,
	Myanmar,
	NagMundari,
	Nandinagari,
	OldNorthArabian,
	Nabataean,
	Newa,
	Nko,
	Nushu,
	Ogham,
	OlChiki,
	OlOnal,
	OldTurkic,
	Oriya,
	Osage,
	Osmanya,
	OldUyghur,
	Palmyrene,
	PauCinHau,
	OldPermic,
	PhagsPa,
	InscriptionalPahlavi,
	PsalterPahlavi,
	Phoenician,
	Miao,
	InscriptionalParthian,
	Rejang,
	HanifiRohingya,
	Runic,
	Samaritan,
	OldSouthArabian,
	Saurashtra,
	SignWriting,
	Shavian,
	Sharada,
	Siddham,
	Sidetic,
	Khudawadi,
	Sinhala,
	Sogdian,
	OldSogdian,
	SoraSompeng,
	Soyombo,
	Sundanese,
	Sunuwar,
	SylotiNagri,
	Syriac,
	Tagbanwa,
	Takri,
	TaiLe,
	NewTaiLue,
	Tamil,
	Tangut,
	TaiViet,
	TaiYo,
	Telugu,
	Tifinagh,
	Tagalog,
	Thaana,
	Thai,
	Tibetan,
	Tirhuta,
	Tangsa,
	Todhri,
	TolongSiki,
	Toto,
	TuluTigalari,
	Ugaritic,
	Vai,
	Vithkuqi,
	WarangCiti,
	Wancho,
	OldPersian,
	Cuneiform,
	Yezidi,
	Yi,
	ZanabazarSquare,
	Inherited,
	Common,
	Unknown,
}

impl Partitioned for Script {

	const DEFAULT: Self = Self::Unknown;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::cat::SC_STARTS, &super::cat::SC_VALS)
	}
}

impl Script {

	/// The long UCD name, `Old_Italic` for instance.
	pub fn name(self) -> &'static str {
		match self {
			Self::Adlam	=> "Adlam",
			Self::CaucasianAlbanian	=> "Caucasian_Albanian",
			Self::Ahom	=> "Ahom",
			Self::Arabic	=> "Arabic",
			Self::ImperialAramaic	=> "Imperial_Aramaic",
			Self::Armenian	=> "Armenian",
			Self::Avestan	=> "Avestan",
			Self::Balinese	=> "Balinese",
			Self::Bamum	=> "Bamum",
			Self::BassaVah	=> "Bassa_Vah",
			Self::Batak	=> "Batak",
			Self::Bengali	=> "Bengali",
			Self::BeriaErfe	=> "Beria_Erfe",
			Self::Bhaiksuki	=> "Bhaiksuki",
			Self::Bopomofo	=> "Bopomofo",
			Self::Brahmi	=> "Brahmi",
			Self::Braille	=> "Braille",
			Self::Buginese	=> "Buginese",
			Self::Buhid	=> "Buhid",
			Self::Chakma	=> "Chakma",
			Self::CanadianAboriginal	=> "Canadian_Aboriginal",
			Self::Carian	=> "Carian",
			Self::Cham	=> "Cham",
			Self::Cherokee	=> "Cherokee",
			Self::Chorasmian	=> "Chorasmian",
			Self::Coptic	=> "Coptic",
			Self::CyproMinoan	=> "Cypro_Minoan",
			Self::Cypriot	=> "Cypriot",
			Self::Cyrillic	=> "Cyrillic",
			Self::Devanagari	=> "Devanagari",
			Self::DivesAkuru	=> "Dives_Akuru",
			Self::Dogra	=> "Dogra",
			Self::Deseret	=> "Deseret",
			Self::Duployan	=> "Duployan",
			Self::EgyptianHieroglyphs	=> "Egyptian_Hieroglyphs",
			Self::Elbasan	=> "Elbasan",
			Self::Elymaic	=> "Elymaic",
			Self::Ethiopic	=> "Ethiopic",
			Self::Garay	=> "Garay",
			Self::Georgian	=> "Georgian",
			Self::Glagolitic	=> "Glagolitic",
			Self::GunjalaGondi	=> "Gunjala_Gondi",
			Self::MasaramGondi	=> "Masaram_Gondi",
			Self::Gothic	=> "Gothic",
			Self::Grantha	=> "Grantha",
			Self::Greek	=> "Greek",
			Self::Gujarati	=> "Gujarati",
			Self::GurungKhema	=> "Gurung_Khema",
			Self::Gurmukhi	=> "Gurmukhi",
			Self::Hangul	=> "Hangul",
			Self::Han	=> "Han",
			Self::Hanunoo	=> "Hanunoo",
			Self::Hatran	=> "Hatran",
			Self::Hebrew	=> "Hebrew",
			Self::Hiragana	=> "Hiragana",
			Self::AnatolianHieroglyphs	=> "Anatolian_Hieroglyphs",
			Self::PahawhHmong	=> "Pahawh_Hmong",
			Self::NyiakengPuachueHmong	=> "Nyiakeng_Puachue_Hmong",
			Self::KatakanaOrHiragana	=> "Katakana_Or_Hiragana",
			Self::OldHungarian	=> "Old_Hungarian",
			Self::OldItalic	=> "Old_Italic",
			Self::Javanese	=> "Javanese",
			Self::KayahLi	=> "Kayah_Li",
			Self::Katakana	=> "Katakana",
			Self::Kawi	=> "Kawi",
			Self::Kharoshthi	=> "Kharoshthi",
			Self::Khmer	=> "Khmer",
			Self::Khojki	=> "Khojki",
			Self::KhitanSmallScript	=> "Khitan_Small_Script",
			Self::Kannada	=> "Kannada",
			Self::KiratRai	=> "Kirat_Rai",
			Self::Kaithi	=> "Kaithi",
			Self::TaiTham	=> "Tai_Tham",
			Self::Lao	=> "Lao",
			Self::Latin	=> "Latin",
			Self::Lepcha	=> "Lepcha",
			Self::Limbu	=> "Limbu",
			Self::LinearA	=> "Linear_A",
			Self::LinearB	=> "Linear_B",
			Self::Lisu	=> "Lisu",
			Self::Lycian	=> "Lycian",
			Self::Lydian	=> "Lydian",
			Self::Mahajani	=> "Mahajani",
			Self::Makasar	=> "Makasar",
			Self::Mandaic	=> "Mandaic",
			Self::Manichaean	=> "Manichaean",
			Self::Marchen	=> "Marchen",
			Self::Medefaidrin	=> "Medefaidrin",
			Self::MendeKikakui	=> "Mende_Kikakui",
			Self::MeroiticCursive	=> "Meroitic_Cursive",
			Self::MeroiticHieroglyphs	=> "Meroitic_Hieroglyphs",
			Self::Malayalam	=> "Malayalam",
			Self::Modi	=> "Modi",
			Self::Mongolian	=> "Mongolian",
			Self::Mro	=> "Mro",
			Self::MeeteiMayek	=> "Meetei_Mayek",
			Self::Multani	=> "Multani",
			Self::Myanmar	=> "Myanmar",
			Self::NagMundari	=> "Nag_Mundari",
			Self::Nandinagari	=> "Nandinagari",
			Self::OldNorthArabian	=> "Old_North_Arabian",
			Self::Nabataean	=> "Nabataean",
			Self::Newa	=> "Newa",
			Self::Nko	=> "Nko",
			Self::Nushu	=> "Nushu",
			Self::Ogham	=> "Ogham",
			Self::OlChiki	=> "Ol_Chiki",
			Self::OlOnal	=> "Ol_Onal",
			Self::OldTurkic	=> "Old_Turkic",
			Self::Oriya	=> "Oriya",
			Self::Osage	=> "Osage",
			Self::Osmanya	=> "Osmanya",
			Self::OldUyghur	=> "Old_Uyghur",
			Self::Palmyrene	=> "Palmyrene",
			Self::PauCinHau	=> "Pau_Cin_Hau",
			Self::OldPermic	=> "Old_Permic",
			Self::PhagsPa	=> "Phags_Pa",
			Self::InscriptionalPahlavi	=> "Inscriptional_Pahlavi",
			Self::PsalterPahlavi	=> "Psalter_Pahlavi",
			Self::Phoenician	=> "Phoenician",
			Self::Miao	=> "Miao",
			Self::InscriptionalParthian	=> "Inscriptional_Parthian",
			Self::Rejang	=> "Rejang",
			Self::HanifiRohingya	=> "Hanifi_Rohingya",
			Self::Runic	=> "Runic",
			Self::Samaritan	=> "Samaritan",
			Self::OldSouthArabian	=> "Old_South_Arabian",
			Self::Saurashtra	=> "Saurashtra",
			Self::SignWriting	=> "SignWriting",
			Self::Shavian	=> "Shavian",
			Self::Sharada	=> "Sharada",
			Self::Siddham	=> "Siddham",
			Self::Sidetic	=> "Sidetic",
			Self::Khudawadi	=> "Khudawadi",
			Self::Sinhala	=> "Sinhala",
			Self::Sogdian	=> "Sogdian",
			Self::OldSogdian	=> "Old_Sogdian",
			Self::SoraSompeng	=> "Sora_Sompeng",
			Self::Soyombo	=> "Soyombo",
			Self::Sundanese	=> "Sundanese",
			Self::Sunuwar	=> "Sunuwar",
			Self::SylotiNagri	=> "Syloti_Nagri",
			Self::Syriac	=> "Syriac",
			Self::Tagbanwa	=> "Tagbanwa",
			Self::Takri	=> "Takri",
			Self::TaiLe	=> "Tai_Le",
			Self::NewTaiLue	=> "New_Tai_Lue",
			Self::Tamil	=> "Tamil",
			Self::Tangut	=> "Tangut",
			Self::TaiViet	=> "Tai_Viet",
			Self::TaiYo	=> "Tai_Yo",
			Self::Telugu	=> "Telugu",
			Self::Tifinagh	=> "Tifinagh",
			Self::Tagalog	=> "Tagalog",
			Self::Thaana	=> "Thaana",
			Self::Thai	=> "Thai",
			Self::Tibetan	=> "Tibetan",
			Self::Tirhuta	=> "Tirhuta",
			Self::Tangsa	=> "Tangsa",
			Self::Todhri	=> "Todhri",
			Self::TolongSiki	=> "Tolong_Siki",
			Self::Toto	=> "Toto",
			Self::TuluTigalari	=> "Tulu_Tigalari",
			Self::Ugaritic	=> "Ugaritic",
			Self::Vai	=> "Vai",
			Self::Vithkuqi	=> "Vithkuqi",
			Self::WarangCiti	=> "Warang_Citi",
			Self::Wancho	=> "Wancho",
			Self::OldPersian	=> "Old_Persian",
			Self::Cuneiform	=> "Cuneiform",
			Self::Yezidi	=> "Yezidi",
			Self::Yi	=> "Yi",
			Self::ZanabazarSquare	=> "Zanabazar_Square",
			Self::Inherited	=> "Inherited",
			Self::Common	=> "Common",
			Self::Unknown	=> "Unknown",
		}
	}

	/// The four letter ISO 15924 code, `Ital` for Old_Italic.
	pub fn code(self) -> &'static str {
		match self {
			Self::Adlam	=> "Adlm",
			Self::CaucasianAlbanian	=> "Aghb",
			Self::Ahom	=> "Ahom",
			Self::Arabic	=> "Arab",
			Self::ImperialAramaic	=> "Armi",
			Self::Armenian	=> "Armn",
			Self::Avestan	=> "Avst",
			Self::Balinese	=> "Bali",
			Self::Bamum	=> "Bamu",
			Self::BassaVah	=> "Bass",
			Self::Batak	=> "Batk",
			Self::Bengali	=> "Beng",
			Self::BeriaErfe	=> "Berf",
			Self::Bhaiksuki	=> "Bhks",
			Self::Bopomofo	=> "Bopo",
			Self::Brahmi	=> "Brah",
			Self::Braille	=> "Brai",
			Self::Buginese	=> "Bugi",
			Self::Buhid	=> "Buhd",
			Self::Chakma	=> "Cakm",
			Self::CanadianAboriginal	=> "Cans",
			Self::Carian	=> "Cari",
			Self::Cham	=> "Cham",
			Self::Cherokee	=> "Cher",
			Self::Chorasmian	=> "Chrs",
			Self::Coptic	=> "Copt",
			Self::CyproMinoan	=> "Cpmn",
			Self::Cypriot	=> "Cprt",
			Self::Cyrillic	=> "Cyrl",
			Self::Devanagari	=> "Deva",
			Self::DivesAkuru	=> "Diak",
			Self::Dogra	=> "Dogr",
			Self::Deseret	=> "Dsrt",
			Self::Duployan	=> "Dupl",
			Self::EgyptianHieroglyphs	=> "Egyp",
			Self::Elbasan	=> "Elba",
			Self::Elymaic	=> "Elym",
			Self::Ethiopic	=> "Ethi",
			Self::Garay	=> "Gara",
			Self::Georgian	=> "Geor",
			Self::Glagolitic	=> "Glag",
			Self::GunjalaGondi	=> "Gong",
			Self::MasaramGondi	=> "Gonm",
			Self::Gothic	=> "Goth",
			Self::Grantha	=> "Gran",
			Self::Greek	=> "Grek",
			Self::Gujarati	=> "Gujr",
			Self::GurungKhema	=> "Gukh",
			Self::Gurmukhi	=> "Guru",
			Self::Hangul	=> "Hang",
			Self::Han	=> "Hani",
			Self::Hanunoo	=> "Hano",
			Self::Hatran	=> "Hatr",
			Self::Hebrew	=> "Hebr",
			Self::Hiragana	=> "Hira",
			Self::AnatolianHieroglyphs	=> "Hluw",
			Self::PahawhHmong	=> "Hmng",
			Self::NyiakengPuachueHmong	=> "Hmnp",
			Self::KatakanaOrHiragana	=> "Hrkt",
			Self::OldHungarian	=> "Hung",
			Self::OldItalic	=> "Ital",
			Self::Javanese	=> "Java",
			Self::KayahLi	=> "Kali",
			Self::Katakana	=> "Kana",
			Self::Kawi	=> "Kawi",
			Self::Kharoshthi	=> "Khar",
			Self::Khmer	=> "Khmr",
			Self::Khojki	=> "Khoj",
			Self::KhitanSmallScript	=> "Kits",
			Self::Kannada	=> "Knda",
			Self::KiratRai	=> "Krai",
			Self::Kaithi	=> "Kthi",
			Self::TaiTham	=> "Lana",
			Self::Lao	=> "Laoo",
			Self::Latin	=> "Latn",
			Self::Lepcha	=> "Lepc",
			Self::Limbu	=> "Limb",
			Self::LinearA	=> "Lina",
			Self::LinearB	=> "Linb",
			Self::Lisu	=> "Lisu",
			Self::Lycian	=> "Lyci",
			Self::Lydian	=> "Lydi",
			Self::Mahajani	=> "Mahj",
			Self::Makasar	=> "Maka",
			Self::Mandaic	=> "Mand",
			Self::Manichaean	=> "Mani",
			Self::Marchen	=> "Marc",
			Self::Medefaidrin	=> "Medf",
			Self::MendeKikakui	=> "Mend",
			Self::MeroiticCursive	=> "Merc",
			Self::MeroiticHieroglyphs	=> "Mero",
			Self::Malayalam	=> "Mlym",
			Self::Modi	=> "Modi",
			Self::Mongolian	=> "Mong",
			Self::Mro	=> "Mroo",
			Self::MeeteiMayek	=> "Mtei",
			Self::Multani	=> "Mult",
			Self::Myanmar	=> "Mymr",
			Self::NagMundari	=> "Nagm",
			Self::Nandinagari	=> "Nand",
			Self::OldNorthArabian	=> "Narb",
			Self::Nabataean	=> "Nbat",
			Self::Newa	=> "Newa",
			Self::Nko	=> "Nkoo",
			Self::Nushu	=> "Nshu",
			Self::Ogham	=> "Ogam",
			Self::OlChiki	=> "Olck",
			Self::OlOnal	=> "Onao",
			Self::OldTurkic	=> "Orkh",
			Self::Oriya	=> "Orya",
			Self::Osage	=> "Osge",
			Self::Osmanya	=> "Osma",
			Self::OldUyghur	=> "Ougr",
			Self::Palmyrene	=> "Palm",
			Self::PauCinHau	=> "Pauc",
			Self::OldPermic	=> "Perm",
			Self::PhagsPa	=> "Phag",
			Self::InscriptionalPahlavi	=> "Phli",
			Self::PsalterPahlavi	=> "Phlp",
			Self::Phoenician	=> "Phnx",
			Self::Miao	=> "Plrd",
			Self::InscriptionalParthian	=> "Prti",
			Self::Rejang	=> "Rjng",
			Self::HanifiRohingya	=> "Rohg",
			Self::Runic	=> "Runr",
			Self::Samaritan	=> "Samr",
			Self::OldSouthArabian	=> "Sarb",
			Self::Saurashtra	=> "Saur",
			Self::SignWriting	=> "Sgnw",
			Self::Shavian	=> "Shaw",
			Self::Sharada	=> "Shrd",
			Self::Siddham	=> "Sidd",
			Self::Sidetic	=> "Sidt",
			Self::Khudawadi	=> "Sind",
			Self::Sinhala	=> "Sinh",
			Self::Sogdian	=> "Sogd",
			Self::OldSogdian	=> "Sogo",
			Self::SoraSompeng	=> "Sora",
			Self::Soyombo	=> "Soyo",
			Self::Sundanese	=> "Sund",
			Self::Sunuwar	=> "Sunu",
			Self::SylotiNagri	=> "Sylo",
			Self::Syriac	=> "Syrc",
			Self::Tagbanwa	=> "Tagb",
			Self::Takri	=> "Takr",
			Self::TaiLe	=> "Tale",
			Self::NewTaiLue	=> "Talu",
			Self::Tamil	=> "Taml",
			Self::Tangut	=> "Tang",
			Self::TaiViet	=> "Tavt",
			Self::TaiYo	=> "Tayo",
			Self::Telugu	=> "Telu",
			Self::Tifinagh	=> "Tfng",
			Self::Tagalog	=> "Tglg",
			Self::Thaana	=> "Thaa",
			Self::Thai	=> "Thai",
			Self::Tibetan	=> "Tibt",
			Self::Tirhuta	=> "Tirh",
			Self::Tangsa	=> "Tnsa",
			Self::Todhri	=> "Todr",
			Self::TolongSiki	=> "Tols",
			Self::Toto	=> "Toto",
			Self::TuluTigalari	=> "Tutg",
			Self::Ugaritic	=> "Ugar",
			Self::Vai	=> "Vaii",
			Self::Vithkuqi	=> "Vith",
			Self::WarangCiti	=> "Wara",
			Self::Wancho	=> "Wcho",
			Self::OldPersian	=> "Xpeo",
			Self::Cuneiform	=> "Xsux",
			Self::Yezidi	=> "Yezi",
			Self::Yi	=> "Yiii",
			Self::ZanabazarSquare	=> "Zanb",
			Self::Inherited	=> "Zinh",
			Self::Common	=> "Zyyy",
			Self::Unknown	=> "Zzzz",
		}
	}
}

/// The Sentence_Break property of UAX #29.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum SentenceClass {
	ATerm,
	Close,
	CR,
	Extend,
	Format,
	OLetter,
	LF,
	Lower,
	Numeric,
	SContinue,
	Sep,
	Sp,
	STerm,
	Upper,
	Other,
}

impl Partitioned for SentenceClass {

	const DEFAULT: Self = Self::Other;

	fn table() -> (&'static [u32], &'static [Self]) {
		(&super::cat::SB_STARTS, &super::cat::SB_VALS)
	}
}
